### MPRAsnakeflow errors

Error in rule variants_generateVariantTable:
    jobid: 265
    input: /data/gpfs-1/users/kisa11_c/work/coding/MPRA/IGVF_Y1_design/design/final_design/results/final_design/variant_region_map.tsv, results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_2_merged_assigned_counts.tsv.gz, /data/gpfs-1/users/kisa11_c/work/coding/MPRAsnakeflow/workflow/rules/../scripts/variants/generateVariantTable.py
    output: results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_2_variantTable.tsv.gz
    log: results/logs/experiments/variants/generateVariantTable.standard_bwa.assignmentFixDuplicates.standardConfig.NGN2.2.log (check log file(s) for error details)
    conda-env: /data/gpfs-1/users/kisa11_c/work/coding/MPRA/MPRAsnakeflow_projects/conda/0c7550b7451981558658b283bfd9de68_
    shell:

        python /data/gpfs-1/users/kisa11_c/work/coding/MPRAsnakeflow/workflow/rules/../scripts/variants/generateVariantTable.py         --counts results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_2_merged_assigned_counts.tsv.gz         --declaration /data/gpfs-1/users/kisa11_c/work/coding/MPRA/IGVF_Y1_design/design/final_design/results/final_design/variant_region_map.tsv         --output results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_2_variantTable.tsv.gz &> results/logs/experiments/variants/generateVariantTable.standard_bwa.assignmentFixDuplicates.standardConfig.NGN2.2.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 6455429

File "/data/gpfs-1/users/kisa11_c/work/coding/MPRAsnakeflow/workflow/rules/../scripts/variants/generateVariantTable.py", line 39, in cli
    output = declaration.join(counts, on='REF')

In [14]:
import pandas as pd
import numpy as np

In [15]:
# read the count and declaration file and try the code out because error does not tell much 
counts_file = '/data/cephfs-2/unmirrored/groups/ag-kircher/MPRA/IGVF_Y1_design/experiment/resequencing_results/old_bam_filtering/results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_2_merged_assigned_counts.tsv.gz'
declaration_file = '/data/gpfs-1/users/kisa11_c/work/coding/MPRA/IGVF_Y1_design/design/final_design/results/final_design/variant_region_map.tsv'

In [20]:
# declaration file
declaration = pd.read_csv(declaration_file, header=0, sep="\t", index_col=0)
# ID REGION REF ALT

# get count df
counts = pd.read_csv(counts_file, header=0, sep="\t", index_col=0)

In [21]:
declaration.head()

,Region,REF_ID,ALT_ID
Variant,,,
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778471|1-2179591-T-C,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778490|1-2191444-G-A,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778492|1-2192015-G-T,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E1311587|1-2192366-T-G,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778494|1-2193142-G-A,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...

renaming

In [22]:
declaration.rename(columns={col: 'REF' for col in declaration.columns if 'REF' in col}, inplace=True)
declaration.rename(columns={col: 'ALT' for col in declaration.columns if 'ALT' in col}, inplace=True)
declaration.index.rename('ID', inplace=True)
declaration

,Region,REF,ALT_ID
ID,,,
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778471|1-2179591-T-C,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778490|1-2191444-G-A,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778492|1-2192015-G-T,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E1311587|1-2192366-T-G,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
cardiac_neuro_cava_random:SKI|ENSG00000157933.11|EH38E2778494|1-2193142-G-A,cardiac_neuro_cava_random:SKI|ENSG00000157933....,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
...,...,...,...
C_positive_heart_CAD:rs7865618,C_positive_heart_CAD:rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618
C_positive_heart_CAD:rs4977757,C_positive_heart_CAD:rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757
C_positive_heart_CAD:rs1537373,C_positive_heart_CAD:rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373
C_positive_heart_CAD:rs10811656,C_positive_heart_CAD:rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656
C_positive_heart_CAD:rs507666,C_positive_heart_CAD:rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666

In [18]:
print(declaration.columns)
print(counts.columns)

Index(['Region', 'REF', 'ALT'], dtype='object')
Index(['dna_counts', 'rna_counts', 'dna_normalized', 'rna_normalized', 'ratio',
       'log2', 'n_obs_bc'],
      dtype='object')

In [19]:
# join ref
output = declaration.join(counts, on='REF')
output = output.join(counts, on='ALT', lsuffix='_REF', rsuffix='_ALT')
output["log2_expression"] = np.log2(output['ratio_ALT']/output['ratio_REF'])

Problem solved by changing the header of the variant region map

Error in rule variants_correlate:
    jobid: 263
    input: results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_1_variantTable.tsv.gz, results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_2_variantTable.tsv.gz, results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_3_variantTable.tsv.gz, /data/gpfs-1/users/kisa11_c/work/coding/MPRAsnakeflow/workflow/rules/../scripts/variants/correlateVariantTables.py
    output: results/experiments/standard_bwa/statistic/variants/assignmentFixDuplicates/standardConfig/NGN2/NGN2_correlation_variantTable_minBC2.tsv.gz
    log: results/logs/experiments/variants/correlate.standard_bwa.assignmentFixDuplicates.standardConfig.NGN2.NGN2.2.log (check log file(s) for error details)
    conda-env: /data/gpfs-1/users/kisa11_c/work/coding/MPRA/MPRAsnakeflow_projects/conda/0c7550b7451981558658b283bfd9de68_
    shell:

        python /data/gpfs-1/users/kisa11_c/work/coding/MPRAsnakeflow/workflow/rules/../scripts/variants/correlateVariantTables.py         --condition NGN2         --variants 1 results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_1_variantTable.tsv.gz --variants 2 results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_2_variantTable.tsv.gz --variants 3 results/experiments/standard_bwa/variants/assignmentFixDuplicates/standardConfig/NGN2_3_variantTable.tsv.gz         --bc-threshold 2         --output results/experiments/standard_bwa/statistic/variants/assignmentFixDuplicates/standardConfig/NGN2/NGN2_correlation_variantTable_minBC2.tsv.gz &> results/logs/experiments/variants/correlate.standard_bwa.assignmentFixDuplicates.standardConfig.NGN2.NGN2.2.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 6455791

df.append used which is not defined anymore

In [ ]:
Error in rule assigned_counts_combine_replicates_barcode_output:
    jobid: 254
    input: results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_1_barcode_assigned_counts.tsv.gz, results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_2_barcode_assigned_counts.tsv.gz, results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_3_barcode_assigned_counts.tsv.gz, /data/gpfs-1/users/kisa11_c/work/coding/MPRAsnakeflow/workflow/rules/../scripts/count/merge_replicates_barcode_counts.py
    output: results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_allreps_merged_barcode_assigned_counts.tsv.gz
    log: results/logs/assigned_counts/combine_replicates_barcode_output.standard_bwa.NGN2.standardConfig.assignmentFixDuplicates.log (check log file(s) for error details)
    conda-env: /data/gpfs-1/users/kisa11_c/work/coding/MPRA/MPRAsnakeflow_projects/conda/0c7550b7451981558658b283bfd9de68_
    shell:

        python /data/gpfs-1/users/kisa11_c/work/coding/MPRAsnakeflow/workflow/rules/../scripts/count/merge_replicates_barcode_counts.py --counts results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_1_barcode_assigned_counts.tsv.gz --counts results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_2_barcode_assigned_counts.tsv.gz --counts results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_3_barcode_assigned_counts.tsv.gz         --threshold 10         --replicate 1 --replicate 2 --replicate 3          --output results/experiments/standard_bwa/assigned_counts/assignmentFixDuplicates/standardConfig/NGN2_allreps_merged_barcode_assigned_counts.tsv.gz &> results/logs/assigned_counts/combine_replicates_barcode_output.standard_bwa.NGN2.standardConfig.assignmentFixDuplicates.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 6455879

problem column is assumed to be called ID and is called Variant