### Sanity check bc_mpralm results with feedback from Pia
- How many variants go into bc_MPRAlm
  - Without any variant controls: 42129
  - With the variant controls without any matching problem: 41474
- Have they all at least 10 barcodes?
- The following things were checked in another script (analyze_NGN2)
- How do the MPRAlm results look like? (compare log2FC and p-values)
- How many dna and rna counts do we have from these results?

In [41]:
import pandas as pd
import yaml

config_path = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/global80K_config.yaml"
# load config file
with open(config_path, "r") as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

In [42]:
config["files"]["creating"]["toptable_bcMPRAlm"]

'/data/gpfs-1/users/kisa11_c/work/coding/MPRA/IGVF_Y1_design/projects/bc_tradeoff/results/bc_MPRAlm/test_controls_concat/toptable_standard_with_variant_controls_no_downsamplingNGN2.feather'

In [43]:
# bcMPRAlm_table = pd.read_csv(config["files"]["toptable_standard_control_table"], sep="\t")
bcMPRAlm_table = pd.read_csv(config["files"]["creating"]["toptable_bcMPRAlm"], sep="\t")


print("%s analyzable variants"%(bcMPRAlm_table.shape[0])) # 41284 rows; low config: 42137 rows; 34683 with 10 barcodes

34683 analyzable variants

In [44]:
### how many variants in bc mpralm 

### do all of them have 10 barcodes? 
# load the sequence to barcode table
sequence_barcode_association = pd.read_csv(config["files"]["final_design"]["sequence_to_barcode_assignment"], sep="\t", header=None)
sequence_barcode_association.columns = ["barcode", "ID", "alignment_info", "association_info"]
sequence_barcode_association

,barcode,ID,alignment_info,association_info
0,AAAAAAAAAAACGTC,GC_Vista:eye;fb;hb;mb_hs1644_vistaElementContr...,15;270M;NM:i:0;MD:Z:270;60,5/5
1,AAAAAAAAAACAAGT,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,6/7
2,AAAAAAAAAACACCA,cardiac_neuro_cava_random:ALT_FTO|ENSG00000140...,15;270M;NM:i:0;MD:Z:270;6,9/10
3,AAAAAAAAAACCTCG,cardiac_neuro_cava_random:REF_FKRP|ENSG0000018...,15;270M;NM:i:0;MD:Z:270;6,7/7
4,AAAAAAAAAAGCTGG,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,7/8
...,...,...,...,...
6305461,TTTTTTTTTTGACCG,cardiac_neuro_cava_random:ALT_CPS1|ENSG0000002...,15;270M;NM:i:0;MD:Z:270;6,32/33
6305462,TTTTTTTTTTGACGA,cardiac_neuro_cava_random:ALT_ACTN2|ENSG000000...,15;270M;NM:i:0;MD:Z:270;6,11/11
6305463,TTTTTTTTTTGCACA,cardiac_neuro_cava_random:ALT_CARD11|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,22/26
6305464,TTTTTTTTTTGCTAA,cardiac_neuro_cava_random:REF_NR4A2|ENSG000001...,15;270M;NM:i:0;MD:Z:270;6,6/6
6305465,TTTTTTTTTTGTCCC,cardiac_neuro_cava_random:ALT_NBN|ENSG00000104...,15;270M;NM:i:0;MD:Z:270;6,3/3

In [50]:
mpralm_with_barcode = bcMPRAlm_table.merge(sequence_barcode_association, left_on="variant_id", right_on="ID", how="left")
# does not work because matching without variant region map not possible

In [45]:
# how many unique IDs 
mpralm_with_barcode["ID"].nunique()

75004

In [46]:
sequence_barcode_association.columns = ["barcode", "ID", "alignment_info", "association_info"]
sequence_barcode_association

,barcode,ID,alignment_info,association_info
0,AAAAAAAAAAACGTC,GC_Vista:eye;fb;hb;mb_hs1644_vistaElementContr...,15;270M;NM:i:0;MD:Z:270;60,5/5
1,AAAAAAAAAACAAGT,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,6/7
2,AAAAAAAAAACACCA,cardiac_neuro_cava_random:ALT_FTO|ENSG00000140...,15;270M;NM:i:0;MD:Z:270;6,9/10
3,AAAAAAAAAACCTCG,cardiac_neuro_cava_random:REF_FKRP|ENSG0000018...,15;270M;NM:i:0;MD:Z:270;6,7/7
4,AAAAAAAAAAGCTGG,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,7/8
...,...,...,...,...
6305461,TTTTTTTTTTGACCG,cardiac_neuro_cava_random:ALT_CPS1|ENSG0000002...,15;270M;NM:i:0;MD:Z:270;6,32/33
6305462,TTTTTTTTTTGACGA,cardiac_neuro_cava_random:ALT_ACTN2|ENSG000000...,15;270M;NM:i:0;MD:Z:270;6,11/11
6305463,TTTTTTTTTTGCACA,cardiac_neuro_cava_random:ALT_CARD11|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,22/26
6305464,TTTTTTTTTTGCTAA,cardiac_neuro_cava_random:REF_NR4A2|ENSG000001...,15;270M;NM:i:0;MD:Z:270;6,6/6
6305465,TTTTTTTTTTGTCCC,cardiac_neuro_cava_random:ALT_NBN|ENSG00000104...,15;270M;NM:i:0;MD:Z:270;6,3/3

In [47]:
# count for each ID how many barcodes are associated
barcode_count = sequence_barcode_association.groupby("ID").count()
barcode_count = barcode_count.reset_index()
barcode_count = barcode_count[['ID', 'barcode']]
barcode_count

                                                      ID  barcode
0      C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...      150
1      C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...      132
2      C_SLEA:SLEA_hg18:chr2:210861483-210861650|10:V...       88
3      C_SLEA:SLEA_hg18:chr2:210861483-210861650|10:V...      122
4      C_SLEA:SLEA_hg18:chr2:210861483-210861650|10:V...       72
...                                                  ...      ...
74999  cardiac_neuro_cava_random:ZNF462|ENSG000001481...       48
75000  cardiac_neuro_cava_random:ZNF462|ENSG000001481...      109
75001  cardiac_neuro_cava_random:ZNF462|ENSG000001481...       36
75002  cardiac_neuro_cava_random:ZNF462|ENSG000001481...       57
75003  cardiac_neuro_cava_random:ZNF462|ENSG000001481...      151

[75004 rows x 2 columns]

In [48]:

# check if all ids have 10 barcodes
bc_number_threshold = 10
barcode_count['label'] = barcode_count['ID'].apply(lambda x: x.split(":")[0])
sequences_below_10_barcodes = barcode_count[barcode_count['barcode'] < bc_number_threshold]
print(barcode_count[barcode_count['barcode'] >= bc_number_threshold].shape[0])
print(f"IDs with less than {bc_number_threshold} barcodes:", len(sequences_below_10_barcodes))
# print(sequences_below_10_barcodes) # 4380 rows with less than 10 barcodes; 731 with less than 2 barcodes

# # check their distribution
print(sequences_below_10_barcodes['label'].value_counts())

# cardiac_below_10_bcs = sequences_below_10_barcodes[sequences_below_10_barcodes['label'] == "cardiac_neuro_cava_random"]
# # check how many variants and how many regions
# cardiac_below_10_bcs['sequence_type'] = cardiac_below_10_bcs['ID'].apply(lambda x: "variant" if ":REF_" in x or ":ALT_" in x else "region")
# cardiac_below_10_bcs['sequence_type'].value_counts()
# cardiac_below_10_bcs['chrom_pos_ref_alt'] = cardiac_below_10_bcs['ID'].apply(lambda x: x.split("|")[-1])
# cardiac_below_10_bcs

70624
IDs with less than 10 barcodes: 4380
label
cardiac_neuro_cava_random      3790
MK                              157
C_positive_heart_AB             145
C_negative_neuron_NP             49
C_negative_heart_MK              32
C_positive_neuron_CD             31
C_positive_neuron_NP             26
GC_Selvarajan                    25
GC_Kircher                       23
C_negative_neuron_MK             22
C_positive_heart_MK              22
C_SLEA                           19
GC_Vista                         13
GC_Mendelian_variants             8
C_positive_heart_CAD              4
GC_GABA_Chengyu                   3
GC_DNase_positive                 3
GC_Liang                          2
C_positive_neuron_MK              2
GC_DNase_positive_shuffeled       2
GC_Glut_Chengyu                   1
GC_Mohlke                         1
Name: count, dtype: int64

In [ ]:
### compare mpralm log2fc and p-values