### Notebook to show and comment the way to the unified design file / headers
list of all the things to remember on the way to the unifyied design file
- Neuron_MK: chrom start end modification
- Where are the duplicated sequences in the design
- Which sequences are reverse complements of each other?

In [1]:
import pandas as pd
import sys
import yaml

# config
config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/global80K_config.yaml"
with open(config_path) as conf:
    config = yaml.load(conf, Loader=yaml.FullLoader)
    conf.close()

sys.path.append('../../00_helpful_functions')
import helpful_functions as hf
# from importlib import reload
# reload helpful_functions

### Load the final design fasta file and get the headers and sequences 
- Findings:
  - same number of tested sequences
    - Are all tested sequences the same? yes
    - Are all headers the same? no 1717 not 
    - Change of , (first version) to ~ (final version)
- Open questions at hand:
  - Which sequences are in the first fasta and not in the final version? (not tested but maybe controls)
  - Why are these sequences not in the final version? (not tested but maybe controls)
  - Are there sequences which are in the final design but not in the first version? (not tested but maybe controls)
- Problems:
  - We have really long headers in the final design file: How can we shorten them? 
    - If we shorten them we need to do so as well in the variant map file 
  - We have between the final file and the first version 
    - Sequences with * ; >
    - Sequences with ~ ; ,

In [2]:
first_fasta_df = hf.fasta_to_dataframe(config['files']['final_design']['first_design_fasta'])
first_fasta_df

,header,sequence
0,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTAAGAATACAAGTAACTGATGAATGAAGGGGG...
1,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTTTGGGTATGCTGCCCCCCAGCTGGCGGGGCA...
2,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTACGAGCAAGGGAATGAGAGAGAGTGGGTTAG...
3,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCGTGGACACGCGTGATTGACCCTTTAACTGT...
4,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCCGGAGAGTCTCAGCTCCCGCAGCCCTAACA...
...,...,...
80801,MK:tile_2240|chr1-116244322+116244591|scramble...,AGGACCGGATCAACTCTTAATCAAATAACCCATTAATTCTATATAT...
80802,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,AGGACCGGATCAACTCATCGGCCCTGGTGAAGCGTCCGTCCAGACG...
80803,MK:tile_18415|chr17-71181691+71181960|scramble...,AGGACCGGATCAACTTAAATATTCAGCGATACATTCCTATTCTTTT...
80804,MK:tile_14356|chr15-67031618+67031887|scramble...,AGGACCGGATCAACTTGAAGCCCCTGATTCTGTTAGAATAAGGTTA...
80805,MK:tile_22033|chr2-71506006+71506275|scramble_...,AGGACCGGATCAACTGGGGGAGAAATTGGACAGGCACGCCTTGCTC...

In [3]:
design_fasta = hf.fasta_to_dataframe(config['files']['final_design']['design_fasta'])
design_fasta

,header,sequence
0,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTAAGAATACAAGTAACTGATGAATGAAGGGGG...
1,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTTTGGGTATGCTGCCCCCCAGCTGGCGGGGCA...
2,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTACGAGCAAGGGAATGAGAGAGAGTGGGTTAG...
3,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCGTGGACACGCGTGATTGACCCTTTAACTGT...
4,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCCGGAGAGTCTCAGCTCCCGCAGCCCTAACA...
...,...,...
80210,MK:tile_2240|chr1-116244322+116244591|scramble...,AGGACCGGATCAACTCTTAATCAAATAACCCATTAATTCTATATAT...
80211,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,AGGACCGGATCAACTCATCGGCCCTGGTGAAGCGTCCGTCCAGACG...
80212,MK:tile_18415|chr17-71181691+71181960|scramble...,AGGACCGGATCAACTTAAATATTCAGCGATACATTCCTATTCTTTT...
80213,MK:tile_14356|chr15-67031618+67031887|scramble...,AGGACCGGATCAACTTGAAGCCCCTGATTCTGTTAGAATAAGGTTA...
80214,MK:tile_22033|chr2-71506006+71506275|scramble_...,AGGACCGGATCAACTGGGGGAGAAATTGGACAGGCACGCCTTGCTC...

### Focus on the tested sequences
- finding: 
    - all sequences are the same
    - you need to replace ',', '~' from the first version headers to have same headers again

In [4]:
first_tested_df = first_fasta_df.loc[first_fasta_df['header'].str.startswith('cardiac_neuro_cava_random')]
first_tested_df

,header,sequence
0,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTAAGAATACAAGTAACTGATGAATGAAGGGGG...
1,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTTTGGGTATGCTGCCCCCCAGCTGGCGGGGCA...
2,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTACGAGCAAGGGAATGAGAGAGAGTGGGTTAG...
3,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCGTGGACACGCGTGATTGACCCTTTAACTGT...
4,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCCGGAGAGTCTCAGCTCCCGCAGCCCTAACA...
...,...,...
73935,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTGGAGCTCTGCCTCACCCCACCTGGCCCCAAT...
73936,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTATGTCTGAATTCACCTCCAAATAATGGGAAA...
73937,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTCCTCTGCCCTCCCTGGCTTCTTCCCCTGTCC...
73938,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTCCTCTGCCCTCCCTGGCTTCTTCCCCTGTCC...
73939,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTCCTCTGCCCTCCCTGGCTTCTTCCCCTGTCC...

In [5]:
final_design_tested_df = design_fasta.loc[design_fasta['header'].str.startswith('cardiac_neuro_cava_random')]
final_design_tested_df

,header,sequence
0,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTAAGAATACAAGTAACTGATGAATGAAGGGGG...
1,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTTTGGGTATGCTGCCCCCCAGCTGGCGGGGCA...
2,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTACGAGCAAGGGAATGAGAGAGAGTGGGTTAG...
3,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCGTGGACACGCGTGATTGACCCTTTAACTGT...
4,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AGGACCGGATCAACTCCGGAGAGTCTCAGCTCCCGCAGCCCTAACA...
...,...,...
73935,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTGGAGCTCTGCCTCACCCCACCTGGCCCCAAT...
73936,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTATGTCTGAATTCACCTCCAAATAATGGGAAA...
73937,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTCCTCTGCCCTCCCTGGCTTCTTCCCCTGTCC...
73938,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTCCTCTGCCCTCCCTGGCTTCTTCCCCTGTCC...
73939,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,AGGACCGGATCAACTCCTCTGCCCTCCCTGGCTTCTTCCCCTGTCC...

####  Open Questions:
- Are all tested sequences the same? 
- Are all headers the same?

In [6]:
# check if all sequences between first design and final design are the same
first_tested_df['sequence'].equals(final_design_tested_df['sequence'])

# check if all headers between first design and final design are the same
first_tested_df['header'].equals(final_design_tested_df['header'])

# check which headers which do not need to be in the same order are not the same
# make a set out of the first version headers and the final version headers
first_design_headers_tested = set(first_tested_df['header'].to_list())
final_design_headers_tested = set(final_design_tested_df['header'].to_list())

# check which header are in final design but not in first design these were changed on the way to the final design
len(final_design_headers_tested - first_design_headers_tested) # 1717
changed_tested_headers = final_design_headers_tested - first_design_headers_tested

In [7]:
# get the final design of the changed headers
changed_tested_df = final_design_tested_df.loc[final_design_tested_df['header'].isin(changed_tested_headers)]
print(changed_tested_df.shape)

# change the header column name of the first version tested header df
first_tested_df.columns = ['header_first_design', 'sequence']

# left join of the changed tested headers and the first version to check what are the differences
changed_tested_df.merge(first_tested_df, how='left', on='sequence')['header_first_design'].isna().sum() # no missing
changed_tested_header = changed_tested_df.merge(first_tested_df, how='left', on='sequence')
changed_tested_header.drop(columns='sequence', inplace=True)

# write the file to check the differences
changed_tested_header.to_csv(config['files']['final_design']['changed_tested_headers'], sep='\t', index=False)

(1717, 2)

#### If I change all , to ~ it should be fine

In [8]:
# add another header column but change all , to ~
first_tested_df['matchable_header'] = first_tested_df['header_first_design'].str.replace(',', '~')

# check if everything is equal now
final_design_tested_df.merge(first_tested_df, how='left', on='sequence')['matchable_header'].isna().sum() # no missing

# all headers are the same now
first_tested_df['matchable_header'].equals(final_design_tested_df['header'])

/tmp/ipykernel_1803/3038504988.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_tested_df['matchable_header'] = first_tested_df['header_first_design'].str.replace(',', '~')

True

### Focus on the control sequences
- Numbers: 
  - 6866 first version
  - 6275 final design
- Patterns:
  - _copy<number> in the first version of sequence duplicates
  - some sequences like from MK are within the positive controls but also within the MK 
    - MK:tile_45784|chr9-81112997+81113266|A-T-17
    - C_negative_neuron_MK:tile_45784_chr9_81112997_81113266_A_T_17__0.312337766730427
  - other combinations like negative neuron mk or negative heart or GABA and GLUT from Chengyu 
    - GC_GABA_Chengyu:GABA|chr11:16297402-16297671|+|1.79
    - GC_Glut_Chengyu:Glut|chr11:16297402-16297671|+|1.65
  - overlap between reference and alternative of different control variant groups:
    - GC_Mohlke:ALT_NC000001.11|230158967|C|A|MohlkeHepControls,NC000001.11|230159168|C|T|MohlkeHepControls,NC000001.11|230159329|CTTAAAGTGTTCAGCACTCCCCT|CT|MohlkeHepControls_fwd_tile1-3_NC000001_11_230158967_C_A
    - GC_Selvarajan:ALT_rs4846913|STARR-seq-HepG2_fwd_tile1-1_rs4846913
    - GC_Selvarajan:REF_rs4846913|STARR-seq-HepG2_fwd_tile1-1
    - GC_Mohlke:REF_NC000001.11|230158967|C|A|MohlkeHepControls,NC000001.11|230159168|C|T|MohlkeHepControls,NC000001.11|230159329|CTTAAAGTGTTCAGCACTCCCCT|CT|MohlkeHepControls_fwd_tile1-3
  - mendelian variants are looking weird, because different variants according to the header have the same sequence
    - GC_Mendelian_variants:ALT_chr7:156791472C>T|SHH_chr7:156791459T>C|SHH	
      - AGGACCGGATCAACTGCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTGGACTTCCTACTCACTCTGTGTCTCTTTAAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAAGTCATCCGGTCATAAAATACAGTACAAGGTCACTTTTATGTAAGTTTGCCAAAAGGGACATAAACCAGGACAATTTCAAACTGTGACACAGGATAGAAACATATTAAAAAAATCTTTGTTCCTCCTCTATTGTGCTGTCATGTTGCTCAGCTTTCATTGCGTGAACCGA
    - GC_Mendelian_variants:ALT_chr7:156791472C>G|SHH_chr7:156791459T>C|SHH	
      - AGGACCGGATCAACTGCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTGGACTTCCTACTCACTCTGTGTCTCTTTAAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAAGTCATCCGGTCATAAAATACAGTACAAGGTCACTTTTATGTAAGTTTGCCAAAAGGGACATAAACCAGGACAATTTCAAACTGTGACACAGGATAGAAACATATTAAAAAAATCTTTGTTCCTCCTCTATTGTGCTGTCATGTTGCTCAGCTTTCATTGCGTGAACCGA

In [9]:
final_design_controls_df = design_fasta.loc[~design_fasta['header'].str.startswith('cardiac_neuro_cava_random')]
final_design_controls_df # 6275

,header,sequence
73940,GC_Atrial_fib:rs7795510|CAV1|STARR-seq-AF~rs78...,AGGACCGGATCAACTTCATTTCATTATAATCAAAAAGGATTTTTAA...
73941,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,AGGACCGGATCAACTCAGCTGCCCATGCTGGGACTGTGATTTTTTG...
73942,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGAGCCCTTCTGGGGGCCCTGGCCACTGGCC...
73943,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGGAAAGGCACTGGAAATTGTACTTACTCCA...
73944,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,AGGACCGGATCAACTTTTGCAAAGGTATGGTTGGTGGATGGAGAAA...
...,...,...
80210,MK:tile_2240|chr1-116244322+116244591|scramble...,AGGACCGGATCAACTCTTAATCAAATAACCCATTAATTCTATATAT...
80211,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,AGGACCGGATCAACTCATCGGCCCTGGTGAAGCGTCCGTCCAGACG...
80212,MK:tile_18415|chr17-71181691+71181960|scramble...,AGGACCGGATCAACTTAAATATTCAGCGATACATTCCTATTCTTTT...
80213,MK:tile_14356|chr15-67031618+67031887|scramble...,AGGACCGGATCAACTTGAAGCCCCTGATTCTGTTAGAATAAGGTTA...
80214,MK:tile_22033|chr2-71506006+71506275|scramble_...,AGGACCGGATCAACTGGGGGAGAAATTGGACAGGCACGCCTTGCTC...

In [10]:
first_controls_df = first_fasta_df.loc[~first_fasta_df['header'].str.startswith('cardiac_neuro_cava_random')]
first_controls_df # 6866

,header,sequence
73940,"GC_Atrial_fib:rs7795510|CAV1|STARR-seq-AF,rs78...",AGGACCGGATCAACTTCATTTCATTATAATCAAAAAGGATTTTTAA...
73941,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,AGGACCGGATCAACTCAGCTGCCCATGCTGGGACTGTGATTTTTTG...
73942,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGAGCCCTTCTGGGGGCCCTGGCCACTGGCC...
73943,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGGAAAGGCACTGGAAATTGTACTTACTCCA...
73944,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,AGGACCGGATCAACTTTTGCAAAGGTATGGTTGGTGGATGGAGAAA...
...,...,...
80801,MK:tile_2240|chr1-116244322+116244591|scramble...,AGGACCGGATCAACTCTTAATCAAATAACCCATTAATTCTATATAT...
80802,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,AGGACCGGATCAACTCATCGGCCCTGGTGAAGCGTCCGTCCAGACG...
80803,MK:tile_18415|chr17-71181691+71181960|scramble...,AGGACCGGATCAACTTAAATATTCAGCGATACATTCCTATTCTTTT...
80804,MK:tile_14356|chr15-67031618+67031887|scramble...,AGGACCGGATCAACTTGAAGCCCCTGATTCTGTTAGAATAAGGTTA...
80805,MK:tile_22033|chr2-71506006+71506275|scramble_...,AGGACCGGATCAACTGGGGGAGAAATTGGACAGGCACGCCTTGCTC...

#### How many control sequences are unique in the first version?
- 6275 final design and 6275 in the first version
- 591 duplicates
- 484 have _copy<number> suffix
- some are within different control groups

In [11]:
final_design_controls_df['sequence'].nunique()
first_controls_df['sequence'].nunique()

6275

##### Investigate the sequences which are duplicated in the first version
- found variant sequences

In [12]:
# # duplicated sequences in the first version
# duplicates_in_first_version = first_controls_df[first_controls_df.duplicated(subset='sequence', keep='first')].sort_values('sequence')
# # print(duplicates_in_first_version['header'].str.contains('_copy').sum()) # 484
# print('Number of duplicates', duplicates_in_first_version.shape[0])

duplicates_in_first_version = first_controls_df[first_controls_df.duplicated(subset='sequence', keep=False)].sort_values('sequence')
print('Number of duplicates', duplicates_in_first_version.shape[0])
duplicates_in_first_version.to_csv(config['files']['final_design']['duplicates_in_first_version'], sep='\t', index=False)

Number of duplicates 935

In [13]:
# found _copy as suffix for copies
# how many have the pattern _copy in the header:
duplicates_in_first_version['header'].str.contains('_copy').sum() # 484

# print the duplicates which do not have _copy in the header
no_copy_duplicates_first_version = duplicates_in_first_version[~duplicates_in_first_version['header'].str.contains('_copy')]
no_copy_duplicates_first_version[no_copy_duplicates_first_version.duplicated(subset='sequence', keep=False)].sort_values('sequence').to_csv(config['files']['final_design']['duplicates_in_first_version_no_copy'], sep='\t', index=False)

#### Help from Pia to clean the duplicates with focus on the variants (not mixing ref and alt up because of the variant map this would lead to losing the variant)
- I thought there is a problem in the final design with the variants and I can do this with clumpsify but the more robust way is to use the variant map:
  - find for the header the fitting alternative ID
    - Split the controls and get all variants 
    - Split controls into ref and alt
    - for each alt there needs to be an entry in the variant map 
    - for each reference associated to the alternative look into the set of references if it is in there

In [14]:
def ignore_this_control_header(header):
    """
    Checks if the given header should be ignored
    """
    label = hf.get_label(header)
    # if MK => not interesting
    if label == "MK":
        return True
    return False
def is_control_variant_reference(header):
    """Returns if a control header is a variant of a reference"""
    if (not ignore_this_control_header):
        return False

    # currently best pattern for variants (REF_ might be not strict enough)
    if ("REF_" in header) or is_control_alternative(header):
        return True
    return False


def is_control_reference(header):
    """Returns if a control header is a control reference sequence. Some control groups might be ignored"""
    if (not ignore_this_control_header):
        return False
    # check reference pattern
    if "REF_" in header:
        return True
    return False


def is_control_alternative(header):
    """Returns if a control header is a control alternative sequence. Some control groups might be ignored"""
    if (not ignore_this_control_header):
        return False
    # check alternative pattern
    if "ALT_" in header:
        return True
    return False

In [37]:
# find for the header the fitting alternative ID
# Split the controls and get all variants
# final_design_controls_df['header'].to_csv('final_controls_find_variant_pattern.csv', sep="\t", index=False)

# make headers matchable
final_design_controls_df['matchable_header'] = final_design_controls_df['header'].str.replace('~',',')
final_design_controls_df['matchable_header'] = final_design_controls_df['matchable_header'].str.replace('*','>')

only_control_variants = final_design_controls_df.loc[final_design_controls_df['header'].apply(is_control_variant_reference)]
# only_control_variants # 967

# Split controls into ref and alt
only_control_alt = only_control_variants.loc[only_control_variants['header'].apply(is_control_alternative)]
only_control_alt # 655 => 967 - 655 = 312 (references)

# all reference headers in the control group
only_control_ref = only_control_variants.loc[only_control_variants['header'].apply(is_control_reference)]
only_control_ref # 312

/tmp/ipykernel_1803/1025084544.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_design_controls_df['matchable_header'] = final_design_controls_df['header'].str.replace('~',',')
/tmp/ipykernel_1803/1025084544.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  final_design_controls_df['matchable_header'] = final_design_controls_df['matchable_header'].str.replace('*','>')
/tmp/ipykernel_1803/1025084544.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_design_controls_df['matchable_header'] = final_design_controls_df['matchable_header'].str.replace('*','>')

,header,sequence,matchable_header
73941,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,AGGACCGGATCAACTCAGCTGCCCATGCTGGGACTGTGATTTTTTG...,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...
73942,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGAGCCCTTCTGGGGGCCCTGGCCACTGGCC...,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...
73943,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGGAAAGGCACTGGAAATTGTACTTACTCCA...,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...
73944,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,AGGACCGGATCAACTTTTGCAAAGGTATGGTTGGTGGATGGAGAAA...,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...
73945,GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...,AGGACCGGATCAACTACAAATTGCTAACTGAGTGTAGAATAACAGG...,GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...
...,...,...,...
74854,C_positive_heart_CAD:REF_rs7865618,AGGACCGGATCAACTTATTGATAACAGGGGATGGATTCTTGTGGAC...,C_positive_heart_CAD:REF_rs7865618
74855,C_positive_heart_CAD:REF_rs4977757,AGGACCGGATCAACTCTGATGGGCTTCCCTTTGTGGGTAACCCGAC...,C_positive_heart_CAD:REF_rs4977757
74856,C_positive_heart_CAD:REF_rs1537373,AGGACCGGATCAACTAGAAAACCATACCCACTTTCCCACATATCCC...,C_positive_heart_CAD:REF_rs1537373
74857,C_positive_heart_CAD:REF_rs10811656,AGGACCGGATCAACTAAATTAAAAGCTTCTAAACTAACAAACAGCC...,C_positive_heart_CAD:REF_rs10811656
74858,C_positive_heart_CAD:REF_rs507666,AGGACCGGATCAACTATTAAGACAAAAAAGGGAAAACAAAGACCAC...,C_positive_heart_CAD:REF_rs507666

In [16]:
# read the variant region map
variant_region_map = pd.read_csv('/home/kisa/coding/80K_MPRA/design_data/design_info/variant_region_map.tsv.gz', sep="\t")
control_variant_region_map = variant_region_map.loc[~variant_region_map['ALT_ID'].str.startswith('cardiac_neuro_cava_random')]
print(control_variant_region_map.shape[0])
print(control_variant_region_map.nunique())

670
Variant    420
Region     311
REF_ID     311
ALT_ID     670
dtype: int64

,header,sequence,REF_ID,ALT_ID
0,GC_Atrial_fib:ALT_rs74541936|KCNN3|STARR-seq-A...,AGGACCGGATCAACTCAGCTGCCCATGCTGGGACTGTGATTTTTTG...,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs74541936|KCNN3|STARR-seq-A...
1,GC_Atrial_fib:ALT_rs34292822|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGAGCCCTTCTGGGGGCCCTGGCCACTGGCC...,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs34292822|KCNN3|STARR-seq-A...
2,GC_Atrial_fib:ALT_rs12754189|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGGAAAGGCACTGGAAATTGTACTTACTCCA...,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs12754189|KCNN3|STARR-seq-A...
3,GC_Atrial_fib:ALT_rs36088503|KCNN3|STARR-seq-A...,AGGACCGGATCAACTTTTGCAAAGGTATGGTTGGTGGATGGAGAAA...,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs36088503|KCNN3|STARR-seq-A...
4,GC_Atrial_fib:ALT_rs1218584|KCNN3|STARR-seq-AF...,AGGACCGGATCAACTACAAATTGCTAACTGAGTGTAGAATAACAGG...,NaN,NaN
...,...,...,...,...
650,C_positive_heart_CAD:ALT_rs7865618_rs7865618,AGGACCGGATCAACTTATTGATAACAGGGGATGGATTCTTGTGGAC...,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618
651,C_positive_heart_CAD:ALT_rs4977757_rs4977757,AGGACCGGATCAACTCTGATGGGCTTCCCTTTGTGGGTAACCCGAC...,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757
652,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGGACCGGATCAACTAGAAAACCATACCCACTTTCCCACATATCCC...,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373
653,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AGGACCGGATCAACTAAATTAAAAGCTTCTAAACTAACAAACAGCC...,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656
654,C_positive_heart_CAD:ALT_rs507666_rs507666,AGGACCGGATCAACTATTAAGACAAAAAAGGGAAAACAAAGACCAC...,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666

In [18]:
control_variant_region_map.nunique()
control_variant_region_map.shape[0]

670

In [44]:




# check if the alternative controls file has all alternative sequences or which are missing
control_alt_final = control_variant_region_map[['REF_ID', 'ALT_ID']].merge(only_control_alt, left_on='ALT_ID', right_on='matchable_header', how='left')
control_alt_final

matchabel_control_alt_final = control_alt_final.loc[~control_alt_final['header'].isna()]
matchabel_control_alt_final # 653


# investigate if all references associated to an alternative sequence are also the set of control reference sequences
# get all references associated to an alternative sequence
alt_associated_references = set(matchabel_control_alt_final['REF_ID'].to_list())

# Are all of these in the final design (in only_control_ref['matchable_header']?
all_references_in_final_design = set(only_control_ref['matchable_header'].to_list())

alt_associated_references - all_references_in_final_design # () => yes all references are in the final design

# check if all references in the final design are associated to an alternative sequence
all_references_in_final_design - alt_associated_references # () => yes all references are associated to an alternative sequence

{'GC_Mendelian_variants:REF_chr8:11703860G>T|GATA4_headerDuplicate2_2_headerDuplicate1_2',
 'GC_Mendelian_variants:REF_chr8:11703890AG>A|GATA4_headerDuplicate2_2_headerDuplicate1_2',
 'GC_Mohlke:REF_NC000001.11|230158967|C|A|MohlkeHepControls,NC000001.11|230159168|C|T|MohlkeHepControls,NC000001.11|230159329|CTTAAAGTGTTCAGCACTCCCCT|CT|MohlkeHepControls_fwd_tile3-3_headerDuplicate2_2_headerDuplicate1_2',
 'GC_Selvarajan:REF_rs216222|STARR-seq-HepG2_fwd_tile1-1',
 'GC_Selvarajan:REF_rs754064|STARR-seq-HepG2_fwd_tile1-1'}

In [22]:
# check if the final design controls file has all alternative sequences or which are missing
all_alt_controls_final = control_variant_region_map[['REF_ID', 'ALT_ID']].merge(final_design_controls_df, left_on='ALT_ID', right_on='matchable_header', how='left')
all_alt_controls_final

matchabel_all_alt_controls_final = all_alt_controls_final.loc[~all_alt_controls_final['header'].isna()]
# problem we find no matches for everything without 205, with ~ => , (492)  with * => > (653) expected 670


# check if all

##### Checking the missing alternative sequences (not all alterantive sequences are in the final design)
- are all of these duplicated sequences? - yes

In [ ]:
# # for each alt there needs to be an entry in the variant map
only_control_alt.merge(control_variant_region_map[['REF_ID', 'ALT_ID']], left_on='header', right_on='ALT_ID', how='left')
# Problem: 655 is the number of alternatives I have according to the final design, but I have 670 unique alternatives in the variant region map (version one?)

In [34]:
# investigate the missing alternative sequences
matchable_alt_controls = set(matchabel_all_alt_controls_final['ALT_ID'].to_list())
# print(len(matchable_alt_controls)) # 653

all_control_variants = set(control_variant_region_map['ALT_ID'].to_list())
# print(len(all_control_variants)) # 670

missing_control_variants = all_control_variants - matchable_alt_controls
# print(len(missing_control_variants)) # 17

missing_control_variants

# are all these missing? check with the duplicates table
duplicates_in_first_version = pd.read_csv(config['files']['final_design']['duplicates_in_first_version_no_copy'], sep='\t')
duplicates_in_first_version

matchable_duplicates = duplicates_in_first_version.loc[duplicates_in_first_version['header'].isin(missing_control_variants)]
print(f'Number of duplicates: {matchable_duplicates.shape[0]} (expected {len(missing_control_variants)}) => only alternative sequences missing which were duplicates') # 17
# we only lost alt with duplicates in the variant region map

Number of duplicates: 17 (expected 17)

In [35]:
# for each reference associated to the alternative look into the set of references if it is in there
# get all reference headers in final design
all_ref_controls_final = control_variant_region_map[['REF_ID', 'ALT_ID']].merge(final_design_controls_df, left_on='REF_ID', right_on='matchable_header', how='left')
matchabel_ref_controls_final = all_ref_controls_final.loc[~all_ref_controls_final['header'].isna()]
matchabel_ref_controls_final

,REF_ID,ALT_ID,header,sequence,matchable_header
0,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs74541936|KCNN3|STARR-seq-A...,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,AGGACCGGATCAACTCAGCTGCCCATGCTGGGACTGTGATTTTTTG...,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...
1,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs34292822|KCNN3|STARR-seq-A...,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGAGCCCTTCTGGGGGCCCTGGCCACTGGCC...,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...
2,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs12754189|KCNN3|STARR-seq-A...,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,AGGACCGGATCAACTAGGAAAGGCACTGGAAATTGTACTTACTCCA...,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...
3,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs36088503|KCNN3|STARR-seq-A...,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,AGGACCGGATCAACTTTTGCAAAGGTATGGTTGGTGGATGGAGAAA...,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...
4,GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...,GC_Atrial_fib:ALT_rs1218584|KCNN3|STARR-seq-AF...,GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...,AGGACCGGATCAACTACAAATTGCTAACTGAGTGTAGAATAACAGG...,GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...
...,...,...,...,...,...
665,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,AGGACCGGATCAACTTATTGATAACAGGGGATGGATTCTTGTGGAC...,C_positive_heart_CAD:REF_rs7865618
666,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,AGGACCGGATCAACTCTGATGGGCTTCCCTTTGTGGGTAACCCGAC...,C_positive_heart_CAD:REF_rs4977757
667,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,AGGACCGGATCAACTAGAAAACCATACCCACTTTCCCACATATCCC...,C_positive_heart_CAD:REF_rs1537373
668,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,AGGACCGGATCAACTAAATTAAAAGCTTCTAAACTAACAAACAGCC...,C_positive_heart_CAD:REF_rs10811656
669,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,AGGACCGGATCAACTATTAAGACAAAAAAGGGAAAACAAAGACCAC...,C_positive_heart_CAD:REF_rs507666

##### Code for clumpify: (Unfinished)
- remove duplicated variants the smart way
- mark all duplicates as duplicated 
- awk sort by header and only get ref and alt of the same variant (not in this code snippets)

- clumpify comes from BBtools requries fasta file input => create fasta output
- run clumpify as mentioned here 

- example:  
  - in design: 
    - GC_Selvarajan:ALT_rs603424|STARR-seq-HepG2_fwd_tile1-1_rs603424	
    - GC_Selvarajan:REF_rs603424|STARR-seq-HepG2_fwd_tile1-1	
  - not in design file: 
    - GC_Mohlke:ALT_NC000010.11|100315721|G|A|MohlkeNonHepControl_fwd_tile1-1_NC000010_11_100315721_G_A	
    - GC_Mohlke:REF_NC000010.11|100315721|G|A|MohlkeNonHepControl_fwd_tile1-1	
```
zcat {input} | awk 'NR%4==1||NR%4==2 {{if (NR%4==1) {{if ($3 == "duplicate")
{{$1 = prev; $3=""}}; prev = $1}} print $0 }}' | bgzip -c > {output}
```

In [79]:
# # create fasta output
# no_copy_duplicates_sorted = no_copy_duplicates_first_version[no_copy_duplicates_first_version.duplicated(subset='sequence', keep=False)].sort_values('sequence')
# hf.write_fasta(no_copy_duplicates_sorted, config['files']['final_design']['duplicates_in_first_version_no_copy_fasta'], header=['header', 'sequence'])

True

In [81]:
# ! clumpify.sh in=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy.fa out=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy_clumpify.fa markduplicates

java -ea -Xmx1319m -Xms1319m -cp /home/kisa/miniforge3/envs/mobil/opt/bbmap-39.06-1/current/ clump.Clumpify in=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy.fa out=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy_clumpify.fa markduplicates
Executing clump.Clumpify [in=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy.fa, out=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy_clumpify.fa, markduplicates]
Version 39.06

Read Estimate:          765
Memory Estimate:        0 MB
Memory Available:       1043 MB
Set groups to 1
Executing clump.KmerSort1 [in1=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy.fa, in2=, out1=/home/kisa/coding/80K_MPRA/metadata_info/design_file/duplicates_controls_first_version_no_copy_clumpify.fa, out2=, groups=1, ecco=false, rename=false, shortname=f, unpair=false, repair=false, namesort=false, ow=true, markduplicates]

Making comparator.
Made a comparator with k=31, seed=1, border=1, hashes=4
Starting cris 0.
Fetching reads.
Making fetch threads.
Starting threads.
Waiting for threads.
Fetch time: 	0.017 seconds.
Closing input stream.
Combining thread output.
Combine time: 	0.000 seconds.
Sorting.
Sort time: 	0.000 seconds.
Making clumps.
Clump time: 	0.000 seconds.
Deduping.
Dedupe time: 	0.005 seconds.
Writing.
Waiting for writing to complete.
Write time: 	0.004 seconds.
Done!
Time:                         	0.111 seconds.
Reads Processed:           209 	1.89k reads/sec
Bases Processed:         62700 	0.57m bases/sec

Reads In:                  209
Clumps Formed:              68
Duplicates Found:          120	57.416%
Reads Out:                 209
Bases Out:               62700
Total time: 	0.192 seconds.