### Get the general control regions for Jessica + rename the Kircher controls + Get the regions for MK

In [2]:
import pandas as pd
from importlib import reload

import ast

import sys

sys.path.append('../helpful_functions/')
import helpful_functions as hf
reload(hf)

In [3]:
# Function to safely evaluate string representations of lists
def safe_eval(x):
    if pd.isna(x):
        return None
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return x

# column names
col_name = 'name'
col_header = 'name'
col_sequence = 'sequence'
col_category = 'category'
col_class = 'class'
col_source = 'source'
col_ref = 'ref'
col_chr = 'chr'
col_start = 'start'
col_end = 'end'
col_strand = 'strand'
col_variant_class = 'variant_class'
col_variant_pos = 'variant_pos'
col_SPDI = 'SPDI'
col_allele = 'allele'
col_info = 'info'


list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

In [4]:
metadata_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MPRA_80215_updated_dnase_sequences.metadata.tsv.gz"
metadata_df = pd.read_csv(metadata_path, sep='\t', compression='gzip', low_memory=False)

# use safe eval on list
# Apply the safe_eval function to the specified columns
for col in list_columns:
    metadata_df[col] = metadata_df[col].apply(safe_eval)

In [5]:
metadata_df

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info
0,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,element active control,Michael Kosicki,GRCh38,chr8,10365155.0,10365425.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, indel, indel, i...","[20, 252, 20, 252, 36, 36, 17, 249, 33]",None,"[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN
1,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,element active control,Michael Kosicki,GRCh38,chr20,20492858.0,20493129.0,+,[SNV],[40],None,[ref],NaN
2,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,element active control,Michael Kosicki,GRCh38,chr22,42282877.0,42283148.0,+,[SNV],[172],None,[ref],NaN
3,MK:tile_38401|chr7-1226231+1226500|reference,AAAACTATTAGACGACAGGCGGATGTGCTACTAAAACTCTTGGTTA...,variant,element active control,Michael Kosicki,GRCh38,chr7,1226230.0,1226500.0,+,"[SNV, SNV, SNV, SNV, indel, indel]","[84, 84, 248, 248, 245, 81]",None,"[ref, ref, ref, ref, ref, ref]",NaN
4,MK:tile_47638|chr16-52435608+52435878|reference,AAAAGCCACCCCAGCTCTCCACTTTCCCATCCGATTCTAGTAGGTC...,variant,element active control,Michael Kosicki,GRCh38,chr16,52435607.0,52435878.0,+,[SNV],[0],None,[ref],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80191,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element active control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN
80192,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element active control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN
80193,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element active control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN
80194,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element active control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN
80195,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element active control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN

In [7]:
metadata_df['label'] = metadata_df[col_name].apply(hf.get_label)

In [8]:
metadata_df['label'].value_counts()

label
cardiac_neuro_cava_random           73940
MK                                   2397
C_positive_heart_AB                   909
GC_Selvarajan                         358
GC_Vista                              256
C_negative_heart_MK                   243
C_negative_neuron_MK                  222
C_negative_neuron_NP                  217
GC_Mendelian_variants                 209
GC_Kircher                            203
C_SLEA                                200
GC_Cort_Chengyu                       185
C_positive_heart_CAD                   99
C_positive_neuron_NP                   99
C_positive_heart_MK                    97
C_positive_neuron_MK                   96
C_positive_neuron_CD                   94
GC_Glut_Chengyu                        83
GC_Atrial_fib                          45
GC_GABA_Chengyu                        42
GC_DNase_positive                      41
GC_DNase_positive_shuffled             41
GC_Mohlke                              38
GC_Liang                               16
GC_DNase_negative_blood                15
GC_DNase_negative_blood_shuffled       15
GC_DNase_negative_brain_shuffled       15
GC_DNase_negative_brain                15
GC_Hon                                  6
Name: count, dtype: int64

In [9]:
general_control_metadata = metadata_df.loc[metadata_df[col_name].str.startswith('GC_')].copy()

In [10]:
general_control_metadata[col_start] = general_control_metadata[col_start].astype(int)
general_control_metadata[col_end] = general_control_metadata[col_end].astype(int)

In [11]:
general_control_metadata

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
2397,GC_Kircher:REF_SORT1_chr1:109274659-109274929_...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659,109274929,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[135, 177, 181, 186, 187, 193, 198, 201, 206, ...","[NC_000001.11:109274794:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
2398,GC_Kircher:REF_SORT1_chr1:109274771-109275041_...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771,109275041,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[65, 69, 74, 75, 81, 86, 89, 94, 98, 113, 114,...","[NC_000001.11:109274836:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
2399,GC_Kircher:REF_SORT1_chr1:109274882-109275152_...,CAGTCATGTGTTAAGTTGCGCTTCTTTGCTGTGATGTGGGTGGGGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274882,109275152,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 28, 30, 35, 40, 41, 42, 43, 44, 45, 46, 4...","[NC_000001.11:109274908:T:G, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
2400,GC_Kircher:REF_SORT1_chr1:109274993-109275263_...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 27, 28, 29, 32, 33, 34, 43, 45, 46, 47, 4...","[NC_000001.11:109275019:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
2401,GC_Kircher:REF_SORT1_chr1:109275105-109275375_...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,"[SNV, SNV, SNV, SNV]","[62, 66, 74, 135]","[NC_000001.11:109275167:C:T, NC_000001.11:1092...","[ref, ref, ref, ref]",NaN,GC_Kircher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80191,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element active control,NaN,GRCh38,chr12,44940898,44941168,-,None,None,None,None,NaN,GC_Glut_Chengyu
80192,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element active control,NaN,GRCh38,chr2,212699380,212699650,+,None,None,None,None,NaN,GC_Glut_Chengyu
80193,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element active control,NaN,GRCh38,chr10,26798828,26799098,-,None,None,None,None,NaN,GC_Glut_Chengyu
80194,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element active control,NaN,GRCh38,chr7,31260963,31261233,+,None,None,None,None,NaN,GC_Glut_Chengyu
80195,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element active control,NaN,GRCh38,chr12,44688247,44688517,-,None,None,None,None,NaN,GC_Glut_Chengyu

In [12]:
general_control_metadata[col_start].isna().sum()
general_control_metadata[col_end].isna().sum()

0

In [13]:
general_control_metadata['label'].value_counts()

label
GC_Selvarajan                       358
GC_Vista                            256
GC_Mendelian_variants               209
GC_Kircher                          203
GC_Cort_Chengyu                     185
GC_Glut_Chengyu                      83
GC_Atrial_fib                        45
GC_GABA_Chengyu                      42
GC_DNase_positive                    41
GC_DNase_positive_shuffled           41
GC_Mohlke                            38
GC_Liang                             16
GC_DNase_negative_brain_shuffled     15
GC_DNase_negative_blood_shuffled     15
GC_DNase_negative_brain              15
GC_DNase_negative_blood              15
GC_Hon                                6
Name: count, dtype: int64

In [167]:
general_control_metadata_dnase = general_control_metadata.loc[general_control_metadata["label"].str.contains("DNase_")].copy()

# remove tailing (.) of the headers => problems with pickard and not useful
def remove_tailing_brackets_of_dnase_headers(name):
    return name.split("(.)")[0]

general_control_metadata_dnase["no_tailing_brackets_name"] = general_control_metadata_dnase["name"].apply(remove_tailing_brackets_of_dnase_headers)

In [178]:
# # checked if the new sequences are already within this table
# general_control_metadata_dnase["name"].to_list()
# general_control_metadata_dnase["sequence"].to_list()
# # general_control_metadata_dnase["label"].value_counts()

In [ ]:
general_control_metadata_dnase

In [168]:
general_control_metadata_dnase_no_shuffled = general_control_metadata_dnase.loc[~general_control_metadata_dnase["label"].str.contains("shuff")]

In [169]:
general_control_metadata_dnase_no_shuffled["label"].value_counts()

label
GC_DNase_positive          41
GC_DNase_negative_brain    15
GC_DNase_negative_blood    15
Name: count, dtype: int64

Write the dnase controls as bed file to get the respective sequences on hg38 (bedtools getfasta)
- use the script for the shuffling => from bed to shuffled sequences

In [16]:
# general_control_metadata_dnase[[col_chr, col_start, col_end, col_name]].to_csv("80k_hg38_dnase_controls.bed", sep="\t", index=False, header=None)
# general_control_metadata_dnase_no_shuffled[[col_chr, col_start, col_end, col_name]].to_csv("80k_hg38_dnase_controls_no_shuffled.bed", sep="\t", index=False, header=None)
# "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls.bed"
# "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls_no_shuffled.bed"

In [17]:
# bedtools getfasta -fi /home/kisa/coding/80K_MPRA/reference_genome_match/hg38.fa -bed /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls.bed -fo /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls.bed -nameOnly
general_dnase_control_sequences = hf.fasta_to_dataframe(fasta_file='/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls.fa', columns=["no_tailing_brackets_name", "hg38_sequence"])
general_dnase_control_sequences
general_dnase_control_sequences["hg38_sequence"] = general_dnase_control_sequences["hg38_sequence"].str.upper()

# get label
general_dnase_control_sequences["label"] = general_dnase_control_sequences["no_tailing_brackets_name"].apply(hf.get_label)
general_dnase_control_sequences["label"].value_counts()

label
GC_DNase_positive_shuffeled          55
GC_DNase_positive                    41
GC_DNase_negative_blood_shuffeled    19
GC_DNase_negative_brain_shuffeled    16
GC_DNase_negative_brain              15
GC_DNase_negative_blood              15
Name: count, dtype: int64

In [18]:
general_control_metadata_dnase_no_shuffled

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label,no_tailing_brackets_name
1487,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CTGTGGTTAGCGGCAAATGTTGCAGAAGGTTTTGGGACAGAGGTGG...,element,element inactive control,NaN,GRCh37,chr1,4708882,4709152,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain,GC_DNase_negative_brain:chr1:4768943-4769212_a...
1488,GC_DNase_negative_brain:chr10:27823303-2782357...,TAAGATTGTTTAGAATTGCATTTTGCTATTGGTTAGATCAAAGTGT...,element,element inactive control,NaN,GRCh37,chr10,27534373,27534643,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain,GC_DNase_negative_brain:chr10:27823303-2782357...
1489,GC_DNase_negative_brain:chr11:75379056-7537932...,ACCTGCACATCATACAACAGTCAAAAATCATCAGTGAGCCAGGAAC...,element,element inactive control,NaN,GRCh37,chr11,75668010,75668280,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain,GC_DNase_negative_brain:chr11:75379056-7537932...
1490,GC_DNase_negative_brain:chr13:35297121-3529739...,TTTACATGTGTTCATTTGTATGTATATGTAACTCAATACAATTTTA...,element,element inactive control,NaN,GRCh37,chr13,34722983,34723253,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain,GC_DNase_negative_brain:chr13:35297121-3529739...
1491,GC_DNase_negative_brain:chr13:66919360-6691962...,TCCCCTTGGCATCTGAAGCAAATATAACTTCTTTAACATTCATTCA...,element,element inactive control,NaN,GRCh37,chr13,66345227,66345497,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain,GC_DNase_negative_brain:chr13:66919360-6691962...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76879,GC_DNase_positive:chr7:61079125-61079394_activ...,ATTTGGTAATTCCTGGACTTTCTCTTTTCAAACCCAGTACAGTTTG...,element,element inactive control,NaN,GRCh37,chr7,61096399,61096669,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive,GC_DNase_positive:chr7:61079125-61079394_activ...
76880,GC_DNase_positive:chr7:68527446-68527715_activ...,GAGAGAAAATAAAGCAATTTATGCTGTGAAAGAAAAAATACTAGTT...,element,element inactive control,NaN,GRCh37,chr7,69062458,69062728,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive,GC_DNase_positive:chr7:68527446-68527715_activ...
76881,GC_DNase_positive:chr8:8085418-8085687_active_...,GGCTGGGCACGGTGGCTCACACCTGTAATCTTAGCACTAGGGAGGC...,element,element inactive control,NaN,GRCh37,chr8,8227895,8228165,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive,GC_DNase_positive:chr8:8085418-8085687_active_...
76882,GC_DNase_positive:chr8:56755078-56755347_activ...,CAGTTTACAATAGGGTTTGTGCTCCTGTGAGAATCTAACGCTGCTG...,element,element inactive control,NaN,GRCh37,chr8,55842518,55842788,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive,GC_DNase_positive:chr8:56755078-56755347_activ...
76883,GC_DNase_positive:chr9:88419918-88420187_activ...,CCAGGCAGTTCCAGTTGGCATGATAATGCAGTTCCCAATCAGTGAT...,element,element inactive control,NaN,GRCh37,chr9,85805002,85805272,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive,GC_DNase_positive:chr9:88419918-88420187_activ...

In [19]:
# remove the shuffled sequences => they will be shuffled with the script
general_dnase_control_seqs_no_shuffled = general_dnase_control_sequences.loc[~general_dnase_control_sequences["label"].str.contains("shuff")].copy()

In [20]:
general_dnase_control_seqs_no_shuffled # no shuffled remove brackets for the final general control
general_dnase_control_seqs_no_shuffled['no_tailing_brackets_name'] = general_dnase_control_seqs_no_shuffled["no_tailing_brackets_name"].apply(remove_tailing_brackets_of_dnase_headers)

In [21]:
metadata_hg38_dnase_sequences = general_control_metadata_dnase_no_shuffled.merge(general_dnase_control_seqs_no_shuffled.drop(columns=["label"]), on="no_tailing_brackets_name", how="inner")

In [22]:
metadata_hg38_dnase_sequences
metadata_hg38_dnase_sequences[col_info] = pd.NA
metadata_hg38_dnase_sequences.drop(columns=[col_name, col_sequence], inplace=True)
metadata_hg38_dnase_sequences.rename(columns={"no_tailing_brackets_name": col_name, "hg38_sequence": col_sequence}, inplace=True)
metadata_hg38_dnase_sequences["ref"] = "GRCh38"

In [23]:
metadata_hg38_dnase_sequences = metadata_hg38_dnase_sequences[['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info', 'label']]

In [24]:
metadata_hg38_dnase_sequences["label"].value_counts()

label
GC_DNase_positive          41
GC_DNase_negative_brain    15
GC_DNase_negative_blood    15
Name: count, dtype: int64

In [25]:
metadata_hg38_dnase_sequences

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CTTTTTTTTCCTCTCTGAACAAATCAATCACTTTAAAAAGGAAGAA...,element,element inactive control,NaN,GRCh38,chr1,4708882,4709152,+,None,None,None,None,<NA>,GC_DNase_negative_brain
1,GC_DNase_negative_brain:chr10:27823303-2782357...,ATTTTAACAAGCTCTTCATATGGTTTGTATGCACATTAATTTTTGA...,element,element inactive control,NaN,GRCh38,chr10,27534373,27534643,+,None,None,None,None,<NA>,GC_DNase_negative_brain
2,GC_DNase_negative_brain:chr11:75379056-7537932...,ACCGAGTCCGCGGGGCCGGAGGTGGAGCCGGAGCCCAGGCCCGGGC...,element,element inactive control,NaN,GRCh38,chr11,75668010,75668280,+,None,None,None,None,<NA>,GC_DNase_negative_brain
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TTATAAATTTGAAATTATAGGAACTGCTGAGGGGTGATTTTTTTTT...,element,element inactive control,NaN,GRCh38,chr13,34722983,34723253,+,None,None,None,None,<NA>,GC_DNase_negative_brain
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTTTGACTGCTTTATTTCTCTCAGATGATATATGCTGGGATTTG...,element,element inactive control,NaN,GRCh38,chr13,66345227,66345497,+,None,None,None,None,<NA>,GC_DNase_negative_brain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,GC_DNase_positive:chr7:61079125-61079394_activ...,GTTAGAGCAGTTTTGAAACACTCTTTTTGTAGAATCTGCAAGTTGA...,element,element inactive control,NaN,GRCh38,chr7,61096399,61096669,+,None,None,None,None,<NA>,GC_DNase_positive
67,GC_DNase_positive:chr7:68527446-68527715_activ...,AACTGAAGAAATTCAGTGAAATGCGGGTAAACGGCGGGAGTAACTA...,element,element inactive control,NaN,GRCh38,chr7,69062458,69062728,+,None,None,None,None,<NA>,GC_DNase_positive
68,GC_DNase_positive:chr8:8085418-8085687_active_...,TCCCGACACCGGCCCCTCCCTAAGCTCCGCCTCCCAGGGCCCGCCT...,element,element inactive control,NaN,GRCh38,chr8,8227895,8228165,+,None,None,None,None,<NA>,GC_DNase_positive
69,GC_DNase_positive:chr8:56755078-56755347_activ...,CCAGGACCTCTAATATTAACTTTACTGGATAAAACTGTGTGGGTTG...,element,element inactive control,NaN,GRCh38,chr8,55842518,55842788,+,None,None,None,None,<NA>,GC_DNase_positive
70,GC_DNase_positive:chr9:88419918-88420187_activ...,GTCTCATTCCCTCGGGAGGCCTCCCTCCTTCCACCCGCTTGAGGAG...,element,element inactive control,NaN,GRCh38,chr9,85805002,85805272,+,None,None,None,None,<NA>,GC_DNase_positive

In [26]:
### still need for shuffling the seqeunces

reference=/home/kisa/coding/80K_MPRA/reference_genome_match/hg38.fa
for i in /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls_no_shuffled.bed; do
    name=`basename $i .bed`
    bedtools getfasta -nameOnly -fi $reference -bed $i | \
    awk '{if ($0 ~ /^>/){print $0} else { print toupper($0)}}' > $name.tmp

    fasta-dinucleotide-shuffle -f $name.tmp -s 42 -c 200 | \
    python /home/kisa/coding/80K_MPRA/MPRAOligoDesign/workflow/scripts/kMerFilter.py -i $name.tmp -k 6 > $name.diShuffled.fa
    rm $name.tmp
done;

# /home/kisa/coding/80K_MPRA/MPRAOligoDesign/workflow/scripts/kMerFilter.py

SyntaxError: invalid syntax (2248032834.py, line 3)

In [27]:
shuffled_sequences_dnase = hf.fasta_to_dataframe("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls_no_shuffled.diShuffled.fa", columns=[col_name, col_sequence])

In [28]:
shuffled_sequences_dnase

,name,sequence
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CGCTCAGAATTCCGCTGGCCTTAGTTGTTGGAACCTGCCATGTTGA...
1,GC_DNase_negative_brain:chr10:27823303-2782357...,AGACCAGCTCAAGTTTATTTCTTGTGATACCAACATTGCATTTCAG...
2,GC_DNase_negative_brain:chr11:75379056-7537932...,AGCGTGTGGCGGCGCCCGGCCGAAGCGGGGGGGTGGGGGCTGTCGC...
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TAATAGTAAGATGATAAAATTCCTTAGATGTTTTAGTGGTCAACAA...
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTCTGGCAGCTTAGTTCAGCATTAGGCTTATCTTAAGGGAGACA...
...,...,...
66,GC_DNase_positive:chr7:61079125-61079394_activ...,GATATTACAACGGAGATTAATAATGTGCTTTCATTTTTTTACTTCA...
67,GC_DNase_positive:chr7:68527446-68527715_activ...,ACCAGAACGCTATCTGCTGCGAAGAACACACAAAGGCCAGAATTAC...
68,GC_DNase_positive:chr8:8085418-8085687_active_...,TACTAGCTGGCGCAACGGTCGGAGTTGACCGAACCCTCCCCCGGTC...
69,GC_DNase_positive:chr8:56755078-56755347_activ...,CATGTGAGACTCTGTGACTCCCAAATGTAACCCACCTTAGCCTTTT...
70,GC_DNase_positive:chr9:88419918-88420187_activ...,GAGCGTCCTGGCCGCACCGCCTTGGTACCGCGTGACCCCCTTGCGC...

In [29]:
shuffled_sequences_dnase[col_name] = shuffled_sequences_dnase[col_name].apply(remove_tailing_brackets_of_dnase_headers)

In [30]:
shuffled_sequences_dnase

,name,sequence
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CGCTCAGAATTCCGCTGGCCTTAGTTGTTGGAACCTGCCATGTTGA...
1,GC_DNase_negative_brain:chr10:27823303-2782357...,AGACCAGCTCAAGTTTATTTCTTGTGATACCAACATTGCATTTCAG...
2,GC_DNase_negative_brain:chr11:75379056-7537932...,AGCGTGTGGCGGCGCCCGGCCGAAGCGGGGGGGTGGGGGCTGTCGC...
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TAATAGTAAGATGATAAAATTCCTTAGATGTTTTAGTGGTCAACAA...
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTCTGGCAGCTTAGTTCAGCATTAGGCTTATCTTAAGGGAGACA...
...,...,...
66,GC_DNase_positive:chr7:61079125-61079394_activ...,GATATTACAACGGAGATTAATAATGTGCTTTCATTTTTTTACTTCA...
67,GC_DNase_positive:chr7:68527446-68527715_activ...,ACCAGAACGCTATCTGCTGCGAAGAACACACAAAGGCCAGAATTAC...
68,GC_DNase_positive:chr8:8085418-8085687_active_...,TACTAGCTGGCGCAACGGTCGGAGTTGACCGAACCCTCCCCCGGTC...
69,GC_DNase_positive:chr8:56755078-56755347_activ...,CATGTGAGACTCTGTGACTCCCAAATGTAACCCACCTTAGCCTTTT...
70,GC_DNase_positive:chr9:88419918-88420187_activ...,GAGCGTCCTGGCCGCACCGCCTTGGTACCGCGTGACCCCCTTGCGC...

In [31]:
# add the scrambled sequence to the metadata file
metadata_hg38_dnase_sequences_shuffled = metadata_hg38_dnase_sequences.drop(columns=[col_sequence]).merge(shuffled_sequences_dnase, on=col_name, how="inner")

In [32]:
# change the name:
def modify_dnase_headers(header):
    """After bedtools the headers are slightly changed"""
    # remove brackets
    name = header.split("(.)")[0]
    # add shuffled name to header
    return name.split(":")[0] + "_shuffled:" + ":".join(name.split(":")[1:])

metadata_hg38_dnase_sequences_shuffled[col_name] = metadata_hg38_dnase_sequences_shuffled[col_name].apply(modify_dnase_headers)

# change the categroy
metadata_hg38_dnase_sequences_shuffled[col_category] = "scrambled"

# change the positive to active
def add_positive_control_class(row, name_col, class_col):
    name = row[name_col]
    if "positive" in name:
        row[class_col] = "element active control"
    return row

In [33]:
metadata_hg38_dnase_sequences_shuffled = metadata_hg38_dnase_sequences_shuffled.apply(lambda row: add_positive_control_class(row, col_name, col_class), axis=1)

In [34]:
metadata_hg38_dnase_sequences_shuffled.columns

Index(['name', 'category', 'class', 'source', 'ref', 'chr', 'start', 'end',
       'strand', 'variant_class', 'variant_pos', 'SPDI', 'allele', 'info',
       'label', 'sequence'],
      dtype='object')

In [35]:
metadata_columns = ['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr', 'start', 'end',
       'strand', 'variant_class', 'variant_pos', 'SPDI', 'allele', 'info']

In [36]:
# combine with other dnase controls with the sequences and the other metadata file and write to file
metadata_hg38_dnase_sequences = metadata_hg38_dnase_sequences[metadata_columns]
metadata_hg38_dnase_sequences_shuffled = metadata_hg38_dnase_sequences_shuffled[metadata_columns]

dnase_controls_hg38 = pd.concat([metadata_hg38_dnase_sequences, metadata_hg38_dnase_sequences_shuffled], ignore_index=True)

In [37]:
dnase_controls_hg38['label'] = dnase_controls_hg38[col_name].apply(hf.get_label)

In [38]:
# remove dnase controls from metadata and add the new dnase controls
metadata_df_no_dnase_controls = metadata_df.loc[~metadata_df['label'].str.contains("DNase")]

dnase_corrected_metadata_file = pd.concat([dnase_controls_hg38, metadata_df_no_dnase_controls], ignore_index=True)

In [39]:
general_controls = dnase_corrected_metadata_file.loc[dnase_corrected_metadata_file['label'].str.contains("GC_")].copy()

In [40]:
general_controls[col_start] = general_controls[col_start].astype(int)
general_controls[col_end] = general_controls[col_end].astype(int)

In [41]:
general_controls["label"].value_counts()

label
GC_Selvarajan                       358
GC_Vista                            256
GC_Mendelian_variants               209
GC_Kircher                          203
GC_Cort_Chengyu                     185
GC_Glut_Chengyu                      83
GC_Atrial_fib                        45
GC_GABA_Chengyu                      42
GC_DNase_positive                    41
GC_DNase_positive_shuffled           41
GC_Mohlke                            38
GC_Liang                             16
GC_DNase_negative_brain              15
GC_DNase_negative_brain_shuffled     15
GC_DNase_negative_blood              15
GC_DNase_negative_blood_shuffled     15
GC_Hon                                6
Name: count, dtype: int64

In [42]:
# general_controls.to_csv("corrected_general_controls.metadata.tsv.gz", sep="\t", header=True, index=False)

#### Test if the general controls are already updated:
- Kircher sequence header short? yes
- Kircher correct regions? yes
- dnase sequences updated?  
- regions correct?
- Mendelian variants
- Engritz

In [ ]:
# kircher is fine: checked with blat
# dnase is fine, checked with blat

In [ ]:
mendelian_variant_controls = general_control_metadata.loc[general_control_metadata['label'] == "GC_Mendelian_variants"].copy()
mendelian_variant_controls

In [185]:
general_control_metadata['label'].value_counts()

label
GC_Selvarajan                       358
GC_Vista                            256
GC_Mendelian_variants               209
GC_Kircher                          203
GC_Cort_Chengyu                     185
GC_Glut_Chengyu                      83
GC_Atrial_fib                        45
GC_GABA_Chengyu                      42
GC_DNase_positive                    41
GC_DNase_positive_shuffled           41
GC_Mohlke                            38
GC_Liang                             16
GC_DNase_negative_brain_shuffled     15
GC_DNase_negative_blood_shuffled     15
GC_DNase_negative_brain              15
GC_DNase_negative_blood              15
GC_Hon                                6
Name: count, dtype: int64

In [ ]:
# get the corrected controls and sanity check them

In [ ]:
general_controls = pd.read_csv("corrected_general_controls.metadata.tsv.gz", sep="\t", low_memory=False)
general_controls['label'].value_counts()
# dnase and shuffled look fine (because same name)

# # checked a sequence => same genomic regions
# mendelian_variants = general_controls.loc[general_controls["label"].str.contains("GC_Mendelian_variants")]
# # Kircher looks fine
# kircher = general_controls.loc[general_controls["label"].str.contains("GC_Kircher")]

# GC_Selvarajan

label
GC_Selvarajan                       358
GC_Vista                            256
GC_Mendelian_variants               209
GC_Kircher                          203
GC_Cort_Chengyu                     185
GC_Glut_Chengyu                      83
GC_Atrial_fib                        45
GC_GABA_Chengyu                      42
GC_DNase_positive                    41
GC_DNase_positive_shuffled           41
GC_Mohlke                            38
GC_Liang                             16
GC_DNase_negative_brain              15
GC_DNase_negative_brain_shuffled     15
GC_DNase_negative_blood              15
GC_DNase_negative_blood_shuffled     15
GC_Hon                                6
Name: count, dtype: int64

In [10]:
kircher

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
1194,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659,109274929,+,"['SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SN...","[135, 177, 181, 186, 187, 193, 198, 201, 206, ...","['NC_000001.11:109274794:C:T', 'NC_000001.11:1...","['ref', 'ref', 'ref', 'ref', 'ref', 'ref', 're...",NaN,GC_Kircher
1195,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771,109275041,+,"['SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SN...","[65, 69, 74, 75, 81, 86, 89, 94, 98, 113, 114,...","['NC_000001.11:109274836:C:T', 'NC_000001.11:1...","['ref', 'ref', 'ref', 'ref', 'ref', 'ref', 're...",NaN,GC_Kircher
1196,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,CAGTCATGTGTTAAGTTGCGCTTCTTTGCTGTGATGTGGGTGGGGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274882,109275152,+,"['SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SN...","[26, 28, 30, 35, 40, 41, 42, 43, 44, 45, 46, 4...","['NC_000001.11:109274908:T:G', 'NC_000001.11:1...","['ref', 'ref', 'ref', 'ref', 'ref', 'ref', 're...",NaN,GC_Kircher
1197,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,"['SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SNV', 'SN...","[26, 27, 28, 29, 32, 33, 34, 43, 45, 46, 47, 4...","['NC_000001.11:109275019:C:T', 'NC_000001.11:1...","['ref', 'ref', 'ref', 'ref', 'ref', 'ref', 're...",NaN,GC_Kircher
1198,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,"['SNV', 'SNV', 'SNV', 'SNV']","[62, 66, 74, 135]","['NC_000001.11:109275167:C:T', 'NC_000001.11:1...","['ref', 'ref', 'ref', 'ref']",NaN,GC_Kircher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,['SNV'],[178],['NC_000001.11:109275171:G:T'],['alt'],NaN,GC_Kircher
1393,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,['SNV'],[66],['NC_000001.11:109275171:G:T'],['alt'],NaN,GC_Kircher
1394,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,['SNV'],[186],['NC_000001.11:109275179:A:T'],['alt'],NaN,GC_Kircher
1395,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,['SNV'],[74],['NC_000001.11:109275179:A:T'],['alt'],NaN,GC_Kircher
1396,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,['SNV'],[135],['NC_000001.11:109275240:C:A'],['alt'],NaN,GC_Kircher

##### Engritz controls:
- Are they filtered out by MPRAoligodesign? - yes 
- figure out how to run MPRAOligodesign with only bed => done and all of these regions are filtered out because of TSS overlap
- test the original regions with MPRAoligodesign (they were slopped with -s -l (I guess this is wrong) )

- add engreitz controls (I checked if the TSS were added because of the extension of the sequences to 270bp but this is not the case => I will add them as they are defined in MPRAOligoDesign)
  - `/data/cephfs-1/scratch/groups/kircher/MPRA/mendelian_variant_second_version/MPRAOligoDesign/resources/controls/Engreitz/Engreitz.housekeeping.promoters.controls.bed.gz`
- check dnase controls
- check shuffled controls

In [5]:
# read the corrected general controls
general_controls = pd.read_csv("corrected_general_controls.metadata.tsv.gz", sep="\t", low_memory=False)

# read the Engreitz controls => bring them in metadata format
engreitz_bed_path = "/data/cephfs-1/scratch/groups/kircher/MPRA/mendelian_variant_second_version/MPRAOligoDesign/resources/controls/Engreitz/Engreitz.housekeeping.promoters.controls.bed.gz"
engreitz_bed = pd.read_csv(engreitz_bed_path, sep="\t", header=None, names=[col_chr, col_start, col_end, col_name, "score", col_strand])
engreitz_bed

engreitz_bed[col_category] = "element"
engreitz_bed[col_class] = "element active control"
engreitz_bed[col_ref] = "GRCh38"
engreitz_bed[col_source] = "Engreitz housekeeping promoters"

# name: label: GC_Engreitz:<gene_name>:<chr>:<start>:<end>:<strand>
# sequence: getfasta from hg38

engreitz_fasta_df = hf.fasta_to_dataframe("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/engreitz_sequence.fa", columns=[col_name, col_sequence])
# bedtools getfasta -fi /home/kisa/coding/80K_MPRA/reference_genome_match/hg38.fa -bed <(zcat /data/cephfs-1/scratch/groups/kircher/MPRA/mendelian_variant_second_version/MPRAOligoDesign/resources/controls/Engreitz/Engreitz.housekeeping.promoters.controls.bed.gz) -fo engreitz_sequence.fa -nameOnly
engreitz_fasta_df[col_sequence] = engreitz_fasta_df[col_sequence].str.upper()

In [6]:
# get the sequence
engreitz_metadata_df = engreitz_bed.merge(engreitz_fasta_df, on=col_name, how="inner")

engreitz_metadata_df['gene_name'] = engreitz_metadata_df['name'].copy()
# define the sequence name
engreitz_metadata_df[col_name] = "GC_Engreitz:" + engreitz_metadata_df['gene_name'].astype(str) + "_" + engreitz_metadata_df[col_chr].astype(str) + ":" + engreitz_metadata_df[col_start].astype(str) + "-" + engreitz_metadata_df[col_end].astype(str)
# set the unused columns to na
engreitz_metadata_df[['variant_class', 'variant_pos', 'SPDI', 'allele', 'info']] = pd.NA
# only focus on the needed columns
interesting_columns = [col_name, col_sequence, col_category, col_class, col_source, col_ref, col_chr, col_start, col_end, col_strand, col_variant_class, col_variant_pos, col_SPDI, col_allele, col_info]
engreitz_metadata = engreitz_metadata_df[interesting_columns]

In [ ]:
group_name = "GC_Engreitz"
output_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/"
import os
# # Write DataFrame to TSV file
# engreitz_metadata.to_csv(os.path.join(output_path, f'{group_name}.metadata.tmp.tsv.gz'), sep='\t', index=False, na_rep='NA', compression='gzip')
# os.system(f'zcat {output_path}/{group_name}.metadata.tmp.tsv.gz | sed "s/\'/\\"/g" | gzip -c > {output_path}/{group_name}.metadata.tsv.gz')

0

In [7]:
general_controls_with_engreitz = pd.concat([general_controls, engreitz_metadata], ignore_index=True)

In [50]:
general_controls

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CTTTTTTTTCCTCTCTGAACAAATCAATCACTTTAAAAAGGAAGAA...,element,element inactive control,NaN,GRCh38,chr1,4708882,4709152,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
1,GC_DNase_negative_brain:chr10:27823303-2782357...,ATTTTAACAAGCTCTTCATATGGTTTGTATGCACATTAATTTTTGA...,element,element inactive control,NaN,GRCh38,chr10,27534373,27534643,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
2,GC_DNase_negative_brain:chr11:75379056-7537932...,ACCGAGTCCGCGGGGCCGGAGGTGGAGCCGGAGCCCAGGCCCGGGC...,element,element inactive control,NaN,GRCh38,chr11,75668010,75668280,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TTATAAATTTGAAATTATAGGAACTGCTGAGGGGTGATTTTTTTTT...,element,element inactive control,NaN,GRCh38,chr13,34722983,34723253,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTTTGACTGCTTTATTTCTCTCAGATGATATATGCTGGGATTTG...,element,element inactive control,NaN,GRCh38,chr13,66345227,66345497,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1578,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element inactive control,NaN,GRCh38,chr12,44940898,44941168,-,NaN,NaN,NaN,NaN,NaN,GC_Glut_Chengyu
1579,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element inactive control,NaN,GRCh38,chr2,212699380,212699650,+,NaN,NaN,NaN,NaN,NaN,GC_Glut_Chengyu
1580,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element inactive control,NaN,GRCh38,chr10,26798828,26799098,-,NaN,NaN,NaN,NaN,NaN,GC_Glut_Chengyu
1581,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element inactive control,NaN,GRCh38,chr7,31260963,31261233,+,NaN,NaN,NaN,NaN,NaN,GC_Glut_Chengyu
1582,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element inactive control,NaN,GRCh38,chr12,44688247,44688517,-,NaN,NaN,NaN,NaN,NaN,GC_Glut_Chengyu

In [52]:
general_controls_with_engreitz

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CTTTTTTTTCCTCTCTGAACAAATCAATCACTTTAAAAAGGAAGAA...,element,element inactive control,NaN,GRCh38,chr1,4708882,4709152,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
1,GC_DNase_negative_brain:chr10:27823303-2782357...,ATTTTAACAAGCTCTTCATATGGTTTGTATGCACATTAATTTTTGA...,element,element inactive control,NaN,GRCh38,chr10,27534373,27534643,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
2,GC_DNase_negative_brain:chr11:75379056-7537932...,ACCGAGTCCGCGGGGCCGGAGGTGGAGCCGGAGCCCAGGCCCGGGC...,element,element inactive control,NaN,GRCh38,chr11,75668010,75668280,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TTATAAATTTGAAATTATAGGAACTGCTGAGGGGTGATTTTTTTTT...,element,element inactive control,NaN,GRCh38,chr13,34722983,34723253,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTTTGACTGCTTTATTTCTCTCAGATGATATATGCTGGGATTTG...,element,element inactive control,NaN,GRCh38,chr13,66345227,66345497,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,GC_Engreitz:BUD31_chr7:99408722-99408992,GCGCGCCGCCTAAGTCCAGGCTTGCCCGTCTGCTGCCAGGCAACAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr7,99408722,99408992,+,NaN,NaN,NaN,NaN,NaN,NaN
1599,GC_Engreitz:PABPC1_chr8:100722036-100722306,AGCCCGGAGCACACACTCCGCACTCTCAGCACTAACCGCCGGGGAG...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,100722036,100722306,-,NaN,NaN,NaN,NaN,NaN,NaN
1600,GC_Engreitz:NDUFB9_chr8:124538931-124539201,CCGGAGGGCGCAATTCCTGGGTCCTGTGACCTTGGTGACCGACGCC...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,124538931,124539201,+,NaN,NaN,NaN,NaN,NaN,NaN
1601,GC_Engreitz:RPS6_chr9:19380196-19380466,TTGAAGCAGCTGAACGCCTCCGAGGCGCCACGGAAAAGAGGGCCAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,19380196,19380466,-,NaN,NaN,NaN,NaN,NaN,NaN
1602,GC_Engreitz:RPL35_chr9:124861910-124862180,ATTGCTGCACAAGCCGCCAACGCCGCCGCCCGCTCCGAGGGAAAGA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,124861910,124862180,-,NaN,NaN,NaN,NaN,NaN,NaN

#### Focus on GC_kircher and rename the sequences + variant region map
- the naming is as follows: 
    - REF_<region of reference and the designed variants> + <tile info> 
    - ALT_<region of reference> + <tile info> + <variant info>
- Process: 
    - store the information of the exact reference sequence in the info column
- Goal: 
    - REF_tile_info
    - ALT_tile_info_variant_info

In [179]:
general_kircher = general_controls.loc[general_controls['label'].str.contains("Kircher")].copy()

In [ ]:
# general_kircher.to_csv("initial_gc_kircher.test.tsv", sep="\t", header=True, index=False)

In [180]:
def extract_reference_from_kircher_name(name):
    """Gets kircher header
    1. if GC_Kircher:ALT_:
        remove the last underscore

    remove the first two underscores
    remove all occurences of KircherControls
    and return as reference name
    """
    if name.startswith("GC_Kircher:ALT_"):
        name = "_".join(name.split("_")[:-5])
    region_name = "_".join(name.split("_")[2:])
    return region_name


def extract_variant_info_from_kircher_name(name):
    if name.startswith("GC_Kircher:ALT_"):
        return "_".join(name.split("_")[-5:])
    return pd.NA


def shorten_kircher_control_name(row, tile_col="tile_info", variant_col="variant_info", name_col="name", chr_col="chr", start_col="start", end_col="end"):
    """
    Remove the region info and only have GC_Kircher:REF_<tile_info> or GC_Kircher:ALT_<tile_info>_variant_info
    """
    name = row[name_col]
    tile_info = row[tile_col]
    ref_alt_info = "_".join(name.split("_")[:2])
    region_info = f'{row[chr_col]}:{row[start_col]}-{row[end_col]}'
    new_name = f'{ref_alt_info}_SORT1_{region_info}_{tile_info}' # only SORT1 regions santiy checked with Max
    if "GC_Kircher:ALT" in ref_alt_info:
        variant_info = row[variant_col]
        return f"{new_name}_{variant_info}"
    return new_name

In [181]:
# gather info
general_kircher['reference'] = general_kircher[col_name].apply(extract_reference_from_kircher_name)
general_kircher['variant_info'] = general_kircher[col_name].apply(extract_variant_info_from_kircher_name)
general_kircher["tile_info"] = general_kircher["reference"].apply(lambda ref: ref.split("_")[-1])

# shorten the name
general_kircher["short_name"] = general_kircher.apply(lambda row: shorten_kircher_control_name(row, tile_col="tile_info", variant_col="variant_info", name_col="name", chr_col="chr", start_col="start", end_col="end"), axis=1)

In [182]:
general_kircher

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label,reference,variant_info,tile_info,short_name
76662,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659,109274929,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[135, 177, 181, 186, 187, 193, 198, 201, 206, ...","[NC_000001.11:109274794:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile1-5,GC_Kircher:REF_SORT1_chr1:109274659-109274929_...
76663,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771,109275041,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[65, 69, 74, 75, 81, 86, 89, 94, 98, 113, 114,...","[NC_000001.11:109274836:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile2-5,GC_Kircher:REF_SORT1_chr1:109274771-109275041_...
76664,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,CAGTCATGTGTTAAGTTGCGCTTCTTTGCTGTGATGTGGGTGGGGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274882,109275152,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 28, 30, 35, 40, 41, 42, 43, 44, 45, 46, 4...","[NC_000001.11:109274908:T:G, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile3-5,GC_Kircher:REF_SORT1_chr1:109274882-109275152_...
76665,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 27, 28, 29, 32, 33, 34, 43, 45, 46, 47, 4...","[NC_000001.11:109275019:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile4-5,GC_Kircher:REF_SORT1_chr1:109274993-109275263_...
76666,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,"[SNV, SNV, SNV, SNV]","[62, 66, 74, 135]","[NC_000001.11:109275167:C:T, NC_000001.11:1092...","[ref, ref, ref, ref]",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile5-5,GC_Kircher:REF_SORT1_chr1:109275105-109275375_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76860,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,[SNV],[178],[NC_000001.11:109275171:G:T],[alt],NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",NC000001_11_109275171_G_T,tile4-5,GC_Kircher:ALT_SORT1_chr1:109274993-109275263_...
76861,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,[SNV],[66],[NC_000001.11:109275171:G:T],[alt],NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",NC000001_11_109275171_G_T,tile5-5,GC_Kircher:ALT_SORT1_chr1:109275105-109275375_...
76862,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,[SNV],[186],[NC_000001.11:109275179:A:T],[alt],NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",NC000001_11_109275179_A_T,tile4-5,GC_Kircher:ALT_SORT1_chr1:109274993-109275263_...
76863,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,[SNV],[74],[NC_000001.11:109275179:A:T],[alt],NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",NC000001_11_109275179_A_T,tile5-5,GC_Kircher:ALT_SORT1_chr1:109275105-109275375_...
76864,GC_Kircher:ALT_NC000001.11|109274794|C|T|Kirch...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105,109275375,+,[SNV],[135],[NC_000001.11:109275240:C:A],[alt],NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",NC000001_11_109275240_C_A,tile5-5,GC_Kircher:ALT_SORT1_chr1:109275105-109275375_...

In [48]:
general_kircher["short_name"] = general_kircher.apply(lambda row: shorten_kircher_control_name(row, tile_col="tile_info", variant_col="variant_info", name_col="name", chr_col="chr", start_col="start", end_col="end"), axis=1)

general_kircher["allele"].apply(lambda allele: "alt" in allele).sum()
# plan to have: ID REF ALT
# shorten the REF and ALT id
# remove KircherControls
# res = test_str.general_kircherreplace("|KircherControls", "")

198

##### Check if the genomic regions in hg38 are the same as the given fasta sequences (they are so shortening the headers is fine)

In [49]:
general_kircher_ref = general_kircher.loc[general_kircher["short_name"].str.contains("REF")].copy()
general_kircher_ref.rename(columns={"short_name": "REF"}, inplace=True)
general_kircher_ref[[col_chr, col_start, col_end, "REF"]].to_csv("gc_kircher_check_genomic_references.bed", sep="\t", header=None, index=None)

In [50]:
# get fasta of the genomic regions from kircher
# bedtools getfasta -fi /home/kisa/coding/80K_MPRA/reference_genome_match/hg38.fa -bed /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/gc_kircher_check_genomic_references.bed -fo /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_kircher_reference_sequences.fa -nameOnly

# read sequences in and compare to the actual sequences
input_hg38_seq_kircher = hf.fasta_to_dataframe("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_kircher_reference_sequences.fa", columns=["ref_name", "sequence"])
# inner join over sequence and look if they match
general_kircher_ref.merge(input_hg38_seq_kircher, on="sequence", how="inner")

,name,sequence,category,class,source,ref,chr,start,end,strand,...,variant_pos,SPDI,allele,info,label,reference,variant_info,tile_info,REF,ref_name
0,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659,109274929,+,...,"[135, 177, 181, 186, 187, 193, 198, 201, 206, ...","[NC_000001.11:109274794:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile1-5,GC_Kircher:REF_SORT1_chr1:109274659-109274929_...,GC_Kircher:REF_SORT1_chr1:109274659-109274929_...
1,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771,109275041,+,...,"[65, 69, 74, 75, 81, 86, 89, 94, 98, 113, 114,...","[NC_000001.11:109274836:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile2-5,GC_Kircher:REF_SORT1_chr1:109274771-109275041_...,GC_Kircher:REF_SORT1_chr1:109274771-109275041_...
2,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,CAGTCATGTGTTAAGTTGCGCTTCTTTGCTGTGATGTGGGTGGGGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274882,109275152,+,...,"[26, 28, 30, 35, 40, 41, 42, 43, 44, 45, 46, 4...","[NC_000001.11:109274908:T:G, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile3-5,GC_Kircher:REF_SORT1_chr1:109274882-109275152_...,GC_Kircher:REF_SORT1_chr1:109274882-109275152_...
3,GC_Kircher:REF_NC000001.11|109274794|C|T|Kirch...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993,109275263,+,...,"[26, 27, 28, 29, 32, 33, 34, 43, 45, 46, 47, 4...","[NC_000001.11:109275019:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher,"NC000001.11|109274794|C|T|KircherControls,NC00...",<NA>,tile4-5,GC_Kircher:REF_SORT1_chr1:109274993-109275263_...,GC_Kircher:REF_SORT1_chr1:109274993-109275263_...

In [51]:
input_hg38_seq_kircher

,ref_name,sequence
0,GC_Kircher:REF_SORT1_chr1:109274659-109274929_...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...
1,GC_Kircher:REF_SORT1_chr1:109274771-109275041_...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...
2,GC_Kircher:REF_SORT1_chr1:109274882-109275152_...,CAGTCATGTGTTAAGTTGCGCTTCTTTGCTGTGATGTGGGTGGGGG...
3,GC_Kircher:REF_SORT1_chr1:109274993-109275263_...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...
4,GC_Kircher:REF_SORT1_chr1:109275105-109275375_...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...

##### Write new kircher metadata file

In [52]:
general_kircher.drop(columns=[col_name], inplace=True)

general_kircher.rename(columns={"short_name": col_name}, inplace=True)

In [53]:
general_kircher_final = general_kircher[['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info', 'label']].copy()

In [54]:
metadata_df.columns

Index(['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info', 'label'],
      dtype='object')

In [55]:
# remove dnase controls from metadata and add the new dnase controls
metadata_df_no_kircher = dnase_corrected_metadata_file.loc[~dnase_corrected_metadata_file['label'].str.contains("GC_Kircher")]

kircher_corrected_metadata_file = pd.concat([general_kircher_final, metadata_df_no_kircher], ignore_index=True)

In [56]:
kircher_corrected_metadata_file['label'].value_counts()

label
cardiac_neuro_cava_random           73940
MK                                   2397
C_positive_heart_AB                   909
GC_Selvarajan                         358
GC_Vista                              256
C_negative_heart_MK                   243
C_negative_neuron_MK                  222
C_negative_neuron_NP                  217
GC_Mendelian_variants                 209
GC_Kircher                            203
C_SLEA                                200
GC_Cort_Chengyu                       185
C_positive_heart_CAD                   99
C_positive_neuron_NP                   99
C_positive_heart_MK                    97
C_positive_neuron_MK                   96
C_positive_neuron_CD                   94
GC_Glut_Chengyu                        83
GC_Atrial_fib                          45
GC_GABA_Chengyu                        42
GC_DNase_positive_shuffled             41
GC_DNase_positive                      41
GC_Mohlke                              38
GC_Liang                               16
GC_DNase_negative_brain_shuffled       15
GC_DNase_negative_blood_shuffled       15
GC_DNase_negative_brain                15
GC_DNase_negative_blood                15
GC_Hon                                  6
Name: count, dtype: int64

##### Generate variant region map
- only alt => get a new column => shortend region name without the variant case

In [57]:
general_kircher_alt = general_kircher.loc[general_kircher[col_name].str.contains("ALT")].copy()
general_kircher_alt.rename(columns={col_name: "ALT"}, inplace=True)
def ref_from_short_name_kircher_controls(short_name):
    # remove variant info
    short_name = "_".join(short_name.split("_")[:-5])
    # replace ALT with REF
    return short_name.replace(":ALT", ":REF")

general_kircher_alt['REF'] = general_kircher_alt["ALT"].apply(ref_from_short_name_kircher_controls)

In [58]:
kircher_variant_map = general_kircher_alt[[col_chr, col_start, col_end, "ALT", "REF"]].merge(general_kircher_ref[["REF"]], on="REF", how="inner")
kircher_variant_map["ID"] = kircher_variant_map["ALT"]
kircher_variant_map[["ID", "REF", "ALT"]].to_csv("GC_Kircher_variant_map.tsv.gz", sep="\t", header=None, index=False)

#### Focus on Element activity (class)

In [59]:
kircher_corrected_metadata_file['class'].value_counts()

class
test                        73940
element inactive control     3653
variant negative control     2073
variant positive control      372
element active control        158
Name: count, dtype: int64

In [60]:
kircher_corrected_metadata_file

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,GC_Kircher:REF_SORT1_chr1:109274659-109274929_...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659.0,109274929.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[135, 177, 181, 186, 187, 193, 198, 201, 206, ...","[NC_000001.11:109274794:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
1,GC_Kircher:REF_SORT1_chr1:109274771-109275041_...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771.0,109275041.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[65, 69, 74, 75, 81, 86, 89, 94, 98, 113, 114,...","[NC_000001.11:109274836:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
2,GC_Kircher:REF_SORT1_chr1:109274882-109275152_...,CAGTCATGTGTTAAGTTGCGCTTCTTTGCTGTGATGTGGGTGGGGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274882.0,109275152.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 28, 30, 35, 40, 41, 42, 43, 44, 45, 46, 4...","[NC_000001.11:109274908:T:G, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
3,GC_Kircher:REF_SORT1_chr1:109274993-109275263_...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993.0,109275263.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 27, 28, 29, 32, 33, 34, 43, 45, 46, 47, 4...","[NC_000001.11:109275019:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
4,GC_Kircher:REF_SORT1_chr1:109275105-109275375_...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105.0,109275375.0,+,"[SNV, SNV, SNV, SNV]","[62, 66, 74, 135]","[NC_000001.11:109275167:C:T, NC_000001.11:1092...","[ref, ref, ref, ref]",NaN,GC_Kircher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80191,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element inactive control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN,GC_Glut_Chengyu
80192,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element inactive control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN,GC_Glut_Chengyu
80193,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element inactive control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN,GC_Glut_Chengyu
80194,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element inactive control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN,GC_Glut_Chengyu
80195,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element inactive control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN,GC_Glut_Chengyu

Reset the class column to be only inactive element for

In [61]:
def get_control_class_based_on_name_or_label(row, class_col="class", name_col="name", label_col="label", category_col="category"):
    """The given sequence is classified as "element inactive control" if the name contains scramble or the category is scrambled or the label contains _negative_"""
    if row[class_col] != "element inactive control":
        return row
    row[class_col] = "element active control"
    if row[category_col] == "scrambled" or ("negative" in row[label_col]) or ("scramb" in row[name_col]):
        row[class_col] = "element inactive control"
    return row

In [62]:
kircher_corrected_metadata_file = kircher_corrected_metadata_file.apply(lambda row: get_control_class_based_on_name_or_label(row, class_col=col_class, name_col=col_name, label_col="label", category_col=col_category), axis=1).copy()

In [63]:
negative_element_controls = kircher_corrected_metadata_file.loc[kircher_corrected_metadata_file["class"] == "element inactive control"].copy()

In [64]:
negative_element_controls["label"].value_counts()

label
MK                                  500
C_negative_heart_MK                 243
C_negative_neuron_MK                222
C_negative_neuron_NP                217
GC_DNase_negative_brain              15
GC_DNase_negative_blood_shuffled     15
GC_DNase_negative_brain_shuffled     15
GC_DNase_negative_blood              15
C_positive_neuron_CD                  3
Name: count, dtype: int64

#### Focus on control variants (TODO)
- get all the other controls and split them by having variants and not having variants
- identify which have variants: MK,

In [8]:
classes_of_interest = ["variant positive control", "variant negative control", "element active control"]

In [9]:
# active_element_and_variant_controls = kircher_corrected_metadata_file.loc[kircher_corrected_metadata_file["class"].isin(classes_of_interest)].copy() # 5000
active_element_and_variant_controls = general_controls_with_engreitz.loc[general_controls_with_engreitz["class"].isin(classes_of_interest)].copy() # 5000

In [10]:
# focus only on elements: do you find variants?
active_element_controls = active_element_and_variant_controls.loc[active_element_and_variant_controls["class"].str.contains("element")].copy()
active_element_controls

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
101,GC_DNase_positive_shuffled:chr1:121484605-1214...,TTTTTAGTTTTGCTTTTTCAGCTTTTCCTTTTTGACCGAGTTGGAA...,scrambled,element active control,NaN,GRCh38,chr1,121742806,121743076,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
102,GC_DNase_positive_shuffled:chr1:153959246-1539...,AGCCACATACACTTACAAGTGTCGGGAGAGAATACCTTGATATAAT...,scrambled,element active control,NaN,GRCh38,chr1,153986769,153987039,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
103,GC_DNase_positive_shuffled:chr1:156186296-1561...,CGCCCTCGGTCCCTCCAACACGGGTGGGGTACCCCCCCTGCACCGG...,scrambled,element active control,NaN,GRCh38,chr1,156216504,156216774,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
104,GC_DNase_positive_shuffled:chr1:161582223-1615...,AGGTTAAACCGGTCGCTCCCTCAAGTTCTATCCGCTCCTTCTTGAT...,scrambled,element active control,NaN,GRCh38,chr1,161612432,161612702,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
105,GC_DNase_positive_shuffled:chr1:223254657-2232...,GACCAGTTGCCCATGGTTCTCCGCCCAATGGCTATCCCAGTCCTCA...,scrambled,element active control,NaN,GRCh38,chr1,223081314,223081584,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,GC_Engreitz:BUD31_chr7:99408722-99408992,GCGCGCCGCCTAAGTCCAGGCTTGCCCGTCTGCTGCCAGGCAACAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr7,99408722,99408992,+,NaN,NaN,NaN,NaN,NaN,NaN
1599,GC_Engreitz:PABPC1_chr8:100722036-100722306,AGCCCGGAGCACACACTCCGCACTCTCAGCACTAACCGCCGGGGAG...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,100722036,100722306,-,NaN,NaN,NaN,NaN,NaN,NaN
1600,GC_Engreitz:NDUFB9_chr8:124538931-124539201,CCGGAGGGCGCAATTCCTGGGTCCTGTGACCTTGGTGACCGACGCC...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,124538931,124539201,+,NaN,NaN,NaN,NaN,NaN,NaN
1601,GC_Engreitz:RPS6_chr9:19380196-19380466,TTGAAGCAGCTGAACGCCTCCGAGGCGCCACGGAAAAGAGGGCCAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,19380196,19380466,-,NaN,NaN,NaN,NaN,NaN,NaN
1602,GC_Engreitz:RPL35_chr9:124861910-124862180,ATTGCTGCACAAGCCGCCAACGCCGCCGCCCGCTCCGAGGGAAAGA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,124861910,124862180,-,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
active_element_and_variant_controls["label"].value_counts()

label
GC_Selvarajan                 355
GC_Mendelian_variants         209
GC_Kircher                    203
GC_Atrial_fib                  44
GC_DNase_positive_shuffled     41
GC_Mohlke                      38
GC_Liang                       16
Name: count, dtype: int64

In [12]:
active_element_and_variant_controls

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
101,GC_DNase_positive_shuffled:chr1:121484605-1214...,TTTTTAGTTTTGCTTTTTCAGCTTTTCCTTTTTGACCGAGTTGGAA...,scrambled,element active control,NaN,GRCh38,chr1,121742806,121743076,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
102,GC_DNase_positive_shuffled:chr1:153959246-1539...,AGCCACATACACTTACAAGTGTCGGGAGAGAATACCTTGATATAAT...,scrambled,element active control,NaN,GRCh38,chr1,153986769,153987039,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
103,GC_DNase_positive_shuffled:chr1:156186296-1561...,CGCCCTCGGTCCCTCCAACACGGGTGGGGTACCCCCCCTGCACCGG...,scrambled,element active control,NaN,GRCh38,chr1,156216504,156216774,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
104,GC_DNase_positive_shuffled:chr1:161582223-1615...,AGGTTAAACCGGTCGCTCCCTCAAGTTCTATCCGCTCCTTCTTGAT...,scrambled,element active control,NaN,GRCh38,chr1,161612432,161612702,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
105,GC_DNase_positive_shuffled:chr1:223254657-2232...,GACCAGTTGCCCATGGTTCTCCGCCCAATGGCTATCCCAGTCCTCA...,scrambled,element active control,NaN,GRCh38,chr1,223081314,223081584,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_positive_shuffled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,GC_Engreitz:BUD31_chr7:99408722-99408992,GCGCGCCGCCTAAGTCCAGGCTTGCCCGTCTGCTGCCAGGCAACAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr7,99408722,99408992,+,NaN,NaN,NaN,NaN,NaN,NaN
1599,GC_Engreitz:PABPC1_chr8:100722036-100722306,AGCCCGGAGCACACACTCCGCACTCTCAGCACTAACCGCCGGGGAG...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,100722036,100722306,-,NaN,NaN,NaN,NaN,NaN,NaN
1600,GC_Engreitz:NDUFB9_chr8:124538931-124539201,CCGGAGGGCGCAATTCCTGGGTCCTGTGACCTTGGTGACCGACGCC...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,124538931,124539201,+,NaN,NaN,NaN,NaN,NaN,NaN
1601,GC_Engreitz:RPS6_chr9:19380196-19380466,TTGAAGCAGCTGAACGCCTCCGAGGCGCCACGGAAAAGAGGGCCAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,19380196,19380466,-,NaN,NaN,NaN,NaN,NaN,NaN
1602,GC_Engreitz:RPL35_chr9:124861910-124862180,ATTGCTGCACAAGCCGCCAACGCCGCCGCCCGCTCCGAGGGAAAGA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,124861910,124862180,-,NaN,NaN,NaN,NaN,NaN,NaN


- elements:
C_positive_heart_AB            909
GC_Vista                       256
C_SLEA                         200
GC_Cort_Chengyu                185
C_positive_heart_CAD            99
C_positive_neuron_NP            99
C_positive_heart_MK             97
C_positive_neuron_MK            96
C_positive_neuron_CD            91
GC_Glut_Chengyu                 83
GC_GABA_Chengyu                 42
GC_DNase_positive               41
GC_DNase_positive_shuffled      41

- variants:
GC_Atrial_fib                   45
GC_Kircher                     203
GC_Liang                        16
GC_Hon                           6
GC_Mohlke                       38
GC_Mendelian_variants          209

- both:
MK                            1897

- undecided
GC_Selvarajan                  358 (has some ref and alt which are not matchable)

In [13]:
variant_region_map_path = "/data/cephfs-1/home/users/kisa11_c/unmirrored/projects/80K_analysis/05_variant_region_list/resources/controls_variant_region_map.tsv.gz"
variant_region_map = pd.read_csv(variant_region_map_path, sep="\t")

In [14]:
variant_region_map['label'] = variant_region_map["ALT_ID"].apply(hf.get_label)
variant_region_map['label'].value_counts()

label
GC_Selvarajan            198
GC_Kircher               198
GC_Mendelian_variants    174
C_positive_heart_CAD      49
GC_Atrial_fib             23
GC_Mohlke                 20
GC_Liang                   8
Name: count, dtype: int64

In [15]:
variant_region_map

,Variant,Region,REF_ID,ALT_ID,label
0,GC_Atrial_fib:rs74541936,GC_Atrial_fib:rs74541936|KCNN3|STARR-seq-AF_fw...,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs74541936|KCNN3|STARR-seq-A...,GC_Atrial_fib
1,GC_Atrial_fib:rs34292822,GC_Atrial_fib:rs34292822|KCNN3|STARR-seq-AF_fw...,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs34292822|KCNN3|STARR-seq-A...,GC_Atrial_fib
2,GC_Atrial_fib:rs12754189,GC_Atrial_fib:rs12754189|KCNN3|STARR-seq-AF_fw...,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs12754189|KCNN3|STARR-seq-A...,GC_Atrial_fib
3,GC_Atrial_fib:rs36088503,GC_Atrial_fib:rs36088503|KCNN3|STARR-seq-AF_fw...,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,GC_Atrial_fib:ALT_rs36088503|KCNN3|STARR-seq-A...,GC_Atrial_fib
4,GC_Atrial_fib:rs76749863,"GC_Atrial_fib:rs1218584|KCNN3|STARR-seq-AF,rs7...",GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...,GC_Atrial_fib:ALT_rs1218584|KCNN3|STARR-seq-AF...,GC_Atrial_fib
...,...,...,...,...,...
665,C_positive_heart_CAD:rs7865618,C_positive_heart_CAD:rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD
666,C_positive_heart_CAD:rs4977757,C_positive_heart_CAD:rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD
667,C_positive_heart_CAD:rs1537373,C_positive_heart_CAD:rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD
668,C_positive_heart_CAD:rs10811656,C_positive_heart_CAD:rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD
669,C_positive_heart_CAD:rs507666,C_positive_heart_CAD:rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD

In [16]:
only_control_variants = active_element_and_variant_controls.loc[active_element_and_variant_controls[col_category] == "variant"].copy()
only_control_variants = only_control_variants.loc[only_control_variants['label'] != "MK"].copy()
# some allele columns are
only_control_variants_alt = only_control_variants.loc[only_control_variants[col_allele].apply(hf.is_alternative)].copy()
only_control_variants_alt.groupby("label").size()

# Selvarajan: 3 variants missing?

label
GC_Atrial_fib             23
GC_Kircher               198
GC_Liang                   8
GC_Mendelian_variants    163
GC_Mohlke                 20
GC_Selvarajan            195
dtype: int64

In [17]:
general_controls_with_engreitz['label'] = general_controls_with_engreitz['name'].apply(hf.get_label)

In [18]:
# investigate GC_Selvarajan group
selvarajan_controls = general_controls_with_engreitz.loc[general_controls_with_engreitz['label'].str.contains('GC_Selvarajan')].copy()

In [ ]:
selvarajan_controls # rs216222 not needed
# selvarajan variant controls
# GC_Selvarajan:REF_rs754064|STARR-seq-HepG2_fwd_tile1-1
# GC_Selvarajan:REF_rs216222|STARR-seq-HepG2_fwd_tile1-1

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
836,GC_Selvarajan:REF_rs216222|STARR-seq-HepG2_fwd...,TGCCTATAGTCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATTGCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr17,2252271,2252541,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
837,GC_Selvarajan:REF_rs754064|STARR-seq-HepG2_fwd...,CTGGTGTTATATTCACCTGACTAAATTTAGAAGGAACTGTGTATCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr20,48798773,48799043,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
838,GC_Selvarajan:ALT_rs2297787|STARR-seq-HepG2_fw...,GTGGCGTGGATTTGGGGATGGATTGAACTAGTAAGTGCTACTAGGT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr10,102920244,102920514,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
839,"GC_Selvarajan:REF_rs9660819|STARR-seq-HepG2,rs...",GGGGATGGTGCGGCCACGTCCAGGAGGCAGAAGCACAGAGAATGTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3036131,3036401,+,"['SNV', 'SNV']","[127, 144]","['NC_000001.11:3036258:C:T', 'NC_000001.11:303...","['ref', 'ref']",NaN,GC_Selvarajan
840,"GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2,rs...",GGGGTTGTGTGGTGTGTGTATCATGGTGTGTGTATATGTACTCTGT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3039882,3040152,+,"['SNV', 'SNV']","[135, 219]","['NC_000001.11:3040017:A:G', 'NC_000001.11:304...","['ref', 'ref']",NaN,GC_Selvarajan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,"GC_Selvarajan:ALT_rs10121140|STARR-seq-HepG2,r...",TGCCAAGATAACCAGAAACCAAATTCCTAGGATGCTAGAGCTAACA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,14292520,14292790,+,['SNV'],[200],['NC_000009.12:14292720:G:A'],['alt'],NaN,GC_Selvarajan
1190,"GC_Selvarajan:ALT_rs10121140|STARR-seq-HepG2,r...",AGGCCAATTCTCTTCCCTGACAGATACAGAAACTGAGTTACTGAGA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,14292585,14292855,+,['SNV'],[135],['NC_000009.12:14292720:G:A'],['alt'],NaN,GC_Selvarajan
1191,GC_Selvarajan:ALT_rs6475604|STARR-seq-HepG2_fw...,AAACTCGTAGAATTTGGCTGACTGCCTGGTTTATCCCAGGACATTA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,22052630,22052900,+,['SNV'],[104],['NC_000009.12:22052734:T:C'],['alt'],NaN,GC_Selvarajan
1192,GC_Selvarajan:ALT_rs1333045|STARR-seq-HepG2_fw...,TTTTTGCTCTGTTACATTAGGAAAGTTATGTAGAATTTTGTGCCTC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,22119060,22119330,+,['SNV'],[135],['NC_000009.12:22119195:T:C'],['alt'],NaN,GC_Selvarajan
1193,GC_Selvarajan:ALT_rs2297400|STARR-seq-HepG2_fw...,AACACAGCCAGTTCCTGGAAGGTCTTGTTCACCTGGAGTCAGGTGG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,104837064,104837334,+,['SNV'],[135],['NC_000009.12:104837199:T:C'],['alt'],NaN,GC_Selvarajan

In [22]:
# is there a reference for each alternative?
selvarajan_controls_alt = selvarajan_controls.loc[selvarajan_controls['name'].str.contains("ALT_")].copy()
selvarajan_controls_alt.loc[selvarajan_controls_alt['SPDI'].isna()]
# GC_Selvarajan:ALT_rs2297787|STARR-seq-HepG2_fwd_tile1-1_rs2297787

# remove GC_Selvarajan:ALT_rs2297787|STARR-seq-HepG2_fwd_tile1-1_rs2297787 because no reference associated

selvarajan_controls_filtered = selvarajan_controls.loc[~selvarajan_controls[col_name].str.contains("GC_Selvarajan:ALT_rs2297787|STARR-seq-HepG2_fwd_tile1-1_rs2297787", regex=False)].copy()
selvarajan_controls_filtered

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
836,GC_Selvarajan:REF_rs216222|STARR-seq-HepG2_fwd...,TGCCTATAGTCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATTGCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr17,2252271,2252541,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
837,GC_Selvarajan:REF_rs754064|STARR-seq-HepG2_fwd...,CTGGTGTTATATTCACCTGACTAAATTTAGAAGGAACTGTGTATCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr20,48798773,48799043,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
839,"GC_Selvarajan:REF_rs9660819|STARR-seq-HepG2,rs...",GGGGATGGTGCGGCCACGTCCAGGAGGCAGAAGCACAGAGAATGTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3036131,3036401,+,"['SNV', 'SNV']","[127, 144]","['NC_000001.11:3036258:C:T', 'NC_000001.11:303...","['ref', 'ref']",NaN,GC_Selvarajan
840,"GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2,rs...",GGGGTTGTGTGGTGTGTGTATCATGGTGTGTGTATATGTACTCTGT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3039882,3040152,+,"['SNV', 'SNV']","[135, 219]","['NC_000001.11:3040017:A:G', 'NC_000001.11:304...","['ref', 'ref']",NaN,GC_Selvarajan
841,"GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2,rs...",CTGTGCATACGGGCTGTGTATATATATGCTGTGTGTATATGTTGCA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3039924,3040194,+,"['SNV', 'SNV']","[93, 177]","['NC_000001.11:3040017:A:G', 'NC_000001.11:304...","['ref', 'ref']",NaN,GC_Selvarajan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,"GC_Selvarajan:ALT_rs10121140|STARR-seq-HepG2,r...",TGCCAAGATAACCAGAAACCAAATTCCTAGGATGCTAGAGCTAACA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,14292520,14292790,+,['SNV'],[200],['NC_000009.12:14292720:G:A'],['alt'],NaN,GC_Selvarajan
1190,"GC_Selvarajan:ALT_rs10121140|STARR-seq-HepG2,r...",AGGCCAATTCTCTTCCCTGACAGATACAGAAACTGAGTTACTGAGA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,14292585,14292855,+,['SNV'],[135],['NC_000009.12:14292720:G:A'],['alt'],NaN,GC_Selvarajan
1191,GC_Selvarajan:ALT_rs6475604|STARR-seq-HepG2_fw...,AAACTCGTAGAATTTGGCTGACTGCCTGGTTTATCCCAGGACATTA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,22052630,22052900,+,['SNV'],[104],['NC_000009.12:22052734:T:C'],['alt'],NaN,GC_Selvarajan
1192,GC_Selvarajan:ALT_rs1333045|STARR-seq-HepG2_fw...,TTTTTGCTCTGTTACATTAGGAAAGTTATGTAGAATTTTGTGCCTC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,22119060,22119330,+,['SNV'],[135],['NC_000009.12:22119195:T:C'],['alt'],NaN,GC_Selvarajan
1193,GC_Selvarajan:ALT_rs2297400|STARR-seq-HepG2_fw...,AACACAGCCAGTTCCTGGAAGGTCTTGTTCACCTGGAGTCAGGTGG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,104837064,104837334,+,['SNV'],[135],['NC_000009.12:104837199:T:C'],['alt'],NaN,GC_Selvarajan

In [23]:
selvarajan_controls

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
836,GC_Selvarajan:REF_rs216222|STARR-seq-HepG2_fwd...,TGCCTATAGTCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATTGCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr17,2252271,2252541,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
837,GC_Selvarajan:REF_rs754064|STARR-seq-HepG2_fwd...,CTGGTGTTATATTCACCTGACTAAATTTAGAAGGAACTGTGTATCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr20,48798773,48799043,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
838,GC_Selvarajan:ALT_rs2297787|STARR-seq-HepG2_fw...,GTGGCGTGGATTTGGGGATGGATTGAACTAGTAAGTGCTACTAGGT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr10,102920244,102920514,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
839,"GC_Selvarajan:REF_rs9660819|STARR-seq-HepG2,rs...",GGGGATGGTGCGGCCACGTCCAGGAGGCAGAAGCACAGAGAATGTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3036131,3036401,+,"['SNV', 'SNV']","[127, 144]","['NC_000001.11:3036258:C:T', 'NC_000001.11:303...","['ref', 'ref']",NaN,GC_Selvarajan
840,"GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2,rs...",GGGGTTGTGTGGTGTGTGTATCATGGTGTGTGTATATGTACTCTGT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3039882,3040152,+,"['SNV', 'SNV']","[135, 219]","['NC_000001.11:3040017:A:G', 'NC_000001.11:304...","['ref', 'ref']",NaN,GC_Selvarajan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,"GC_Selvarajan:ALT_rs10121140|STARR-seq-HepG2,r...",TGCCAAGATAACCAGAAACCAAATTCCTAGGATGCTAGAGCTAACA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,14292520,14292790,+,['SNV'],[200],['NC_000009.12:14292720:G:A'],['alt'],NaN,GC_Selvarajan
1190,"GC_Selvarajan:ALT_rs10121140|STARR-seq-HepG2,r...",AGGCCAATTCTCTTCCCTGACAGATACAGAAACTGAGTTACTGAGA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,14292585,14292855,+,['SNV'],[135],['NC_000009.12:14292720:G:A'],['alt'],NaN,GC_Selvarajan
1191,GC_Selvarajan:ALT_rs6475604|STARR-seq-HepG2_fw...,AAACTCGTAGAATTTGGCTGACTGCCTGGTTTATCCCAGGACATTA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,22052630,22052900,+,['SNV'],[104],['NC_000009.12:22052734:T:C'],['alt'],NaN,GC_Selvarajan
1192,GC_Selvarajan:ALT_rs1333045|STARR-seq-HepG2_fw...,TTTTTGCTCTGTTACATTAGGAAAGTTATGTAGAATTTTGTGCCTC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,22119060,22119330,+,['SNV'],[135],['NC_000009.12:22119195:T:C'],['alt'],NaN,GC_Selvarajan
1193,GC_Selvarajan:ALT_rs2297400|STARR-seq-HepG2_fw...,AACACAGCCAGTTCCTGGAAGGTCTTGTTCACCTGGAGTCAGGTGG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,104837064,104837334,+,['SNV'],[135],['NC_000009.12:104837199:T:C'],['alt'],NaN,GC_Selvarajan

In [24]:
# add modified Selvarajan
general_controls_with_engreitz_no_selvarajan = general_controls_with_engreitz.loc[~general_controls_with_engreitz['label'].str.contains('GC_Selvarajan')].copy()

general_controls = pd.concat([selvarajan_controls_filtered, general_controls_with_engreitz_no_selvarajan], ignore_index=False)

In [29]:
general_controls['label'].value_counts()

label
GC_Selvarajan                       357
GC_Vista                            256
GC_Mendelian_variants               209
GC_Kircher                          203
GC_Cort_Chengyu                     185
GC_Glut_Chengyu                      83
GC_Atrial_fib                        45
GC_GABA_Chengyu                      42
GC_DNase_positive_shuffled           41
GC_DNase_positive                    41
GC_Mohlke                            38
GC_Engreitz                          20
GC_Liang                             16
GC_DNase_negative_brain              15
GC_DNase_negative_brain_shuffled     15
GC_DNase_negative_blood              15
GC_DNase_negative_blood_shuffled     15
GC_Hon                                6
Name: count, dtype: int64

In [30]:
dnase_negative_brain = general_controls.loc[general_controls['label']== "GC_DNase_negative_brain"]
gc_hon = general_controls.loc[general_controls['label']== "GC_Hon"]

In [ ]:
general_controls[interesting_columns]

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
830,GC_Hon:TBXEnh4_Centered_region|chr12:114025966...,GGGCTCACTGTCCTTGGTGAATGACTTACATCTGAGCTTCTTCCTG...,element,element inactive control,NaN,GRCh38,chr12,114025955,114026225,NaN,NaN,NaN,NaN,NaN,NaN,GC_Hon
831,GC_Hon:TBXEnh2_EH38E1646265|chr12:114335696-11...,TGACACTATCGGCCTGTTGTCTAAAGTACTTACAGTTCTCTCCGGG...,element,element inactive control,NaN,GRCh38,chr12,114335685,114335955,NaN,NaN,NaN,NaN,NaN,NaN,GC_Hon
832,GC_Hon:TBXEnh3_EH38E3042928|chr12:114361591-11...,TTCCAAACACAAGGAGCCCTCCGGCCTGCCTGGCCCTGTGACATTT...,element,element inactive control,NaN,GRCh38,chr12,114361580,114361850,NaN,NaN,NaN,NaN,NaN,NaN,GC_Hon
833,GC_Hon:TBXEnh6_EH38E1646350|chr12:114415524-11...,CTTTTATGATTATTATTTTTACCGACAGCTCCAAGCAGAGGCCTGT...,element,element inactive control,NaN,GRCh38,chr12,114415513,114415783,NaN,NaN,NaN,NaN,NaN,NaN,GC_Hon
834,GC_Hon:TBXEnh6_EH38E3042962|chr12:114415802-11...,GAAATAGCAGGTGCAAGATCCATGCTGGGCACGAACACGGGCAGAA...,element,element inactive control,NaN,GRCh38,chr12,114415791,114416061,NaN,NaN,NaN,NaN,NaN,NaN,GC_Hon
835,GC_Hon:NGFRAP1_Centered_region|chrX:103376085-...,AGAAGGGTAGGAATTCAGGGGCTACGTGGGCATTGATGGCTGTGCA...,element,element inactive control,NaN,GRCh38,chrX,103376074,103376344,NaN,NaN,NaN,NaN,NaN,NaN,GC_Hon

In [28]:
dnase_negative_brain

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CTTTTTTTTCCTCTCTGAACAAATCAATCACTTTAAAAAGGAAGAA...,element,element inactive control,NaN,GRCh38,chr1,4708882,4709152,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
1,GC_DNase_negative_brain:chr10:27823303-2782357...,ATTTTAACAAGCTCTTCATATGGTTTGTATGCACATTAATTTTTGA...,element,element inactive control,NaN,GRCh38,chr10,27534373,27534643,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
2,GC_DNase_negative_brain:chr11:75379056-7537932...,ACCGAGTCCGCGGGGCCGGAGGTGGAGCCGGAGCCCAGGCCCGGGC...,element,element inactive control,NaN,GRCh38,chr11,75668010,75668280,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TTATAAATTTGAAATTATAGGAACTGCTGAGGGGTGATTTTTTTTT...,element,element inactive control,NaN,GRCh38,chr13,34722983,34723253,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTTTGACTGCTTTATTTCTCTCAGATGATATATGCTGGGATTTG...,element,element inactive control,NaN,GRCh38,chr13,66345227,66345497,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
5,GC_DNase_negative_brain:chr13:72716260-7271652...,TATACTGAATCCTATAACTTTCTACCACTGCCATCCTTCTGAGAAA...,element,element inactive control,NaN,GRCh38,chr13,72142121,72142391,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
6,GC_DNase_negative_brain:chr16:6433041-6433310_...,GACATCTGGTGCCCAAGAAGTTTGTTAAGGTTGCCCAGTCACTTGC...,element,element inactive control,NaN,GRCh38,chr16,6383039,6383309,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
7,GC_DNase_negative_brain:chr18:9737546-9737815_...,ACTTATCTGCTACACTAACGAGCAGATGACTGTCCTCCTCTCCTGC...,element,element inactive control,NaN,GRCh38,chr18,9737548,9737818,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
8,GC_DNase_negative_brain:chr18:25690223-2569049...,AACAGTGTCTCCCTACATGGGACCCTCTGTCAGCCACATGCTTTCA...,element,element inactive control,NaN,GRCh38,chr18,28110258,28110528,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
9,GC_DNase_negative_brain:chr20:5892173-5892442_...,AGGCACGCTGGTTTTCCGGGGCCGCTCCATCGCGCCTTCCTCCTGC...,element,element inactive control,NaN,GRCh38,chr20,5911526,5911796,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
10,GC_DNase_negative_brain:chr4:6000102-6000371_a...,TTTTTTAAAAGCTCTTGCTTGCTGCTGGAGAGAGAAACAAATGTGT...,element,element inactive control,NaN,GRCh38,chr4,5998374,5998644,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
11,GC_DNase_negative_brain:chr7:37955027-37955296...,CAAAAATATTCCTAGGTTTCATTTCAAGAAGTGAATTTAAACCTCT...,element,element inactive control,NaN,GRCh38,chr7,37915424,37915694,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
12,GC_DNase_negative_brain:chr7:70038310-70038579...,ACCTGTCTTTCTGAAGAACTCCTCTATTTAGGCCCACTCAAGCAAA...,element,element inactive control,NaN,GRCh38,chr7,70573323,70573593,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
13,GC_DNase_negative_brain:chr7:110448481-1104487...,GCCCTTTATGAATGAATGCAGTCACTAAAAGGCTAATTGTGTCTTC...,element,element inactive control,NaN,GRCh38,chr7,110808424,110808694,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain
14,GC_DNase_negative_brain:chr7:145812901-1458131...,CTGAAGGGGAGGAGAGAAGGAAAGGAGAAGGCATCCGAGCGAGGGT...,element,element inactive control,NaN,GRCh38,chr7,146115808,146116078,+,NaN,NaN,NaN,NaN,NaN,GC_DNase_negative_brain

In [ ]:
general_controls['sequence'].str.len().value_counts()

# 4 268
wrong_length = general_controls.loc[general_controls[col_sequence].str.len() < 270]

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
240,GC_Mendelian_variants:ALT_chr1:209816133C>CA|I...,TTGAGCCCAGGGGCTGAATCTGGAGCTTTGGGGCCTGGGAACCTCT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,209815997,209816267,+,['indel'],[135],['NC_000001.11:209816132:C:CA'],['alt'],NaN,GC_Mendelian_variants
288,GC_Mendelian_variants:ALT_chr7:156791255G>C|SH...,GAGATATGGCTTCATTTTCTGTAATAAACACTAAGATCAAAACATG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791119,156791389,+,['indel'],[154],['NC_000007.14:156791273:T:TTAAGGAAGTGATT'],['alt'],NaN,GC_Mendelian_variants
289,GC_Mendelian_variants:ALT_chr7:156791257G>A|SH...,GATATGGCTTCATTTTCTGTAATAAACACTAAGATCAAAACATGAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791121,156791391,+,['indel'],[152],['NC_000007.14:156791273:T:TTAAGGAAGTGATT'],['alt'],NaN,GC_Mendelian_variants
290,GC_Mendelian_variants:ALT_chr7:156791274T>TTAA...,TGTAATAAACACTAAGATCAAAACATGACCCAAGTTAAATTTCCTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791138,156791408,+,['indel'],[135],['NC_000007.14:156791273:T:TTAAGGAAGTGATT'],['alt'],NaN,GC_Mendelian_variants

In [41]:
general_controls

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
836,GC_Selvarajan:REF_rs216222|STARR-seq-HepG2_fwd...,TGCCTATAGTCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATTGCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr17,2252271,2252541,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
837,GC_Selvarajan:REF_rs754064|STARR-seq-HepG2_fwd...,CTGGTGTTATATTCACCTGACTAAATTTAGAAGGAACTGTGTATCT...,element,element inactive control,general controls IGVF year 1 design 2023,GRCh38,chr20,48798773,48799043,+,NaN,NaN,NaN,NaN,NaN,GC_Selvarajan
839,"GC_Selvarajan:REF_rs9660819|STARR-seq-HepG2,rs...",GGGGATGGTGCGGCCACGTCCAGGAGGCAGAAGCACAGAGAATGTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3036131,3036401,+,"['SNV', 'SNV']","[127, 144]","['NC_000001.11:3036258:C:T', 'NC_000001.11:303...","['ref', 'ref']",NaN,GC_Selvarajan
840,"GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2,rs...",GGGGTTGTGTGGTGTGTGTATCATGGTGTGTGTATATGTACTCTGT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3039882,3040152,+,"['SNV', 'SNV']","[135, 219]","['NC_000001.11:3040017:A:G', 'NC_000001.11:304...","['ref', 'ref']",NaN,GC_Selvarajan
841,"GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2,rs...",CTGTGCATACGGGCTGTGTATATATATGCTGTGTGTATATGTTGCA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,3039924,3040194,+,"['SNV', 'SNV']","[93, 177]","['NC_000001.11:3040017:A:G', 'NC_000001.11:304...","['ref', 'ref']",NaN,GC_Selvarajan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,GC_Engreitz:BUD31_chr7:99408722-99408992,GCGCGCCGCCTAAGTCCAGGCTTGCCCGTCTGCTGCCAGGCAACAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr7,99408722,99408992,+,NaN,NaN,NaN,NaN,NaN,GC_Engreitz
1599,GC_Engreitz:PABPC1_chr8:100722036-100722306,AGCCCGGAGCACACACTCCGCACTCTCAGCACTAACCGCCGGGGAG...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,100722036,100722306,-,NaN,NaN,NaN,NaN,NaN,GC_Engreitz
1600,GC_Engreitz:NDUFB9_chr8:124538931-124539201,CCGGAGGGCGCAATTCCTGGGTCCTGTGACCTTGGTGACCGACGCC...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr8,124538931,124539201,+,NaN,NaN,NaN,NaN,NaN,GC_Engreitz
1601,GC_Engreitz:RPS6_chr9:19380196-19380466,TTGAAGCAGCTGAACGCCTCCGAGGCGCCACGGAAAAGAGGGCCAA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,19380196,19380466,-,NaN,NaN,NaN,NaN,NaN,GC_Engreitz
1602,GC_Engreitz:RPL35_chr9:124861910-124862180,ATTGCTGCACAAGCCGCCAACGCCGCCGCCCGCTCCGAGGGAAAGA...,element,element active control,Engreitz housekeeping promoters,GRCh38,chr9,124861910,124862180,-,NaN,NaN,NaN,NaN,NaN,GC_Engreitz

In [ ]:
group_name = "IGVF_General_MPRA_Controls"
output_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata"
import os
# # Write DataFrame to TSV file
general_controls[interesting_columns].to_csv(os.path.join(output_path, f'{group_name}.metadata.tmp.tsv.gz'), sep='\t', index=False, na_rep='NA', compression='gzip')
os.system(f'zcat {output_path}/{group_name}.metadata.tmp.tsv.gz | sed "s/\'/\\"/g" | gzip -c > {output_path}/{group_name}.metadata.tsv.gz')

0

In [36]:
f'{output_path}/{group_name}.metadata.tsv.gz'

'/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata//IGVF_General_MPRA_Controls.metadata.tsv.gz'

In [38]:
metadata_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata//IGVF_General_MPRA_Controls.metadata.tsv"
metadata_df = pd.read_csv(metadata_path, sep='\t', low_memory=False)

# use safe eval on list
# Apply the safe_eval function to the specified columns
for col in list_columns:
    metadata_df[col] = metadata_df[col].apply(safe_eval)

In [42]:
group_name = "IGVF_General_MPRA_Controls"
# Write DataFrame to TSV file
metadata_df[interesting_columns].to_csv(os.path.join(output_path, f'{group_name}.metadata.tmp.tsv.gz'), sep='\t', index=False, na_rep='NA', compression='gzip')
os.system(f'zcat {output_path}/{group_name}.metadata.tmp.tsv.gz | sed "s/\'/\\"/g" | gzip -c > {output_path}/{group_name}.metadata.tsv.gz')

0

In [43]:
metadata_df.columns

Index(['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info'],
      dtype='object')

In [40]:
metadata_df[col_sequence].str.len().value_counts()

sequence
270    1602
Name: count, dtype: int64

In [ ]:
variant_region_map.merge(only_control_variants_alt[[col_name, col_variant_pos]], )

NameError: name 'variant_region_map' is not defined

In [71]:
only_control_variants[col_start].isna().sum()

NameError: name 'only_control_variants' is not defined

In [73]:
only_control_variants.loc[only_control_variants[col_start].isna()]["label"].value_counts()

Series([], Name: count, dtype: int64)

In [74]:
import pandas as pd

# # Example DataFrame setup
# data = {
#     "name": ["seq1_REF", "seq1_ALT", "seq2_REF", "seq2_ALT"],
#     "chrom": ["chr1", "chr1", "chr1", "chr1"],
#     "start": [100, 100, 200, 200],
#     "end": [110, 110, 210, 210],
#     "sequence": ["ACGTACGTAC", "ACGTTCGTAC", "TGCATGCATG", "TGCGTGCATG"]
# }
# df = pd.DataFrame(data)

# Step 1: Identify REF/ALT pairs by matching genomic positions
pairs = only_control_variants.groupby([col_chr, col_start, col_end])

results = []

# Step 2: Compare REF and ALT sequences
for (chrom, start, end), group in pairs:
    ref_row = group[group["name"].str.contains("REF")]
    alt_row = group[group["name"].str.contains("ALT")]

    if not ref_row.empty and not alt_row.empty:
        ref_name = ref_row["name"].values[0]
        alt_name = alt_row["name"].values[0]
        ref_seq = ref_row["sequence"].values[0]
        alt_seq = alt_row["sequence"].values[0]

        # Step 3: Find the position of the variant (first difference)
        variant_position = next(
            (i for i, (r, a) in enumerate(zip(ref_seq, alt_seq)) if r != a),
            -1
        )

        results.append({
            "chrom": chrom,
            "start": start,
            "end": end,
            "ref_name": ref_name,
            "alt_name": alt_name,
            "ref_seq": ref_seq,
            "alt_seq": alt_seq,
            "variant_position_in_seq": variant_position
        })

# Convert results to a DataFrame
controls_no_mk_variant_table = pd.DataFrame(results)

In [75]:
# generate you own variant region map: from the genomic regions
only_control_variants_alt

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
5,GC_Kircher:ALT_SORT1_chr1:109274659-109274929_...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659.0,109274929.0,+,[SNV],[135],[NC_000001.11:109274794:C:T],[alt],NaN,GC_Kircher
6,GC_Kircher:ALT_SORT1_chr1:109274659-109274929_...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659.0,109274929.0,+,[SNV],[177],[NC_000001.11:109274836:C:T],[alt],NaN,GC_Kircher
7,GC_Kircher:ALT_SORT1_chr1:109274771-109275041_...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771.0,109275041.0,+,[SNV],[65],[NC_000001.11:109274836:C:T],[alt],NaN,GC_Kircher
8,GC_Kircher:ALT_SORT1_chr1:109274659-109274929_...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659.0,109274929.0,+,[SNV],[181],[NC_000001.11:109274840:A:C],[alt],NaN,GC_Kircher
9,GC_Kircher:ALT_SORT1_chr1:109274771-109275041_...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771.0,109275041.0,+,[SNV],[69],[NC_000001.11:109274840:A:C],[alt],NaN,GC_Kircher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80048,GC_Mendelian_variants:ALT_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336.0,156791606.0,+,[SNV],[135],[NC_000007.14:156791471:C:T],[alt],NaN,GC_Mendelian_variants
80049,GC_Mendelian_variants:ALT_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336.0,156791606.0,+,[SNV],[76],[NC_000007.14:156791412:A:C],[alt],NaN,GC_Mendelian_variants
80058,GC_Mohlke:ALT_NC000010.11|100315721|G|A|Mohlke...,TAATAAATATATTACCAGTCTGATTTTCTTTGTAGGGGAAAGGGGG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,100315633.0,100315903.0,+,[SNV],[88],[NC_000010.11:100315721:G:A],[alt],NaN,GC_Mohlke
80062,C_positive_heart_CAD:ALT_rs12721051_rs12721051...,TCCTGCCTCAGCCTCATGAGTACTTGGAACTACAGGTGTGTGACAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr19,44918767.0,44919037.0,+,[SNV],[136],[NC_000019.10:44918902:C:G],[alt],NaN,C_positive_heart_CAD
80070,C_positive_neuron_MK:tile_37243_chr6_97306567_...,TTTTTATTGTACTAATCAGTCTCAAGATGTTCTCTGTGTTAATTGG...,variant,variant positive control,Michael Kosicki,GRCh38,chr6,97306566.0,97306836.0,+,[SNV],[244],[NC_000006.12:97306810:G:C],[alt],NaN,C_positive_neuron_MK

special cases which are alternatives but do not have a reference associated: 
C_positive_heart_MK:tile_6898_chr11_9613179_9613448_G_C_145_0.321328448327018
C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_13_0.56278024959106
C_positive_neuron_CD:p1_rs9975055_T_G_alt_50_G::chr21:44929969-44930239-mean_ratio2.18
C_positive_heart_CAD:ALT_rs12721051_rs12721051;GC_Selvarajan:ALT_rs12721051|STARR-seq-HepG2_fwd_tile1-1_rs12721051 (multiple names for one sequence: we will prepare the variant map first => sequence is the same, so exploding does not make sense)
the others have ALT_ in their header

In [76]:
only_control_variants_alt[col_variant_pos].isna().sum()

0

#### Focus on MK variants (TODO)
- mk has SNVs 
- and other things: 
- e.g. MK:newcore_70553|chr11-57778685+57778954|ts98-104 (insertion of same length)
    - AGTGGGGGAACAGA
    - AGCAAAAAGACAGA
- e.g. MK:tile_985|chr1-33363966+33364235|LC28.22 (insertion of same length)
    - CATGGGGGAGGGGCTT
    - CACAAAAAGAAAATTT

In [77]:
mk_metadata = kircher_corrected_metadata_file.loc[kircher_corrected_metadata_file[col_name].str.startswith('MK')].copy()

Check the different variant types

In [ ]:
# check the different variant types

mk_metadata_regions['header_suffix'] = mk_metadata_regions[col_name].apply(lambda header: header.split("|")[-1])

header_suffix_list = mk_metadata_regions['header_suffix'].to_list()
# variants char - char - number (normal snv)

header_suffix_list_no_ref = [head for head in header_suffix_list if not "ref" in head]

len(header_suffix_list_no_ref) # 1557

# ts containing:
header_suffix_list_ts_containing = [head for head in header_suffix_list_no_ref if "ts" in head]
len(header_suffix_list_ts_containing) # 134
header_suffix_list_no_ref_ts_containing = [head for head in header_suffix_list_no_ref if not "ts" in head]

len(header_suffix_list_no_ref_ts_containing) # 1423


header_suffix_list_no_ref_ts_containing_scramble_negative = [head for head in header_suffix_list_no_ref_ts_containing if not "scramble_negative" in head]
len(header_suffix_list_no_ref_ts_containing_scramble_negative) # 923
header_suffix_list_no_ref_ts_containing_scramble_negative

# LC
header_suffix_list_LC_containing = [head for head in header_suffix_list_no_ref if "LC" in head]
len(header_suffix_list_LC_containing) # 118

header_suffix_list_no_ref_ts_containing_scramble_negative_LC = [head for head in header_suffix_list_no_ref_ts_containing_scramble_negative if not "LC" in head]

header_suffix_list_no_ref_ts_containing_scramble_negative_LC # only snvs in the list anymore # 805 + 118 + 134 = 1057

get mk regions from header and add metadata information

In [6]:
metadata_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MPRA_80215_updated_dnase_sequences.metadata.tsv.gz"
updated_mpra_80k_metadata_df = pd.read_csv(metadata_path, sep='\t', compression='gzip', low_memory=False)

# use safe eval on list
# Apply the safe_eval function to the specified columns
for col in list_columns:
    updated_mpra_80k_metadata_df[col] = updated_mpra_80k_metadata_df[col].apply(safe_eval)

mk_metadata = updated_mpra_80k_metadata_df.loc[updated_mpra_80k_metadata_df['name'].str.startswith("MK:")]

In [7]:
import re
def get_mk_region_from_header(row, name_col="name", chr_col="chr", start_col="start", strand_col="strand", end_col="end"):
    """

    """
    header = row[name_col]
    # Regex to capture the chromosome, start, and end
    pattern = re.compile(r"(chr\w+)-(\d+)([+-])(\d+)")

    match = pattern.search(header)
    if match:
        chrom, start, strand, end = match.groups()
        row[chr_col] = chrom
        row[start_col] = int(start)-1
        row[strand_col] = strand
        row[end_col] = int(end)
    else:
        print(header)
    return row


def add_SNV_or_indel_for_variant_header(row, name_col="name", class_col="class", category_col="category", variant_class_col="variant_class", variant_pos_col="variant_pos", info_col="info"):
    header = row[name_col]
    if not header.startswith("MK"):
        raise ValueError("Function only defined for the MK group")
    pattern_for_SNV = re.compile(r"(\w)-(\w)-(\d+)")
    pattern_for_indel_with_numbers = re.compile(r"ts(\d+)-(\d+)")
    pattern_for_lc_indel = re.compile(r"LC(\d+).(\d)+")
    SNV_match = pattern_for_SNV.search(header)
    indel_with_numbers_match = pattern_for_indel_with_numbers.search(header)
    indel_LC_match = pattern_for_lc_indel.search(header)
    row[category_col] = "element"
    row[class_col] = "element active control"
    if "reference" in header:
        row[category_col] = "element"
        row[class_col] = "element active control"

    elif "scramble_negative" in header:
        row[category_col] = "scrambled"
        row[class_col] = "element inactive control"

    elif SNV_match:
        row[category_col] = "variant"
        row[class_col] = "variant positive control"
        REF, ALT, variant_pos_one_based = SNV_match.groups()
        row[variant_class_col] = "SNV"
        row[variant_pos_col] = int(variant_pos_one_based) - 1 # from 1-based to 0-based

    elif indel_with_numbers_match:
        row[category_col] = "variant"
        row[class_col] = "variant positive control"
        start, end = indel_with_numbers_match.groups()
        row[variant_class_col] = "indel"
        row[variant_pos_col] = int(start) - 1
        row[info_col] = "for start and end (1-based) of the variant see header"

    elif indel_LC_match:
        row[category_col] = "variant"
        row[class_col] = "variant positive control"
        row[variant_class_col] = "indel"
        row[variant_pos_col] = pd.NA
        row[info_col] = "The meaning of LC was not known while generating this file"



    else:
        print(header)
        raise ValueError("Unexprected Sequence this function expected LC containing ts containing or SNVs")
    return row

def correct_MK_metadata(row):
    """
    Correct MK metadata:
    - category treat everything as element except the ones which contain scramble in the header => scrambled
    - set all as element active control except the ones which contain scramble => element inactive control
    - get the regions from the header (start -1) and strand from inbetween
    """
    pass

In [8]:
mk_metadata_regions = mk_metadata.apply(lambda row: get_mk_region_from_header(row, name_col=col_name, chr_col=col_chr, start_col=col_start, strand_col=col_strand, end_col=col_end), axis=1).copy()
mk_metadata_regions = mk_metadata_regions.apply(lambda row: add_SNV_or_indel_for_variant_header(row, name_col=col_name, class_col=col_class, category_col=col_category, variant_class_col=col_variant_class, variant_pos_col=col_variant_pos, info_col=col_info), axis=1).copy()

In [9]:
mk_metadata_regions

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info
0,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,element,element active control,Michael Kosicki,GRCh38,chr8,10365155,10365425,+,"[SNV, SNV, SNV, SNV, SNV, SNV, indel, indel, i...","[20, 252, 20, 252, 36, 36, 17, 249, 33]",None,"[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN
1,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,element,element active control,Michael Kosicki,GRCh38,chr20,20492858,20493129,+,[SNV],[40],None,[ref],NaN
2,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,element,element active control,Michael Kosicki,GRCh38,chr22,42282877,42283148,+,[SNV],[172],None,[ref],NaN
3,MK:tile_38401|chr7-1226231+1226500|reference,AAAACTATTAGACGACAGGCGGATGTGCTACTAAAACTCTTGGTTA...,element,element active control,Michael Kosicki,GRCh38,chr7,1226230,1226500,+,"[SNV, SNV, SNV, SNV, indel, indel]","[84, 84, 248, 248, 245, 81]",None,"[ref, ref, ref, ref, ref, ref]",NaN
4,MK:tile_47638|chr16-52435608+52435878|reference,AAAAGCCACCCCAGCTCTCCACTTTCCCATCCGATTCTAGTAGGTC...,element,element active control,Michael Kosicki,GRCh38,chr16,52435607,52435878,+,[SNV],[0],None,[ref],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,MK:tile_2240|chr1-116244322+116244591|scramble...,CTTAATCAAATAACCCATTAATTCTATATATCTACCTAATATTAAT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr1,116244321,116244591,+,None,None,None,None,NaN
2393,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,CATCGGCCCTGGTGAAGCGTCCGTCCAGACGGGCCTGCCTAGCCTC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr11,2374616,2374886,+,None,None,None,None,NaN
2394,MK:tile_18415|chr17-71181691+71181960|scramble...,TAAATATTCAGCGATACATTCCTATTCTTTTTCAGAAGTAGTTATT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr17,71181690,71181960,+,None,None,None,None,NaN
2395,MK:tile_14356|chr15-67031618+67031887|scramble...,TGAAGCCCCTGATTCTGTTAGAATAAGGTTACTGAGTCGTGTATAC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr15,67031617,67031887,+,None,None,None,None,NaN
2396,MK:tile_22033|chr2-71506006+71506275|scramble_...,GGGGGAGAAATTGGACAGGCACGCCTTGCTCATGTGTGTGGGGACT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr2,71506005,71506275,+,None,None,None,None,NaN

In [10]:
# need for variant map: to get the variant information to the respective reference

# Get the variant table for MK

# Step 1: Identify REF/ALT pairs by matching genomic positions
pairs = mk_metadata_regions.groupby([col_chr, col_start, col_end])

results = []

# Step 2: Compare REF and all ALT sequences
for (chrom, start, end), group in pairs:
    # Get the reference row
    ref_row = group[group["name"].str.contains("reference")]
    # Get all alternative rows (not labeled "reference")
    alt_rows = group[~group["name"].str.contains("reference")]

    # Ensure we have a reference row
    if not ref_row.empty and not alt_rows.empty:
        ref_name = ref_row["name"].values[0]
        ref_seq = ref_row["sequence"].values[0]

        # Loop over each alternative row
        for _, alt_row in alt_rows.iterrows():
            alt_name = alt_row["name"]
            alt_seq = alt_row["sequence"]

            # Step 3: Find the position of the variant (first difference)
            variant_position = next(
                (i for i, (r, a) in enumerate(zip(ref_seq, alt_seq)) if r != a),
                pd.NA
            )

            # Append each REF-ALT combination as a separate row
            results.append({
                "chrom": chrom,
                "start": start,
                "end": end,
                "REF": ref_name,
                "ALT": alt_name,
                "ref_seq": ref_seq,
                "alt_seq": alt_seq,
                "variant_position_in_seq": variant_position
            })
# Convert results to a DataFrame
controls_mk_variant_map = pd.DataFrame(results)

In [11]:
controls_mk_variant_map

,chrom,start,end,REF,ALT,ref_seq,alt_seq,variant_position_in_seq
0,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.21,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTATCTTTTCTTTTTACCTGCTC...,26
1,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.22,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,146
2,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.23,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTTCTTATTTTCCGCTCCCCTCCCCCACCTGCTC...,14
3,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.24,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,206
4,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.25,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,50
...,...,...,...,...,...,...,...,...
782,chrX,24999633,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|T-A-31,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTCTTAGATGAGGGAATTAGC...,30
783,chrX,24999633,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|ts28-34,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTTCCCAGCGAGGGAATTAGC...,27
784,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-A-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTACTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
785,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-C-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTCCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
786,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|ts1-7,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,CCCATCACGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,0

In [17]:
mk_variant_map_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MK_variant_map.tsv.gz"

controls_mk_variant_map.to_csv(mk_variant_map_path, sep="\t", index=False)

In [12]:
# expected number of variants:
mk_variants = mk_metadata_regions.loc[mk_metadata_regions[col_category] == "variant"].copy() # 1,057
mk_variants

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info
242,MK:newcore_110746|chr13-80235318+80235587|G-A-21,GCTTCTAGTCATAGACAATGACAATTGCAGAGCAAGACTAATAACA...,variant,variant positive control,Michael Kosicki,GRCh38,chr13,80235317,80235587,+,SNV,20,None,[alt],NaN
243,MK:newcore_110746|chr13-80235318+80235587|G-C-21,GCTTCTAGTCATAGACAATGCCAATTGCAGAGCAAGACTAATAACA...,variant,variant positive control,Michael Kosicki,GRCh38,chr13,80235317,80235587,+,SNV,20,None,[alt],NaN
244,MK:newcore_110746|chr13-80235318+80235587|T-A-197,GCTTCTAGTCATAGACAATGGCAATTGCAGAGCAAGACTAATAACA...,variant,variant positive control,Michael Kosicki,GRCh38,chr13,80235317,80235587,+,SNV,196,None,[alt],NaN
245,MK:newcore_110746|chr13-80235318+80235587|T-A-265,GCTTCTAGTCATAGACAATGGCAATTGCAGAGCAAGACTAATAACA...,variant,variant positive control,Michael Kosicki,GRCh38,chr13,80235317,80235587,+,SNV,264,None,[alt],NaN
246,MK:newcore_110746|chr13-80235318+80235587|T-A-9,GCTTCTAGACATAGACAATGGCAATTGCAGAGCAAGACTAATAACA...,variant,variant positive control,Michael Kosicki,GRCh38,chr13,80235317,80235587,+,SNV,8,None,[alt],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294,MK:tile_9894|chr12-94535162+94535431|A-T-113,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,SNV,112,None,[alt],NaN
1295,MK:tile_9894|chr12-94535162+94535431|G-A-105,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,SNV,104,None,[alt],NaN
1296,MK:tile_9894|chr12-94535162+94535431|G-C-105,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,SNV,104,None,[alt],NaN
1297,MK:tile_9894|chr12-94535162+94535431|ts102-108,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,indel,101,None,[alt],for start and end (1-based) of the variant see...
1298,MK:tile_9894|chr12-94535162+94535431|ts110-116,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,indel,109,None,[alt],for start and end (1-based) of the variant see...

In [13]:
# get all variant pos because of value error if not
variant_pos_alternative_dict = controls_mk_variant_map[["ALT", "variant_position_in_seq"]].set_index("ALT").to_dict()["variant_position_in_seq"]
variant_pos_alternative_dict

def add_variant_position_for_sequences_with_unknown_variant_position(row, col_name, col_variant_pos):
    name = row[col_name]
    if isinstance(row[col_variant_pos], int):
        return row
    if name in list(variant_pos_alternative_dict.keys()):
        row[col_variant_pos] = int(variant_pos_alternative_dict[name])
    return row

In [14]:
mk_metadata_regions = mk_metadata_regions.apply(lambda row: add_variant_position_for_sequences_with_unknown_variant_position(row, col_name=col_name, col_variant_pos=col_variant_pos),axis=1)

In [15]:
mk_metadata_regions

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info
0,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,element,element active control,Michael Kosicki,GRCh38,chr8,10365155,10365425,+,"[SNV, SNV, SNV, SNV, SNV, SNV, indel, indel, i...","[20, 252, 20, 252, 36, 36, 17, 249, 33]",None,"[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN
1,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,element,element active control,Michael Kosicki,GRCh38,chr20,20492858,20493129,+,[SNV],[40],None,[ref],NaN
2,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,element,element active control,Michael Kosicki,GRCh38,chr22,42282877,42283148,+,[SNV],[172],None,[ref],NaN
3,MK:tile_38401|chr7-1226231+1226500|reference,AAAACTATTAGACGACAGGCGGATGTGCTACTAAAACTCTTGGTTA...,element,element active control,Michael Kosicki,GRCh38,chr7,1226230,1226500,+,"[SNV, SNV, SNV, SNV, indel, indel]","[84, 84, 248, 248, 245, 81]",None,"[ref, ref, ref, ref, ref, ref]",NaN
4,MK:tile_47638|chr16-52435608+52435878|reference,AAAAGCCACCCCAGCTCTCCACTTTCCCATCCGATTCTAGTAGGTC...,element,element active control,Michael Kosicki,GRCh38,chr16,52435607,52435878,+,[SNV],[0],None,[ref],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,MK:tile_2240|chr1-116244322+116244591|scramble...,CTTAATCAAATAACCCATTAATTCTATATATCTACCTAATATTAAT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr1,116244321,116244591,+,None,None,None,None,NaN
2393,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,CATCGGCCCTGGTGAAGCGTCCGTCCAGACGGGCCTGCCTAGCCTC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr11,2374616,2374886,+,None,None,None,None,NaN
2394,MK:tile_18415|chr17-71181691+71181960|scramble...,TAAATATTCAGCGATACATTCCTATTCTTTTTCAGAAGTAGTTATT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr17,71181690,71181960,+,None,None,None,None,NaN
2395,MK:tile_14356|chr15-67031618+67031887|scramble...,TGAAGCCCCTGATTCTGTTAGAATAAGGTTACTGAGTCGTGTATAC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr15,67031617,67031887,+,None,None,None,None,NaN
2396,MK:tile_22033|chr2-71506006+71506275|scramble_...,GGGGGAGAAATTGGACAGGCACGCCTTGCTCATGTGTGTGGGGACT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr2,71506005,71506275,+,None,None,None,None,NaN

In [16]:
controls_mk_variant_map["REF"].nunique() # 242
controls_mk_variant_map["ALT"].nunique() # 787
controls_mk_variant_map

,chrom,start,end,REF,ALT,ref_seq,alt_seq,variant_position_in_seq
0,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.21,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTATCTTTTCTTTTTACCTGCTC...,26
1,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.22,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,146
2,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.23,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTTCTTATTTTCCGCTCCCCTCCCCCACCTGCTC...,14
3,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.24,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,206
4,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.25,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,50
...,...,...,...,...,...,...,...,...
782,chrX,24999633,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|T-A-31,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTCTTAGATGAGGGAATTAGC...,30
783,chrX,24999633,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|ts28-34,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTTCCCAGCGAGGGAATTAGC...,27
784,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-A-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTACTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
785,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-C-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTCCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
786,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|ts1-7,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,CCCATCACGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,0

In [88]:
controls_mk_variant_map['variant_position_in_seq'].isna().sum()

0

In [89]:
# what is the expected number of variants (1,057 alternative sequences)
controls_mk_variant_map # 787

,chrom,start,end,REF,ALT,ref_seq,alt_seq,variant_position_in_seq
0,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.21,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTATCTTTTCTTTTTACCTGCTC...,26
1,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.22,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,146
2,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.23,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTTCTTATTTTCCGCTCCCCTCCCCCACCTGCTC...,14
3,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.24,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,206
4,chr1,33363965,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.25,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,50
...,...,...,...,...,...,...,...,...
782,chrX,24999633,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|T-A-31,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTCTTAGATGAGGGAATTAGC...,30
783,chrX,24999633,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|ts28-34,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTTCCCAGCGAGGGAATTAGC...,27
784,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-A-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTACTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
785,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-C-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTCCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
786,chrX,82534379,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|ts1-7,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,CCCATCACGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,0

In [90]:
mk_metadata_regions

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
77621,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,element,element active control,Michael Kosicki,GRCh38,chr8,10365155,10365425,+,None,NaN,None,None,NaN,MK
77622,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,element,element active control,Michael Kosicki,GRCh38,chr20,20492858,20493129,+,None,NaN,None,None,NaN,MK
77623,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,element,element active control,Michael Kosicki,GRCh38,chr22,42282877,42283148,+,None,NaN,None,None,NaN,MK
77624,MK:CENPE|chr4-103198452-103198721|reference,AAAAATACATGTATCTCTACCTAGTTTCGTCTACAGGTTCCAAACT...,element,element active control,Michael Kosicki,GRCh38,chr4,103198451,103198721,-,None,NaN,None,None,NaN,MK
77625,MK:tile_45386|chr9-33290305+33290574|reference,AAAACCACAATGATTACGCAAGTCGCCGCCCTCCCTCCTGCGATTG...,element,element active control,Michael Kosicki,GRCh38,chr9,33290304,33290574,+,None,NaN,None,None,NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80013,MK:tile_2240|chr1-116244322+116244591|scramble...,CTTAATCAAATAACCCATTAATTCTATATATCTACCTAATATTAAT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr1,116244321,116244591,+,None,NaN,None,None,NaN,MK
80014,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,CATCGGCCCTGGTGAAGCGTCCGTCCAGACGGGCCTGCCTAGCCTC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr11,2374616,2374886,+,None,NaN,None,None,NaN,MK
80015,MK:tile_18415|chr17-71181691+71181960|scramble...,TAAATATTCAGCGATACATTCCTATTCTTTTTCAGAAGTAGTTATT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr17,71181690,71181960,+,None,NaN,None,None,NaN,MK
80016,MK:tile_14356|chr15-67031618+67031887|scramble...,TGAAGCCCCTGATTCTGTTAGAATAAGGTTACTGAGTCGTGTATAC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr15,67031617,67031887,+,None,NaN,None,None,NaN,MK
80017,MK:tile_22033|chr2-71506006+71506275|scramble_...,GGGGGAGAAATTGGACAGGCACGCCTTGCTCATGTGTGTGGGGACT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr2,71506005,71506275,+,None,NaN,None,None,NaN,MK

In [91]:
# add alt/ref for all the sequences in the variant map
alt_list = controls_mk_variant_map['ALT'].to_list()
ref_list = list(set(controls_mk_variant_map["REF"].to_list()))

def add_alt_ref_to_metadata_mk(row, col_name, col_allele, col_category):
    name = row[col_name]
    if name in alt_list:
        row[col_allele] = "alt"
        row[col_category] = "variant"
    elif name in ref_list:
        row[col_allele] = "ref"
        row[col_category] = "variant"
    else:
        row[col_allele] = pd.NA
    return row


mk_metadata_regions = mk_metadata_regions.apply(lambda row: add_alt_ref_to_metadata_mk(row, col_name=col_name, col_allele=col_allele, col_category=col_category), axis=1)

In [92]:
variant_metadata_mk = mk_metadata_regions.loc[mk_metadata_regions[col_category] == "variant"].copy() # 1,057 (only alt) 1,299  with ref

# make dict for REF: [list of ALT_IDs associated to this REF] from the variant_map_filtered
ref_alt_dict = controls_mk_variant_map.groupby('REF')['ALT'].apply(list).to_dict()
ref_alt_dict

# # make dict for ALT_ID to variant_pos from the metadata table
alt_variant_pos_dict = variant_metadata_mk[[col_name, col_variant_pos]].set_index(col_name).to_dict()[col_variant_pos]
alt_variant_pos_dict
# # make dict for ALT_ID to variant_class from the metadata table
alt_variant_class_dict = variant_metadata_mk[[col_name, col_variant_class]].set_index(col_name).to_dict()[col_variant_class]
alt_variant_class_dict

# function to add a list of SPDI values from the REF to the metadata table
def add_alt_info_values_2_reference(row):
    if row[col_name] in ref_list:
        # check if row[col_name] is in ref_alt_dict
        if not row[col_name] in ref_alt_dict:
            # raise exception
            raise ValueError('Reference ID not found in ref_alt_dict')
        # NOTE: within variant_pos: for reference sequences a array of variant positions need to be added
        row[col_variant_pos] = [int(alt_variant_pos_dict[alt_id]) for alt_id in ref_alt_dict[row[col_name]]]
        row[col_variant_class] = [alt_variant_class_dict[alt_id] for alt_id in ref_alt_dict[row[col_name]]]
        row[col_allele] = ['ref' for _ in ref_alt_dict[row[col_name]]]
        row[col_category] = "variant"
    return row

variant_metadata_mk = variant_metadata_mk.apply(add_alt_info_values_2_reference, axis=1)

In [93]:
# function to generate arrays out off the columns
def make_column_arrays(row):
    """
    create arrays for the required columns
    """
    allele = row[col_allele]
    SPDI = row[col_SPDI]
    variant_pos = row[col_variant_pos]
    variant_class = row[col_variant_class]

    if isinstance(allele, str): # only "alt" is string
        row[col_allele] = [allele]
    if isinstance(SPDI, str): # only for alt sequences this is true
        if SPDI != "NA":
            row[col_SPDI] = [SPDI]
    if isinstance(variant_pos, float):
        row[col_variant_pos] = [int(variant_pos)]
    elif isinstance(variant_pos, int):
        row[col_variant_pos] = [int(variant_pos)]
    if isinstance(variant_class, str):
        if row[col_variant_class] in ['SNV', 'indel']:
                row[col_variant_class] = [variant_class]
    if not isinstance(row[col_class], str):
        print(row[col_name])
    return row

In [94]:
variant_metadata_mk = variant_metadata_mk.apply(make_column_arrays, axis=1)

In [95]:
variant_metadata_mk # 1299
# e.g.: missing allele: MK:tile_10173|chr12-113932852+113933122|A-G-100 => not found in variant table (many variants but no reference designed)

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
77621,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,element active control,Michael Kosicki,GRCh38,chr8,10365155,10365425,+,"[SNV, SNV, SNV, SNV, SNV, SNV, indel, indel, i...","[20, 252, 20, 252, 36, 36, 17, 249, 33]",None,"[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN,MK
77622,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,element active control,Michael Kosicki,GRCh38,chr20,20492858,20493129,+,[SNV],[40],None,[ref],NaN,MK
77623,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,element active control,Michael Kosicki,GRCh38,chr22,42282877,42283148,+,[SNV],[172],None,[ref],NaN,MK
77627,MK:tile_38401|chr7-1226231+1226500|reference,AAAACTATTAGACGACAGGCGGATGTGCTACTAAAACTCTTGGTTA...,variant,element active control,Michael Kosicki,GRCh38,chr7,1226230,1226500,+,"[SNV, SNV, SNV, SNV, indel, indel]","[84, 84, 248, 248, 245, 81]",None,"[ref, ref, ref, ref, ref, ref]",NaN,MK
77629,MK:tile_47638|chr16-52435608+52435878|reference,AAAAGCCACCCCAGCTCTCCACTTTCCCATCCGATTCTAGTAGGTC...,variant,element active control,Michael Kosicki,GRCh38,chr16,52435607,52435878,+,[SNV],[0],None,[ref],NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79513,MK:tile_9894|chr12-94535162+94535431|A-T-113,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,[SNV],[112],None,[alt],NaN,MK
79514,MK:tile_9894|chr12-94535162+94535431|G-A-105,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,[SNV],[104],None,[alt],NaN,MK
79515,MK:tile_9894|chr12-94535162+94535431|G-C-105,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,[SNV],[104],None,[alt],NaN,MK
79516,MK:tile_9894|chr12-94535162+94535431|ts102-108,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,[indel],[101],None,[alt],for start and end (1-based) of the variant see...,MK
79517,MK:tile_9894|chr12-94535162+94535431|ts110-116,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant positive control,Michael Kosicki,GRCh38,chr12,94535161,94535431,+,[indel],[109],None,[alt],for start and end (1-based) of the variant see...,MK

##### Focus on elements

In [96]:
# finished the variant specific investigation => next element specific
mk_metadata_regions_elements = mk_metadata_regions.loc[~(mk_metadata_regions[col_category] == "variant")].copy() # 1,057 (only alt) 1,299  with ref

Sanity check if the regions are correct

In [ ]:

mk_metadata_regions_elements[[col_chr, col_start, col_end, col_name, col_info, col_strand]].to_csv("MK_element_region.bed", sep="\t", index=False, header=None)

# write to bed with strandedness and use getfasta to get the sequences: are the sequences the same


# bedtools getfasta -fi /home/kisa/coding/80K_MPRA/reference_genome_match/hg38.fa -bed /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MK_element_region.bed -s -fo /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MK_element_region_hg38.fa -nameOnly

In [ ]:
mk_metadata_regions_elements

In [ ]:
mk_elements_fa = hf.fasta_to_dataframe("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MK_element_region_hg38.fa", columns=['bed_name', 'sequence'])
mk_elements_fa['sequence'] = mk_elements_fa['sequence'].str.upper()

mk_elements_fa.merge(mk_metadata_regions_elements, on="sequence", how="inner") # 598 => there are differences in the sequences (scrambled sequences)

,bed_name,sequence,name,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,MK:CENPE|chr4-103198452-103198721|reference(-),AAAAATACATGTATCTCTACCTAGTTTCGTCTACAGGTTCCAAACT...,MK:CENPE|chr4-103198452-103198721|reference,element,element active control,Michael Kosicki,GRCh38,chr4,103198451,103198721,-,None,NaN,None,<NA>,NaN,MK
1,MK:tile_45386|chr9-33290305+33290574|reference(+),AAAACCACAATGATTACGCAAGTCGCCGCCCTCCCTCCTGCGATTG...,MK:tile_45386|chr9-33290305+33290574|reference,element,element active control,Michael Kosicki,GRCh38,chr9,33290304,33290574,+,None,NaN,None,<NA>,NaN,MK
2,MK:newcore_325721|chr6-30614846+30615115|refer...,AAAACTAGAACTACACAGAGATGGACAGCCTTGATACTTAATTCCT...,MK:newcore_325721|chr6-30614846+30615115|refer...,element,element active control,Michael Kosicki,GRCh38,chr6,30614845,30615115,+,None,NaN,None,<NA>,NaN,MK
3,MK:EID2|chr19-39540234-39540503|reference(-),AAAAGACCATGAATCTAAAATATCTTGATATATAATAGAGGTGGCA...,MK:EID2|chr19-39540234-39540503|reference,element,element active control,Michael Kosicki,GRCh38,chr19,39540233,39540503,-,None,NaN,None,<NA>,NaN,MK
4,MK:tile_21037|chr2-41840760+41841029|reference(+),AAAAGGCTTTCCTCTCCAGGAGCCTGGCAAGCCAAGCCCGCCCTCT...,MK:tile_21037|chr2-41840760+41841029|reference,element,element active control,Michael Kosicki,GRCh38,chr2,41840759,41841029,+,None,NaN,None,<NA>,NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,MK:ZNF717|chr3-75785590-75785859|reference(-),TTTTCACAATGTGCCAGGCTGTGAAACCAGGATTTAATAAAGAACC...,MK:ZNF717|chr3-75785590-75785859|reference,element,element active control,Michael Kosicki,GRCh38,chr3,75785589,75785859,-,None,NaN,None,<NA>,NaN,MK
594,MK:newcore_375317|chr8-80727518+80727787|refer...,TTTTGCAAGAGTTCGCCTTCGGGTTTTAAATAATTCATCATGCAGT...,MK:newcore_375317|chr8-80727518+80727787|refer...,element,element active control,Michael Kosicki,GRCh38,chr8,80727517,80727787,+,None,NaN,None,<NA>,NaN,MK
595,MK:tile_18181|chr17-58659383+58659652|referenc...,TTTTTAGGCATCGCTTCGAAACTACCGCTTCTTCGTATGACACATC...,MK:tile_18181|chr17-58659383+58659652|reference,element,element active control,Michael Kosicki,GRCh38,chr17,58659382,58659652,+,None,NaN,None,<NA>,NaN,MK
596,MK:newcore_229767|chr20-22686062+22686331|refe...,TTTTTCTCGTTTCATGAGTAGTTGATAATTCAGCAAAGGTTTCTTA...,MK:newcore_229767|chr20-22686062+22686331|refe...,element,element active control,Michael Kosicki,GRCh38,chr20,22686061,22686331,+,None,NaN,None,<NA>,NaN,MK
597,MK:ZNF493|chr19-21396827+21397096|reference(+),TTTTTTAAATTTGTGAATAGCCATATATTATTTATAAGTGCTTATG...,MK:ZNF493|chr19-21396827+21397096|reference,element,element active control,Michael Kosicki,GRCh38,chr19,21396826,21397096,+,None,NaN,None,<NA>,NaN,MK

In [97]:
mk_elements_fa = hf.fasta_to_dataframe("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MK_element_region_hg38.fa", columns=['name', 'bed_sequence'])
mk_elements_fa['bed_sequence'] = mk_elements_fa['bed_sequence'].str.upper()

mk_elements_fa["name"] = mk_elements_fa["name"].apply(lambda name: name.split("(")[0])
mk_elements_fa

,name,bed_sequence
0,MK:CENPE|chr4-103198452-103198721|reference,AAAAATACATGTATCTCTACCTAGTTTCGTCTACAGGTTCCAAACT...
1,MK:tile_45386|chr9-33290305+33290574|reference,AAAACCACAATGATTACGCAAGTCGCCGCCCTCCCTCCTGCGATTG...
2,MK:newcore_325721|chr6-30614846+30615115|refer...,AAAACTAGAACTACACAGAGATGGACAGCCTTGATACTTAATTCCT...
3,MK:EID2|chr19-39540234-39540503|reference,AAAAGACCATGAATCTAAAATATCTTGATATATAATAGAGGTGGCA...
4,MK:tile_21037|chr2-41840760+41841029|reference,AAAAGGCTTTCCTCTCCAGGAGCCTGGCAAGCCAAGCCCGCCCTCT...
...,...,...
1093,MK:tile_2240|chr1-116244322+116244591|scramble...,GAAATTCTACCTTGTTGCTTCTCTTATTAGTAGCTATCTGCTTTCT...
1094,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,TGCCCTTCCTCAACGTGCCTCCGGCTGTGCCCACATCGCTCCAGCA...
1095,MK:tile_18415|chr17-71181691+71181960|scramble...,CAGTGCTATTTAACTCTTTAAAAGTGAGTCTGAATTCTTAAGTACC...
1096,MK:tile_14356|chr15-67031618+67031887|scramble...,TATTCTAAGACAAAAAACTATGACCTCTCCAGGGGAAACAATGAGG...
1097,MK:tile_22033|chr2-71506006+71506275|scramble_...,GCTCAGGGCCACAGCTACCCTCTGCCTGCTTCTGGAGGTTGTCTGA...

In [98]:
hg38_designed_seq_mk = mk_elements_fa.merge(mk_metadata_regions_elements, on="name", how="inner").copy()

In [99]:
def check_sequences(row, col_name, col_sequence, col_bed_sequence):
    designed_seq = row[col_sequence]
    hg38_seq = row[col_bed_sequence]
    if designed_seq != hg38_seq:
        print(row[col_name])



hg38_designed_seq_mk.apply(lambda row: check_sequences(row, col_name=col_name, col_sequence=col_sequence, col_bed_sequence="bed_sequence"), axis=1)

MK:tile_35551|chr5-173255689+173255958|scramble_negative
MK:tile_3346|chr1-204293262+204293531|scramble_negative
MK:tile_45208|chr9-22087668+22087937|scramble_negative
MK:tile_23759|chr2-197868362+197868631|scramble_negative
MK:tile_20126|chr19-10889768+10890037|scramble_negative
MK:tile_33101|chr5-33059101+33059370|scramble_negative
MK:tile_15196|chr15-92916822+92917091|scramble_negative
MK:tile_13505|chr15-51402681+51402950|scramble_negative
MK:tile_42191|chr7-102841734+102842003|scramble_negative
MK:tile_40626|chr7-42337421+42337690|scramble_negative
MK:tile_9944|chr12-98489717+98489986|scramble_negative
MK:tile_7027|chr11-12892224+12892493|scramble_negative
MK:tile_27788|chr3-37769210+37769479|scramble_negative
MK:tile_8254|chr11-86898452+86898721|scramble_negative
MK:tile_12110|chr14-61245826+61246095|scramble_negative
MK:tile_15683|chr16-31722164+31722433|scramble_negative
MK:tile_46252|chr9-103781929+103782198|scramble_negative
MK:tile_196|chr1-3421601+3421870|scramble_negative
MK:tile_45972|chr9-88814004+88814273|scramble_negative
MK:tile_31117|chr4-52959085+52959354|scramble_negative
MK:tile_42764|chr7-150969403+150969672|scramble_negative
MK:tile_34162|chr5-103018334+103018603|scramble_negative
MK:tile_16110|chr16-53779738+53780007|scramble_negative
MK:tile_41248|chr7-42694130+42694399|scramble_negative
MK:tile_19382|chr18-47413233+47413502|scramble_negative
MK:tile_38157|chr6-156952530+156952799|scramble_negative
MK:tile_16607|chr16-72701247+72701516|scramble_negative
MK:tile_25672|chr20-40857220+40857489|scramble_negative
MK:tile_29088|chr3-124587664+124587933|scramble_negative
MK:tile_24489|chr2-219750473+219750742|scramble_negative
MK:tile_39698|chr7-42052977+42053246|scramble_negative
MK:tile_46259|chr9-103783583+103783852|scramble_negative
MK:tile_45326|chr9-22126491+22126760|scramble_negative
MK:tile_3035|chr1-172180134+172180403|scramble_negative
MK:tile_2216|chr1-115792365+115792634|scramble_negative
MK:tile_36280|chr6-20842498+20842767|scramble_negative
MK:tile_34927|chr5-149443874+149444143|scramble_negative
MK:tile_30975|chr4-10319028+10319297|scramble_negative
MK:tile_12423|chr14-73181768+73182037|scramble_negative
MK:tile_40411|chr7-42245927+42246196|scramble_negative
MK:tile_15752|chr16-50814444+50814713|scramble_negative
MK:tile_41261|chr7-42697288+42697557|scramble_negative
MK:tile_17005|chr16-86867109+86867378|scramble_negative
MK:tile_21607|chr2-59996926+59997195|scramble_negative
MK:tile_24956|chr2-236687761+236688030|scramble_negative
MK:tile_12516|chr14-76013288+76013557|scramble_negative
MK:tile_17309|chr17-12488518+12488787|scramble_negative
MK:tile_17108|chr16-89332625+89332894|scramble_negative
MK:tile_46071|chr9-93864476+93864745|scramble_negative
MK:tile_41118|chr7-42615384+42615653|scramble_negative
MK:tile_5335|chr10-78220122+78220391|scramble_negative
MK:tile_34578|chr5-135019819+135020088|scramble_negative
MK:tile_26463|chr21-34446297+34446566|scramble_negative
MK:tile_25609|chr20-40607139+40607408|scramble_negative
MK:tile_30970|chr4-10317867+10318136|scramble_negative
MK:tile_22041|chr2-71613682+71613951|scramble_negative
MK:tile_2361|chr1-117661500+117661769|scramble_negative
MK:tile_39726|chr7-42059697+42059966|scramble_negative
MK:tile_32512|chr4-173683638+173683907|scramble_negative
MK:tile_41155|chr7-42624950+42625219|scramble_negative
MK:tile_8346|chr11-113022656+113022925|scramble_negative
MK:tile_29996|chr3-157914484+157914753|scramble_negative
MK:tile_40409|chr7-42245461+42245730|scramble_negative
MK:tile_36769|chr6-43794271+43794540|scramble_negative
MK:tile_24635|chr2-221102823+221103092|scramble_negative
MK:tile_40689|chr7-42391546+42391815|scramble_negative
MK:tile_28101|chr3-48151916+48152185|scramble_negative
MK:tile_16543|chr16-69849464+69849733|scramble_negative
MK:tile_45190|chr9-22081705+22081974|scramble_negative
MK:tile_32351|chr4-173485595+173485864|scramble_negative
MK:tile_35654|chr5-175321800+175322069|scramble_negative
MK:tile_11158|chr13-105132202+105132471|scramble_negative
MK:tile_41980|chr7-93249400+93249669|scramble_negative
MK:tile_15875|chr16-51699434+51699703|scramble_negative
MK:tile_39711|chr7-42056097+42056366|scramble_negative
MK:tile_28182|chr3-52038956+52039225|scramble_negative
MK:tile_37720|chr6-118377313+118377582|scramble_negative
MK:tile_35502|chr5-173194887+173195156|scramble_negative
MK:tile_43430|chr8-32206632+32206901|scramble_negative
MK:tile_41978|chr7-93248930+93249199|scramble_negative
MK:tile_28078|chr3-48146403+48146672|scramble_negative
MK:tile_36063|chr6-15510393+15510662|scramble_negative
MK:tile_17807|chr17-44547435+44547704|scramble_negative
MK:tile_43463|chr8-33803157+33803426|scramble_negative
MK:tile_36170|chr6-17716081+17716350|scramble_negative
MK:tile_33630|chr5-86385579+86385848|scramble_negative
MK:tile_1623|chr1-60937550+60937819|scramble_negative
MK:tile_45045|chr9-13315233+13315502|scramble_negative
MK:tile_40698|chr7-42393701+42393970|scramble_negative
MK:tile_40550|chr7-42280536+42280805|scramble_negative
MK:tile_25948|chr20-50393335+50393604|scramble_negative
MK:tile_37804|chr6-125583410+125583679|scramble_negative
MK:tile_25652|chr20-40833360+40833629|scramble_negative
MK:tile_41398|chr7-42768297+42768566|scramble_negative
MK:tile_24631|chr2-219968314+219968583|scramble_negative
MK:tile_16536|chr16-69821598+69821867|scramble_negative
MK:tile_35749|chr6-3249417+3249686|scramble_negative
MK:tile_21534|chr2-59534386+59534655|scramble_negative
MK:tile_3833|chr1-223100301+223100570|scramble_negative
MK:tile_46268|chr9-103785711+103785980|scramble_negative
MK:tile_45306|chr9-22121495+22121764|scramble_negative
MK:tile_14360|chr15-67032572+67032841|scramble_negative
MK:tile_38299|chr6-163747624+163747893|scramble_negative
MK:tile_28109|chr3-48153834+48154103|scramble_negative
MK:tile_16324|chr16-55206883+55207152|scramble_negative
MK:tile_7173|chr11-16875626+16875895|scramble_negative
MK:tile_5768|chr10-100791925+100792194|scramble_negative
MK:tile_21585|chr2-59828493+59828762|scramble_negative
MK:tile_14337|chr15-67027087+67027356|scramble_negative
MK:tile_20844|chr2-19378414+19378683|scramble_negative
MK:tile_16620|chr16-72801035+72801304|scramble_negative
MK:tile_39716|chr7-42057297+42057566|scramble_negative
MK:tile_6641|chr11-2011875+2012144|scramble_negative
MK:tile_25832|chr20-48156151+48156420|scramble_negative
MK:tile_46260|chr9-103783820+103784089|scramble_negative
MK:tile_34165|chr5-103019026+103019295|scramble_negative
MK:tile_42129|chr7-98613036+98613305|scramble_negative
MK:tile_37551|chr6-105304192+105304461|scramble_negative
MK:tile_16123|chr16-53782684+53782953|scramble_negative
MK:tile_44782|chr8-128928329+128928598|scramble_negative
MK:tile_17763|chr17-41738896+41739165|scramble_negative
MK:tile_39274|chr7-41933506+41933775|scramble_negative
MK:tile_37008|chr6-56875022+56875291|scramble_negative
MK:tile_40225|chr7-42184027+42184296|scramble_negative
MK:tile_5652|chr10-93080122+93080391|scramble_negative
MK:tile_36920|chr6-51329700+51329969|scramble_negative
MK:tile_25670|chr20-40856744+40857013|scramble_negative
MK:tile_17762|chr17-41738668+41738937|scramble_negative
MK:tile_26141|chr20-57161568+57161837|scramble_negative
MK:tile_12575|chr14-76931268+76931537|scramble_negative
MK:tile_26332|chr21-18442017+18442286|scramble_negative
MK:tile_43867|chr8-67982287+67982556|scramble_negative
MK:tile_5646|chr10-93078742+93079011|scramble_negative
MK:tile_40171|chr7-42166904+42167173|scramble_negative
MK:tile_40161|chr7-42164519+42164788|scramble_negative
MK:tile_45968|chr9-88813062+88813331|scramble_negative
MK:tile_30962|chr4-10316009+10316278|scramble_negative
MK:tile_35492|chr5-173192543+173192812|scramble_negative
MK:tile_3551|chr1-210727306+210727575|scramble_negative
MK:tile_39286|chr7-41936310+41936579|scramble_negative
MK:tile_28317|chr3-61808217+61808486|scramble_negative
MK:tile_4991|chr10-72892470+72892739|scramble_negative
MK:tile_26461|chr21-34445847+34446116|scramble_negative
MK:tile_41111|chr7-42613709+42613978|scramble_negative
MK:tile_14910|chr15-78826455+78826724|scramble_negative
MK:tile_34397|chr5-124514336+124514605|scramble_negative
MK:tile_41247|chr7-42693906+42694175|scramble_negative
MK:tile_27800|chr3-37772037+37772306|scramble_negative
MK:tile_9860|chr12-91676908+91677177|scramble_negative
MK:tile_3197|chr1-201354239+201354508|scramble_negative
MK:tile_41109|chr7-42613230+42613499|scramble_negative
MK:tile_41153|chr7-42624481+42624750|scramble_negative
MK:tile_4942|chr10-72256097+72256366|scramble_negative
MK:tile_14354|chr15-67031141+67031410|scramble_negative
MK:tile_1805|chr1-81262972+81263241|scramble_negative
MK:tile_40414|chr7-42246625+42246894|scramble_negative
MK:tile_6720|chr11-2592512+2592781|scramble_negative
MK:tile_41227|chr7-42677353+42677622|scramble_negative
MK:tile_35590|chr5-173279513+173279782|scramble_negative
MK:tile_44511|chr8-108668829+108669098|scramble_negative
MK:tile_28103|chr3-48152396+48152665|scramble_negative
MK:tile_37704|chr6-118372927+118373196|scramble_negative
MK:tile_34891|chr5-143043312+143043581|scramble_negative
MK:tile_29870|chr3-157788547+157788816|scramble_negative
MK:tile_40660|chr7-42345704+42345973|scramble_negative
MK:tile_3203|chr1-201355632+201355901|scramble_negative
MK:tile_28885|chr3-113149977+113150246|scramble_negative
MK:tile_32135|chr4-147495171+147495440|scramble_negative
MK:tile_16828|chr16-78900288+78900557|scramble_negative
MK:tile_12580|chr14-76932443+76932712|scramble_negative
MK:tile_15334|chr15-98732815+98733084|scramble_negative
MK:tile_6310|chr10-123953520+123953789|scramble_negative
MK:tile_45158|chr9-22074122+22074391|scramble_negative
MK:tile_35493|chr5-173192777+173193046|scramble_negative
MK:tile_30286|chr3-171293263+171293532|scramble_negative
MK:tile_45170|chr9-22076966+22077235|scramble_negative
MK:tile_32971|chr5-3924729+3924998|scramble_negative
MK:tile_19871|chr18-78311565+78311834|scramble_negative
MK:tile_8012|chr11-68327783+68328052|scramble_negative
MK:tile_19861|chr18-78304036+78304305|scramble_negative
MK:tile_42061|chr7-95872255+95872524|scramble_negative
MK:tile_16853|chr16-79936906+79937175|scramble_negative
MK:tile_27846|chr3-38563003+38563272|scramble_negative
MK:tile_39907|chr7-42103136+42103405|scramble_negative
MK:tile_2078|chr1-94087771+94088040|scramble_negative
MK:tile_2079|chr1-94088001+94088270|scramble_negative
MK:tile_41381|chr7-42754958+42755227|scramble_negative
MK:tile_5611|chr10-92450668+92450937|scramble_negative
MK:tile_36765|chr6-43793441+43793710|scramble_negative
MK:tile_36064|chr6-15510615+15510884|scramble_negative
MK:tile_36800|chr6-44551121+44551390|scramble_negative
MK:tile_42765|chr7-150969639+150969908|scramble_negative
MK:tile_47410|chrX-83512544+83512813|scramble_negative
MK:tile_27290|chr22-39291595+39291864|scramble_negative
MK:tile_30527|chr3-186406052+186406321|scramble_negative
MK:tile_14923|chr15-78861533+78861802|scramble_negative
MK:tile_36983|chr6-56869056+56869325|scramble_negative
MK:tile_19500|chr18-51497336+51497605|scramble_negative
MK:tile_30303|chr3-171297208+171297477|scramble_negative
MK:tile_14892|chr15-77752938+77753207|scramble_negative
MK:tile_26599|chr21-40638068+40638337|scramble_negative
MK:tile_20128|chr19-10890242+10890511|scramble_negative
MK:tile_3950|chr1-230147357+230147626|scramble_negative
MK:tile_2098|chr1-94130418+94130687|scramble_negative
MK:tile_2256|chr1-116248148+116248417|scramble_negative
MK:tile_25696|chr20-40947061+40947330|scramble_negative
MK:tile_34379|chr5-124164034+124164303|scramble_negative
MK:tile_39693|chr7-42051777+42052046|scramble_negative
MK:tile_6819|chr11-8254519+8254788|scramble_negative
MK:tile_7314|chr11-19219506+19219775|scramble_negative
MK:tile_41019|chr7-42515983+42516252|scramble_negative
MK:tile_26342|chr21-28282996+28283265|scramble_negative
MK:tile_20124|chr19-10889294+10889563|scramble_negative
MK:tile_5648|chr10-93079202+93079471|scramble_negative
MK:tile_28884|chr3-113149748+113150017|scramble_negative
MK:tile_28121|chr3-48156711+48156980|scramble_negative
MK:tile_38306|chr6-163749268+163749537|scramble_negative
MK:tile_42009|chr7-94376201+94376470|scramble_negative
MK:tile_39043|chr7-30672227+30672496|scramble_negative
MK:tile_36159|chr6-17538486+17538755|scramble_negative
MK:tile_10128|chr12-111211746+111212015|scramble_negative
MK:tile_41299|chr7-42707396+42707665|scramble_negative
MK:tile_36919|chr6-51329469+51329738|scramble_negative
MK:tile_28323|chr3-61809606+61809875|scramble_negative
MK:tile_39661|chr7-42044097+42044366|scramble_negative
MK:tile_20830|chr2-16567001+16567270|scramble_negative
MK:tile_15984|chr16-52707150+52707419|scramble_negative
MK:tile_37010|chr6-56875500+56875769|scramble_negative
MK:tile_22762|chr2-120806285+120806554|scramble_negative
MK:tile_14913|chr15-78859147+78859416|scramble_negative
MK:tile_45966|chr9-88812591+88812860|scramble_negative
MK:tile_29518|chr3-148370143+148370412|scramble_negative
MK:tile_41305|chr7-42708814+42709083|scramble_negative
MK:tile_597|chr1-18146812+18147081|scramble_negative
MK:tile_8437|chr11-116962988+116963257|scramble_negative
MK:tile_19345|chr18-47404354+47404623|scramble_negative
MK:tile_17462|chr17-17989109+17989378|scramble_negative
MK:tile_24030|chr2-212163570+212163839|scramble_negative
MK:tile_2466|chr1-119974473+119974742|scramble_negative
MK:tile_24624|chr2-219966645+219966914|scramble_negative
MK:tile_41352|chr7-42728533+42728802|scramble_negative
MK:tile_36172|chr6-17931749+17932018|scramble_negative
MK:tile_14922|chr15-78861294+78861563|scramble_negative
MK:tile_33022|chr5-9283604+9283873|scramble_negative
MK:tile_14844|chr15-73385437+73385706|scramble_negative
MK:tile_41558|chr7-45562977+45563246|scramble_negative
MK:tile_45500|chr9-68810243+68810512|scramble_negative
MK:tile_30972|chr4-10318332+10318601|scramble_negative
MK:tile_8229|chr11-86046946+86047215|scramble_negative
MK:tile_17305|chr17-12487581+12487850|scramble_negative
MK:tile_19893|chr18-78757730+78757999|scramble_negative
MK:tile_19379|chr18-47412513+47412782|scramble_negative
MK:tile_39727|chr7-42059937+42060206|scramble_negative
MK:tile_35491|chr5-173192308+173192577|scramble_negative
MK:tile_19501|chr18-51497564+51497833|scramble_negative
MK:tile_28882|chr3-113149290+113149559|scramble_negative
MK:tile_37123|chr6-85187311+85187580|scramble_negative
MK:tile_32739|chr4-185137927+185138196|scramble_negative
MK:tile_41284|chr7-42703852+42704121|scramble_negative
MK:tile_2268|chr1-116251018+116251287|scramble_negative
MK:tile_14904|chr15-78825025+78825294|scramble_negative
MK:tile_15636|chr16-22673692+22673961|scramble_negative
MK:tile_45334|chr9-22128356+22128625|scramble_negative
MK:tile_12515|chr14-76013058+76013327|scramble_negative
MK:tile_40555|chr7-42281728+42281997|scramble_negative
MK:tile_3811|chr1-223095060+223095329|scramble_negative
MK:tile_11141|chr13-105128123+105128392|scramble_negative
MK:tile_40704|chr7-42395137+42395406|scramble_negative
MK:tile_8683|chr11-126411886+126412155|scramble_negative
MK:tile_4992|chr10-72892701+72892970|scramble_negative
MK:tile_43428|chr8-32206171+32206440|scramble_negative
MK:tile_19439|chr18-48073831+48074100|scramble_negative
MK:tile_10420|chr12-123066909+123067178|scramble_negative
MK:tile_31696|chr4-110996184+110996453|scramble_negative
MK:tile_16997|chr16-86865331+86865600|scramble_negative
MK:tile_28883|chr3-113149519+113149788|scramble_negative
MK:tile_3792|chr1-223090533+223090802|scramble_negative
MK:tile_39268|chr7-41932104+41932373|scramble_negative
MK:tile_13487|chr15-48633342+48633611|scramble_negative
MK:tile_37073|chr6-85077480+85077749|scramble_negative
MK:tile_41219|chr7-42675452+42675721|scramble_negative
MK:tile_2427|chr1-119006145+119006414|scramble_negative
MK:tile_8352|chr11-113023961+113024230|scramble_negative
MK:tile_28555|chr3-71205593+71205862|scramble_negative
MK:tile_29149|chr3-127371790+127372059|scramble_negative
MK:tile_13440|chr15-44187915+44188184|scramble_negative
MK:tile_24951|chr2-236620257+236620526|scramble_negative
MK:tile_35506|chr5-173195824+173196093|scramble_negative
MK:tile_31952|chr4-139561276+139561545|scramble_negative
MK:tile_41101|chr7-42607523+42607792|scramble_negative
MK:tile_21105|chr2-42907636+42907905|scramble_negative
MK:tile_14716|chr15-67786945+67787214|scramble_negative
MK:tile_42552|chr7-120899996+120900265|scramble_negative
MK:tile_20945|chr2-28312959+28313228|scramble_negative
MK:tile_1047|chr1-38163114+38163383|scramble_negative
MK:tile_14357|chr15-67031857+67032126|scramble_negative
MK:tile_41052|chr7-42571850+42572119|scramble_negative
MK:tile_14739|chr15-67884984+67885253|scramble_negative
MK:tile_21912|chr2-67188738+67189007|scramble_negative
MK:tile_16458|chr16-61102041+61102310|scramble_negative
MK:tile_25949|chr20-50393572+50393841|scramble_negative
MK:tile_40916|chr7-42481803+42482072|scramble_negative
MK:tile_32911|chr5-3164701+3164970|scramble_negative
MK:tile_7235|chr11-17806144+17806413|scramble_negative
MK:tile_41157|chr7-42625418+42625687|scramble_negative
MK:tile_38156|chr6-156952300+156952569|scramble_negative
MK:tile_15983|chr16-52706914+52707183|scramble_negative
MK:tile_41194|chr7-42648765+42649034|scramble_negative
MK:tile_45035|chr9-8737401+8737670|scramble_negative
MK:tile_39929|chr7-42108416+42108685|scramble_negative
MK:tile_39288|chr7-41936778+41937047|scramble_negative
MK:tile_42876|chr7-151713978+151714247|scramble_negative
MK:tile_16547|chr16-69850389+69850658|scramble_negative
MK:tile_39683|chr7-42049377+42049646|scramble_negative
MK:tile_37698|chr6-118371565+118371834|scramble_negative
MK:tile_16107|chr16-53777233+53777502|scramble_negative
MK:tile_22875|chr2-137454942+137455211|scramble_negative
MK:tile_39961|chr7-42116096+42116365|scramble_negative
MK:tile_45312|chr9-22122918+22123187|scramble_negative
MK:tile_25947|chr20-50393098+50393367|scramble_negative
MK:tile_16457|chr16-61101829+61102098|scramble_negative
MK:tile_16115|chr16-53780871+53781140|scramble_negative
MK:tile_41197|chr7-42649484+42649753|scramble_negative
MK:tile_11208|chr13-105971358+105971627|scramble_negative
MK:tile_24496|chr2-219752081+219752350|scramble_negative
MK:tile_43865|chr8-67981809+67982078|scramble_negative
MK:tile_40806|chr7-42454827+42455096|scramble_negative
MK:tile_40703|chr7-42394898+42395167|scramble_negative
MK:tile_5769|chr10-100792135+100792404|scramble_negative
MK:tile_40247|chr7-42189279+42189548|scramble_negative
MK:tile_10316|chr12-114449376+114449645|scramble_negative
MK:tile_36910|chr6-51327390+51327659|scramble_negative
MK:tile_46909|chr9-129863470+129863739|scramble_negative
MK:tile_41373|chr7-42753088+42753357|scramble_negative
MK:tile_28706|chr3-78989395+78989664|scramble_negative
MK:tile_17129|chr16-89337578+89337847|scramble_negative
MK:tile_1595|chr1-59637424+59637693|scramble_negative
MK:tile_28627|chr3-71940405+71940674|scramble_negative
MK:tile_22638|chr2-108635931+108636200|scramble_negative
MK:tile_4075|chr1-232619340+232619609|scramble_negative
MK:tile_37697|chr6-118371338+118371607|scramble_negative
MK:tile_30304|chr3-171297440+171297709|scramble_negative
MK:tile_12506|chr14-76010986+76011255|scramble_negative
MK:tile_14906|chr15-78825502+78825771|scramble_negative
MK:tile_4624|chr10-30813258+30813527|scramble_negative
MK:tile_1594|chr1-59637188+59637457|scramble_negative
MK:tile_41460|chr7-42838169+42838438|scramble_negative
MK:tile_27086|chr22-35588722+35588991|scramble_negative
MK:tile_33628|chr5-86385113+86385382|scramble_negative
MK:tile_18132|chr17-57474315+57474584|scramble_negative
MK:tile_15936|chr16-52403195+52403464|scramble_negative
MK:tile_30307|chr3-171305106+171305375|scramble_negative
MK:tile_7823|chr11-61259740+61260009|scramble_negative
MK:tile_45368|chr9-30936453+30936722|scramble_negative
MK:tile_5613|chr10-92451146+92451415|scramble_negative
MK:tile_16723|chr16-73799883+73800152|scramble_negative
MK:tile_19008|chr18-24578692+24578961|scramble_negative
MK:tile_19544|chr18-55305817+55306086|scramble_negative
MK:tile_9859|chr12-91676679+91676948|scramble_negative

0       None
1       None
2       None
3       None
4       None
        ...
1093    None
1094    None
1095    None
1096    None
1097    None
Length: 1098, dtype: object

In [100]:
mk_metadata_regions[col_category].value_counts()

category
variant      1299
element       598
scrambled     500
Name: count, dtype: int64

##### Combine element and variants and add to the metadata file

In [102]:
variant_metadata_mk.columns

Index(['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info', 'label'],
      dtype='object')

In [104]:
mk_metadata_regions_elements.columns

Index(['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info', 'label'],
      dtype='object')

In [105]:
mk_element_variant_metadata = pd.concat([variant_metadata_mk, mk_metadata_regions_elements], ignore_index=True)

In [106]:
mk_element_variant_metadata

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,element active control,Michael Kosicki,GRCh38,chr8,10365155,10365425,+,"[SNV, SNV, SNV, SNV, SNV, SNV, indel, indel, i...","[20, 252, 20, 252, 36, 36, 17, 249, 33]",None,"[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN,MK
1,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,element active control,Michael Kosicki,GRCh38,chr20,20492858,20493129,+,[SNV],[40],None,[ref],NaN,MK
2,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,element active control,Michael Kosicki,GRCh38,chr22,42282877,42283148,+,[SNV],[172],None,[ref],NaN,MK
3,MK:tile_38401|chr7-1226231+1226500|reference,AAAACTATTAGACGACAGGCGGATGTGCTACTAAAACTCTTGGTTA...,variant,element active control,Michael Kosicki,GRCh38,chr7,1226230,1226500,+,"[SNV, SNV, SNV, SNV, indel, indel]","[84, 84, 248, 248, 245, 81]",None,"[ref, ref, ref, ref, ref, ref]",NaN,MK
4,MK:tile_47638|chr16-52435608+52435878|reference,AAAAGCCACCCCAGCTCTCCACTTTCCCATCCGATTCTAGTAGGTC...,variant,element active control,Michael Kosicki,GRCh38,chr16,52435607,52435878,+,[SNV],[0],None,[ref],NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,MK:tile_2240|chr1-116244322+116244591|scramble...,CTTAATCAAATAACCCATTAATTCTATATATCTACCTAATATTAAT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr1,116244321,116244591,+,None,NaN,None,NaN,NaN,MK
2393,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,CATCGGCCCTGGTGAAGCGTCCGTCCAGACGGGCCTGCCTAGCCTC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr11,2374616,2374886,+,None,NaN,None,NaN,NaN,MK
2394,MK:tile_18415|chr17-71181691+71181960|scramble...,TAAATATTCAGCGATACATTCCTATTCTTTTTCAGAAGTAGTTATT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr17,71181690,71181960,+,None,NaN,None,NaN,NaN,MK
2395,MK:tile_14356|chr15-67031618+67031887|scramble...,TGAAGCCCCTGATTCTGTTAGAATAAGGTTACTGAGTCGTGTATAC...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr15,67031617,67031887,+,None,NaN,None,NaN,NaN,MK
2396,MK:tile_22033|chr2-71506006+71506275|scramble_...,GGGGGAGAAATTGGACAGGCACGCCTTGCTCATGTGTGTGGGGACT...,scrambled,element inactive control,Michael Kosicki,GRCh38,chr2,71506005,71506275,+,None,NaN,None,NaN,NaN,MK

In [107]:
kircher_corrected_metadata_file.loc[kircher_corrected_metadata_file["label"] == "MK"].shape[0]

2397

In [109]:
metadata_df_no_mk = kircher_corrected_metadata_file.loc[kircher_corrected_metadata_file["label"] != "MK"]
metadata_df_no_mk

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,GC_Kircher:REF_SORT1_chr1:109274659-109274929_...,AAAGCCCTGTCCGGTGAGGGGGCAGAAGGACTCAGCGCCCCTGGAC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274659.0,109274929.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[135, 177, 181, 186, 187, 193, 198, 201, 206, ...","[NC_000001.11:109274794:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
1,GC_Kircher:REF_SORT1_chr1:109274771-109275041_...,AGCCCCTCTCCTTTTCCTGGACTCTGGCCGTGCGCGGCAGCCCAGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274771.0,109275041.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[65, 69, 74, 75, 81, 86, 89, 94, 98, 113, 114,...","[NC_000001.11:109274836:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
2,GC_Kircher:REF_SORT1_chr1:109274882-109275152_...,CAGTCATGTGTTAAGTTGCGCTTCTTTGCTGTGATGTGGGTGGGGG...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274882.0,109275152.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 28, 30, 35, 40, 41, 42, 43, 44, 45, 46, 4...","[NC_000001.11:109274908:T:G, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
3,GC_Kircher:REF_SORT1_chr1:109274993-109275263_...,TCTGGGTTCTGGTGTCCACTCACCCACCCCACCCCCCAAAATCAGA...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109274993.0,109275263.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[26, 27, 28, 29, 32, 33, 34, 43, 45, 46, 47, 4...","[NC_000001.11:109275019:C:T, NC_000001.11:1092...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Kircher
4,GC_Kircher:REF_SORT1_chr1:109275105-109275375_...,ATTGGCTCTCTTCTTCAAAGGACCAGGTCCTGTTCCTCTTTCTCCC...,variant,variant positive control,general controls IGVF year 1 design 2023,GRCh38,chr1,109275105.0,109275375.0,+,"[SNV, SNV, SNV, SNV]","[62, 66, 74, 135]","[NC_000001.11:109275167:C:T, NC_000001.11:1092...","[ref, ref, ref, ref]",NaN,GC_Kircher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80191,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element active control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN,GC_Glut_Chengyu
80192,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element active control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN,GC_Glut_Chengyu
80193,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element active control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN,GC_Glut_Chengyu
80194,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element active control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN,GC_Glut_Chengyu
80195,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element active control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN,GC_Glut_Chengyu

In [110]:
mk_corrected_metadata_file = pd.concat([mk_element_variant_metadata, metadata_df_no_mk], ignore_index=True)
mk_corrected_metadata_file

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
0,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,element active control,Michael Kosicki,GRCh38,chr8,10365155.0,10365425.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, indel, indel, i...","[20, 252, 20, 252, 36, 36, 17, 249, 33]",None,"[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN,MK
1,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,element active control,Michael Kosicki,GRCh38,chr20,20492858.0,20493129.0,+,[SNV],[40],None,[ref],NaN,MK
2,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,element active control,Michael Kosicki,GRCh38,chr22,42282877.0,42283148.0,+,[SNV],[172],None,[ref],NaN,MK
3,MK:tile_38401|chr7-1226231+1226500|reference,AAAACTATTAGACGACAGGCGGATGTGCTACTAAAACTCTTGGTTA...,variant,element active control,Michael Kosicki,GRCh38,chr7,1226230.0,1226500.0,+,"[SNV, SNV, SNV, SNV, indel, indel]","[84, 84, 248, 248, 245, 81]",None,"[ref, ref, ref, ref, ref, ref]",NaN,MK
4,MK:tile_47638|chr16-52435608+52435878|reference,AAAAGCCACCCCAGCTCTCCACTTTCCCATCCGATTCTAGTAGGTC...,variant,element active control,Michael Kosicki,GRCh38,chr16,52435607.0,52435878.0,+,[SNV],[0],None,[ref],NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80191,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element active control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN,GC_Glut_Chengyu
80192,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element active control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN,GC_Glut_Chengyu
80193,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element active control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN,GC_Glut_Chengyu
80194,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element active control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN,GC_Glut_Chengyu
80195,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element active control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN,GC_Glut_Chengyu

In [114]:
mk_corrected_metadata_file['start'].isna().sum()

9

In [ ]:
mk_corrected_metadata_file

In [117]:
import os
interesting_columns = [col_name, col_sequence, col_category, col_class, col_source, col_ref, col_chr, col_start, col_end, col_strand, col_variant_class, col_variant_pos, col_SPDI, col_allele, col_info]

In [118]:
output_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/"
group_name = "MPRA_80215"
# Write DataFrame to TSV file
mk_corrected_metadata_file[interesting_columns].to_csv(os.path.join(output_path, f'{group_name}.metadata.tmp.tsv.gz'), sep='\t', index=False, na_rep='NA', compression='gzip')
os.system(f'zcat {output_path}/{group_name}.metadata.tmp.tsv.gz | sed "s/\'/\\"/g" | gzip -c > {output_path}/{group_name}.metadata.tsv.gz')

0

In [119]:
print("Saved the metadata file to: ", f'{output_path}/{group_name}.metadata.tsv.gz')

Saved the metadata file to:  /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata//MPRA_80215.metadata.tsv.gz

In [ ]:
# remove dnase controls from metadata and add the new dnase controls
metadata_df_no_kircher = dnase_corrected_metadata_file.loc[~dnase_corrected_metadata_file['label'].str.contains("GC_Kircher")]

kircher_corrected_metadata_file = pd.concat([general_kircher_final, metadata_df_no_kircher], ignore_index=True)

In [ ]:
header_suffix_list_LC_containing

['LC18.1',
 'LC18.10',
 'LC18.11',
 'LC18.12',
 'LC18.13',
 'LC18.14',
 'LC18.15',
 'LC18.16',
 'LC18.17',
 'LC18.18',
 'LC18.19',
 'LC18.2',
 'LC18.20',
 'LC18.21',
 'LC18.3',
 'LC18.35',
 'LC18.36',
 'LC18.4',
 'LC18.5',
 'LC18.6',
 'LC18.7',
 'LC18.8',
 'LC18.9',
 'LC18t1',
 'LC18t10',
 'LC18t11',
 'LC18t12',
 'LC18t13',
 'LC18t14',
 'LC18t15',
 'LC18t16',
 'LC18t17',
 'LC18t18',
 'LC18t19',
 'LC18t2',
 'LC18t20',
 'LC18t21',
 'LC18t22',
 'LC18t23',
 'LC18t3',
 'LC18t4',
 'LC18t5',
 'LC18t6',
 'LC18t7',
 'LC18t8',
 'LC18t9',
 'LC16.1',
 'LC16.10',
 'LC16.11',
 'LC16.12',
 'LC16.13',
 'LC16.15',
 'LC16.16',
 'LC16.18',
 'LC16.19',
 'LC16.2',
 'LC16.20',
 'LC16.21',
 'LC16.22',
 'LC16.23',
 'LC16.24',
 'LC16.3',
 'LC16.4',
 'LC16.47',
 'LC16.5',
 'LC16.6',
 'LC16.7',
 'LC16.8',
 'LC16.9',
 'LC16t1',
 'LC16t10',
 'LC16t11',
 'LC16t12',
 'LC16t13',
 'LC16t14',
 'LC16t15',
 'LC16t16',
 'LC16t17',
 'LC16t18',
 'LC16t19',
 'LC16t2',
 'LC16t20',
 'LC16t21',
 'LC16t22',
 'LC16t23',
 'LC16t3',
 'LC16t4',
 'LC16t5',
 'LC16t6',
 'LC16t7',
 'LC16t8',
 'LC16t9',
 'LC28.21',
 'LC28.22',
 'LC28.23',
 'LC28.24',
 'LC28.25',
 'LC28.26',
 'LC28t1',
 'LC28t10',
 'LC28t11',
 'LC28t12',
 'LC28t13',
 'LC28t14',
 'LC28t15',
 'LC28t16',
 'LC28t17',
 'LC28t18',
 'LC28t19',
 'LC28t2',
 'LC28t20',
 'LC28t3',
 'LC28t4',
 'LC28t5',
 'LC28t6',
 'LC28t7',
 'LC28t8',
 'LC28t9']

In [ ]:
len(header_suffix_list_no_ref_ts_containing_scramble_negative_LC)

805

In [ ]:
mk_sorted_regions = mk_metadata_regions.sort_values(by=[col_chr, col_start, col_end])

In [ ]:
mk_sorted_regions

In [ ]:
mk_metadata_regions

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
77621,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,element active control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77622,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,element active control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77623,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,element active control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77624,MK:CENPE|chr4-103198452-103198721|reference,AAAAATACATGTATCTCTACCTAGTTTCGTCTACAGGTTCCAAACT...,variant,element active control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77625,MK:tile_45386|chr9-33290305+33290574|reference,AAAACCACAATGATTACGCAAGTCGCCGCCCTCCCTCCTGCGATTG...,variant,element active control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80013,MK:tile_2240|chr1-116244322+116244591|scramble...,CTTAATCAAATAACCCATTAATTCTATATATCTACCTAATATTAAT...,scrambled,element inactive control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
80014,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,CATCGGCCCTGGTGAAGCGTCCGTCCAGACGGGCCTGCCTAGCCTC...,scrambled,element inactive control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
80015,MK:tile_18415|chr17-71181691+71181960|scramble...,TAAATATTCAGCGATACATTCCTATTCTTTTTCAGAAGTAGTTATT...,scrambled,element inactive control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
80016,MK:tile_14356|chr15-67031618+67031887|scramble...,TGAAGCCCCTGATTCTGTTAGAATAAGGTTACTGAGTCGTGTATAC...,scrambled,element inactive control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
80017,MK:tile_22033|chr2-71506006+71506275|scramble_...,GGGGGAGAAATTGGACAGGCACGCCTTGCTCATGTGTGTGGGGACT...,scrambled,element inactive control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK

,chrom,start,end,ref_name,alt_name,ref_seq,alt_seq,variant_position_in_seq
0,1,33363966,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.21,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTATCTTTTCTTTTTACCTGCTC...,26
1,1,33363966,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.22,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,146
2,1,33363966,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.23,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTTCTTATTTTCCGCTCCCCTCCCCCACCTGCTC...,14
3,1,33363966,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.24,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,206
4,1,33363966,33364235,MK:tile_985|chr1-33363966+33364235|reference,MK:tile_985|chr1-33363966+33364235|LC28.25,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,TCTTAGGCTCTGTTCTCCGCCCCTTACTCCCCTCCCCCACCTGCTC...,50
...,...,...,...,...,...,...,...,...
782,X,24999634,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|T-A-31,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTCTTAGATGAGGGAATTAGC...,30
783,X,24999634,24999903,MK:tile_47231|chrX-24999634+24999903|reference,MK:tile_47231|chrX-24999634+24999903|ts28-34,GTTGAGCAAAGCAGCAGACAAGGCATTCTTTGATGAGGGAATTAGC...,GTTGAGCAAAGCAGCAGACAAGGCATTTCCCAGCGAGGGAATTAGC...,27
784,X,82534380,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-A-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTACTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
785,X,82534380,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|G-C-4,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,TTTCCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,3
786,X,82534380,82534649,MK:tile_47392|chrX-82534380+82534649|reference,MK:tile_47392|chrX-82534380+82534649|ts1-7,TTTGCTGCGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,CCCATCACGTTGAGGGACAGCACCTTTGTGTGTTTGACCCCTAGCA...,0

### Focus on Mendelian variants:
-

In [126]:
mendelian_variants_metadata = mk_corrected_metadata_file.loc[mk_corrected_metadata_file[col_name].str.contains("Mendelian")].copy()

# start end => int
mendelian_variants_metadata[col_start] = mendelian_variants_metadata[col_start].astype(int)
mendelian_variants_metadata[col_end] = mendelian_variants_metadata[col_end].astype(int)

mendelian_variants_metadata

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
4229,GC_Mendelian_variants:REF_chr1:21564170G>A|ALPL,CCCCAGGGAAATCTGTGGGCATTGTGACCACCACGAGAGTGAACCA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,21564034,21564304,+,[SNV],[135],[NC_000001.11:21564169:G:A],[ref],NaN,GC_Mendelian_variants
4230,GC_Mendelian_variants:REF_chr1:209816133C>CA|IRF6,TTGAGCCCAGGGGCTGAATCTGGAGCTTTGGGGCCTGGGAACCTCT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,209815997,209816267,+,[indel],[135],[NC_000001.11:209816132:C:CA],[ref],NaN,GC_Mendelian_variants
4231,GC_Mendelian_variants:REF_chr10:23219376A>C|PTF1A,ATTTGGGTTTCTCCTGTGTTTCAGATACTGATGTTTGAGCTTTCTC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219240,23219510,+,"[SNV, SNV, SNV]","[135, 193, 195]","[NC_000010.11:23219375:A:C, NC_000010.11:23219...","[ref, ref, ref]",NaN,GC_Mendelian_variants
4232,GC_Mendelian_variants:REF_chr10:23219434A>G|PTF1A,CACTTAAAGAGTCACTGTTACTTTGAGGTTTTATCTGTAAGATTCG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219298,23219568,+,"[SNV, SNV, SNV, SNV, SNV]","[77, 135, 137, 209, 218]","[NC_000010.11:23219375:A:C, NC_000010.11:23219...","[ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants
4233,GC_Mendelian_variants:REF_chr10:23219436A>G|PTF1A,CTTAAAGAGTCACTGTTACTTTGAGGTTTTATCTGTAAGATTCGTG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219300,23219570,+,"[SNV, SNV, SNV, SNV, SNV]","[75, 133, 135, 207, 216]","[NC_000010.11:23219375:A:C, NC_000010.11:23219...","[ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80045,GC_Mendelian_variants:ALT_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336,156791606,+,[SNV],[210],[NC_000007.14:156791546:A:G],[alt],NaN,GC_Mendelian_variants
80046,GC_Mendelian_variants:ALT_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336,156791606,+,[SNV],[205],[NC_000007.14:156791541:A:C],[alt],NaN,GC_Mendelian_variants
80047,GC_Mendelian_variants:ALT_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336,156791606,+,[SNV],[135],[NC_000007.14:156791471:C:G],[alt],NaN,GC_Mendelian_variants
80048,GC_Mendelian_variants:ALT_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336,156791606,+,[SNV],[135],[NC_000007.14:156791471:C:T],[alt],NaN,GC_Mendelian_variants
80049,GC_Mendelian_variants:ALT_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336,156791606,+,[SNV],[76],[NC_000007.14:156791412:A:C],[alt],NaN,GC_Mendelian_variants

In [133]:
mendelian_variants_metadata_no_alt = mendelian_variants_metadata.loc[~mendelian_variants_metadata[col_name].str.contains(":ALT_")].copy()

# correct length sequences?
mendelian_variants_metadata_no_alt['sequence'].str.len().value_counts()
mendelian_variants_metadata_no_alt['new_header'] = mendelian_variants_metadata_no_alt[col_name].apply(lambda name: ":".join(name.split(":")[1:]))

hf.write_fasta(mendelian_variants_metadata_no_alt, "mendelian_variants_reference_fasta.fa", header=["new_header", col_sequence])

True

In [140]:
mendelian_variants_metadata_no_alt

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label,new_header
4229,GC_Mendelian_variants:REF_chr1:21564170G>A|ALPL,CCCCAGGGAAATCTGTGGGCATTGTGACCACCACGAGAGTGAACCA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,21564034,21564304,+,[SNV],[135],[NC_000001.11:21564169:G:A],[ref],NaN,GC_Mendelian_variants,REF_chr1:21564170G>A|ALPL
4230,GC_Mendelian_variants:REF_chr1:209816133C>CA|IRF6,TTGAGCCCAGGGGCTGAATCTGGAGCTTTGGGGCCTGGGAACCTCT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,209815997,209816267,+,[indel],[135],[NC_000001.11:209816132:C:CA],[ref],NaN,GC_Mendelian_variants,REF_chr1:209816133C>CA|IRF6
4231,GC_Mendelian_variants:REF_chr10:23219376A>C|PTF1A,ATTTGGGTTTCTCCTGTGTTTCAGATACTGATGTTTGAGCTTTCTC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219240,23219510,+,"[SNV, SNV, SNV]","[135, 193, 195]","[NC_000010.11:23219375:A:C, NC_000010.11:23219...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr10:23219376A>C|PTF1A
4232,GC_Mendelian_variants:REF_chr10:23219434A>G|PTF1A,CACTTAAAGAGTCACTGTTACTTTGAGGTTTTATCTGTAAGATTCG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219298,23219568,+,"[SNV, SNV, SNV, SNV, SNV]","[77, 135, 137, 209, 218]","[NC_000010.11:23219375:A:C, NC_000010.11:23219...","[ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr10:23219434A>G|PTF1A
4233,GC_Mendelian_variants:REF_chr10:23219436A>G|PTF1A,CTTAAAGAGTCACTGTTACTTTGAGGTTTTATCTGTAAGATTCGTG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219300,23219570,+,"[SNV, SNV, SNV, SNV, SNV]","[75, 133, 135, 207, 216]","[NC_000010.11:23219375:A:C, NC_000010.11:23219...","[ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr10:23219436A>G|PTF1A
4234,GC_Mendelian_variants:REF_chr10:23219508A>G|PTF1A,CAAAGATTACAATGTCAATAGCACCTAATTACTGGACTGTGAGAAA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219372,23219642,+,"[SNV, SNV, SNV, SNV]","[61, 63, 135, 144]","[NC_000010.11:23219433:A:G, NC_000010.11:23219...","[ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr10:23219508A>G|PTF1A
4235,GC_Mendelian_variants:REF_chr10:23219517A>C|PTF1A,CAATGTCAATAGCACCTAATTACTGGACTGTGAGAAAGGTCTTCTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr10,23219381,23219651,+,"[SNV, SNV, SNV, SNV]","[52, 54, 126, 135]","[NC_000010.11:23219433:A:G, NC_000010.11:23219...","[ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr10:23219517A>C|PTF1A
4236,GC_Mendelian_variants:REF_chr11:5250053G>A|HBG1,GCCTCACTGGATACTCTAAGACTATTGGTCAAGTTTGCCTTGTCAA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr11,5249917,5250187,+,"[SNV, SNV, SNV]","[53, 56, 135]","[NC_000011.10:5249970:G:A, NC_000011.10:524997...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr11:5250053G>A|HBG1
4237,GC_Mendelian_variants:REF_chr11:5254956A>G|HBG2,CTAGCCAGCCGCCGGCCCCTGGCCTCACTGGATACTCTAAGACTAT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr11,5254820,5255090,+,"[SNV, SNV, SNV]","[74, 135, 162]","[NC_000011.10:5254894:G:T, NC_000011.10:525495...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr11:5254956A>G|HBG2
4238,GC_Mendelian_variants:REF_chr11:5254983G>C|HBG2,CTGGATACTCTAAGACTATTGGTCAAGTTTGCCTTGTCAAGGCTAT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr11,5254847,5255117,+,"[SNV, SNV, SNV]","[47, 108, 135]","[NC_000011.10:5254894:G:T, NC_000011.10:525495...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr11:5254983G>C|HBG2
4239,GC_Mendelian_variants:REF_chr11:17388225C>A|KC...,ATGGCTCCGGTGACCCCCAGGGAGGGGCTTCCCCCATCGGAGGCAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr11,17388089,17388359,+,[SNV],[135],[NC_000011.10:17388224:C:A],[ref],NaN,GC_Mendelian_variants,REF_chr11:17388225C>A|KCNJ11
4240,GC_Mendelian_variants:REF_chr11:31664397C>A|PAX6,ATTGTAAAGAGTAGATGATTTAAAACGTGTTCCCAAGATAAACTTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr11,31664261,31664531,+,[SNV],[135],[NC_000011.10:31664396:C:A],[ref],NaN,GC_Mendelian_variants,REF_chr11:31664397C>A|PAX6
4241,GC_Mendelian_variants:REF_chr12:114266710G>T|TBX5,TGCCTCCTTCTTACTGGGAAAGAGCAAAAGCCAACTTTTCATGACA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr12,114266574,114266844,+,[SNV],[135],[NC_000012.12:114266709:G:T],[ref],NaN,GC_Mendelian_variants,REF_chr12:114266710G>T|TBX5
4242,GC_Mendelian_variants:REF_chr16:159710T>C|HBA2,GGATCAGGCCCTGGGGCCTGAGTCCGGAAGAGAGGTCTGTATGGAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr16,159574,159844,+,[SNV],[135],[NC_000016.10:159709:T:C],[ref],NaN,GC_Mendelian_variants,REF_chr16:159710T>C|HBA2
4243,GC_Mendelian_variants:REF_chr17:44001600C>A|NAGS,GTGGGGCTGGGTAGGAGTGCTGACCCCAGACACTCACACTCTTCTC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr17,44001464,44001734,+,[SNV],[135],[NC_000017.11:44001599:C:A],[ref],NaN,GC_Mendelian_variants,REF_chr17:44001600C>A|NAGS
4244,GC_Mendelian_variants:REF_chr17:70680162T>C|SOX9,GCTGTAATGAAGTTAAACTCAATATATTTTTTCCTCTAGTTATAAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr17,70680026,70680296,+,[SNV],[135],[NC_000017.11:70680161:T:C],[ref],NaN,GC_Mendelian_variants,REF_chr17:70680162T>C|SOX9
4245,GC_Mendelian_variants:REF_chr19:48965093C>A|FTL,CCAGGACCCCAGGGTCATCAGTTCACAGGGCTGTTAGTGCTCCCAT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr19,48964957,48965227,+,[SNV],[135],[NC_000019.10:48965092:C:A],[ref],NaN,GC_Mendelian_variants,REF_chr19:48965093C>A|FTL
4246,GC_Mendelian_variants:REF_chr5:112737311A>T|APC,ACTGCTCTAAATACTTCATATATATTAACTCCTCTATTCTGTACTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr5,112737175,112737445,+,[SNV],[135],[NC_000005.10:112737310:A:T],[ref],NaN,GC_Mendelian_variants,REF_chr5:112737311A>T|APC
4247,GC_Mendelian_variants:REF_chr7:117479283T>G|CFTR,GGCTAAAAAGGATAGACAAGGAACACATCCTGGGCCGGTAATTACG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,117479147,117479417,+,[SNV],[135],[NC_000007.14:117479282:T:G],[ref],NaN,GC_Mendelian_variants,REF_chr7:117479283T>G|CFTR
4248,GC_Mendelian_variants:REF_chr7:156268812C>T|SHH,GGTACCAAGAAGCCACTTTAACCACTTCACATATTTCTGAAGATCC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156268676,156268946,+,[SNV],[135],[NC_000007.14:156268811:C:T],[ref],NaN,GC_Mendelian_variants,REF_chr7:156268812C>T|SHH
4249,GC_Mendelian_variants:REF_chr7:156791137T>C|SHH,GGTAAAAACTAGTGCTCTCAATTGGGGGATTGTAGAGGATTTCTAT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791001,156791271,+,[SNV],[135],[NC_000007.14:156791136:T:C],[ref],NaN,GC_Mendelian_variants,REF_chr7:156791137T>C|SHH
4250,GC_Mendelian_variants:REF_chr7:156791255G>C|SHH,GAGATATGGCTTCATTTTCTGTAATAAACACTAAGATCAAAACATG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791119,156791389,+,"[SNV, SNV, indel]","[135, 137, 154]","[NC_000007.14:156791254:G:C, NC_000007.14:1567...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791255G>C|SHH
4251,GC_Mendelian_variants:REF_chr7:156791257G>A|SHH,GATATGGCTTCATTTTCTGTAATAAACACTAAGATCAAAACATGAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791121,156791391,+,"[SNV, SNV, indel]","[133, 135, 152]","[NC_000007.14:156791254:G:C, NC_000007.14:1567...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791257G>A|SHH
4252,GC_Mendelian_variants:REF_chr7:156791274T>TTAA...,TGTAATAAACACTAAGATCAAAACATGACCCAAGTTAAATTTCCTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791138,156791408,+,"[SNV, SNV, indel]","[116, 118, 135]","[NC_000007.14:156791254:G:C, NC_000007.14:1567...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791274T>TTAAGGAAGTGATT|SHH
4253,GC_Mendelian_variants:REF_chr7:156791413A>C|SHH,CAGCACTTCCTTAATCACTCATTTCCAACAATTTATGGATCATCAG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791277,156791547,+,"[SNV, SNV, SNV, SNV, SNV, SNV]","[135, 181, 194, 194, 196, 202]","[NC_000007.14:156791412:A:C, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791413A>C|SHH
4254,GC_Mendelian_variants:REF_chr7:156791459T>C|SHH,TGGCAAAAAACGAGCAAAAATAATGAAAGAATGCAATGAAAGCTCG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791323,156791593,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV]","[89, 135, 148, 148, 150, 156, 218, 223]","[NC_000007.14:156791412:A:C, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791459T>C|SHH
4255,GC_Mendelian_variants:REF_chr7:156791474G>A|SHH,AAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791338,156791608,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[74, 120, 133, 133, 135, 141, 203, 208, 232, 2...","[NC_000007.14:156791412:A:C, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Mendelian_variants,REF_chr7:156791474G>A|SHH
4256,GC_Mendelian_variants:REF_chr7:156791480G>A|SHH,AATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTGGACTTC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791344,156791614,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[68, 114, 127, 127, 129, 135, 197, 202, 226, 2...","[NC_000007.14:156791412:A:C, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Mendelian_variants,REF_chr7:156791480G>A|SHH
4257,GC_Mendelian_variants:REF_chr7:156791542A>C|SHH,TCTTTAAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791406,156791676,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[52, 65, 65, 67, 73, 135, 140, 164, 172, 174]","[NC_000007.14:156791458:T:C, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Mendelian_variants,REF_chr7:156791542A>C|SHH
4258,GC_Mendelian_variants:REF_chr7:156791547A>G|SHH,AAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAAGTCAT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791411,156791681,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[47, 60, 60, 62, 68, 130, 135, 159, 167, 169]","[NC_000007.14:156791458:T:C, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Mendelian_variants,REF_chr7:156791547A>G|SHH
4259,GC_Mendelian_variants:REF_chr7:156791571T>A|SHH,GCCACTGGGGGGAAAAAGTCATCTGGTCATAAAATACAGTACAAGG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791435,156791705,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV]","[36, 36, 38, 44, 106, 111, 135, 143, 145]","[NC_000007.14:156791471:C:G, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791571T>A|SHH
4260,GC_Mendelian_variants:REF_chr7:156791579C>T|SHH,GGGGAAAAAGTCATCTGGTCATAAAATACAGTACAAGGTCACTTTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791443,156791713,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV]","[28, 28, 30, 36, 98, 103, 127, 135, 137]","[NC_000007.14:156791471:C:G, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791579C>T|SHH
4261,GC_Mendelian_variants:REF_chr7:156791581A>G|SHH,GGAAAAAGTCATCTGGTCATAAAATACAGTACAAGGTCACTTTTAT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791445,156791715,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV]","[26, 26, 28, 34, 96, 101, 125, 133, 135]","[NC_000007.14:156791471:C:G, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr7:156791581A>G|SHH
4262,GC_Mendelian_variants:REF_chr7:156791771G>C|SHH,CTTCGCTTCCACCTGGTCAGTCCAATTAATTAAGAAAGGAAGTTAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791635,156791905,+,[SNV],[135],[NC_000007.14:156791770:G:C],[ref],NaN,GC_Mendelian_variants,REF_chr7:156791771G>C|SHH
4263,GC_Mendelian_variants:REF_chr7:156792169G>A|SHH,ATATAATATAAAACAAATATATGCCTAACTACCATTTAAACACTGG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156792033,156792303,+,[SNV],[135],[NC_000007.14:156792168:G:A],[ref],NaN,GC_Mendelian_variants,REF_chr7:156792169G>A|SHH
4264,GC_Mendelian_variants:REF_chr8:11474238G>T|BLK,GACCTCAGGTGATCCGCCTGCCTTGGCCTCCCAAAGTGCTGGGATT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr8,11474102,11474372,+,[SNV],[135],[NC_000008.11:11474237:G:T],[ref],NaN,GC_Mendelian_variants,REF_chr8:11474238G>T|BLK
4265,GC_Mendelian_variants:REF_chr8:11703355C>A|GATA4,CCGGCTGTTATCTGGGGCTGAAGGCTGCGGTAATCGATGGGTTATT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr8,11703219,11703489,+,"[SNV, SNV]","[58, 135]","[NC_000008.11:11703277:T:C, NC_000008.11:11703...","[ref, ref]",NaN,GC_Mendelian_variants,REF_chr8:11703355C>A|GATA4
4266,GC_Mendelian_variants:REF_chr8:11703774C>T|GATA4,ATTTTGGGAAGGCAAAAGGGAGGCTTCGGTCTCTACGCTCTGATTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr8,11703638,11703908,+,"[SNV, SNV]","[135, 221]","[NC_000008.11:11703773:C:T, NC_000008.11:11703...","[ref, ref]",NaN,GC_Mendelian_variants,REF_chr8:11703774C>T|GATA4
4267,GC_Mendelian_variants:REF_chr8:11703860G>T|GATA4,CGGGGCTGGGAGGATCCCCACTACCCCTGCCCAGGAACTAGCATCC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr8,11703724,11703994,+,"[SNV, SNV, indel]","[49, 135, 165]","[NC_000008.11:11703773:C:T, NC_000008.11:11703...","[ref, ref, ref]",NaN,GC_Mendelian_variants,REF_chr8:11703860G>T|GATA4
4268,GC_Mendelian_variants:REF_chr8:11703890AG>A|GATA4,CCAGGAACTAGCATCCAGCCGGGCACCCCGGGTGACCCAGTGCCCC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr8,11703754,11704024,+,"[SNV, indel]","[105, 135]","[NC_000008.11:11703859:G:T, NC_000008.11:11703...","[ref, ref]",NaN,GC_Mendelian_variants,REF_chr8:11703890AG>A|GATA4
4271,GC_Mendelian_variants:REF_chr9:101435912C>T|ALDOB,AGATCTTTGGTAGCACACAATTTTTATAGACTTCTCATCATGTTTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr9,101435776,101436046,+,[SNV],[135],[NC_000009.12:101435911:C:T],[ref],NaN,GC_Mendelian_variants,REF_chr9:101435912C>T|ALDOB
4272,GC_Mendelian_variants:REF_chrX:38352331A>G|OTC,GTGGAAAGACTGGCAATTAGAGGTAGAAAAGTGAAATAAATGGAAA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chrX,38352195,38352465,+,[SNV],[135],[NC_000023.11:38352330:A:G],[ref],NaN,GC_Mendelian_variants,REF_chrX:38352331A>G|OTC
4273,GC_Mendelian_variants:REF_chrX:55028202A>G|ALAS2,AGGTAATTATGGCCACTTCACAAGGTAGGTAAGGAATTGGATCCAG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chrX,55028066,55028336,+,[SNV],[135],[NC_000023.11:55028201:A:G],[ref],NaN,GC_Mendelian_variants,REF_chrX:55028202A>G|ALAS2
4274,GC_Mendelian_variants:REF_chrX:55031184G>C|ALAS2,GGCCTGGCCCTGCATTGGCCCCAAAGGTATCTCAGTCCCTTCCTTG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chrX,55031048,55031318,+,[SNV],[135],[NC_000023.11:55031183:G:C],[ref],NaN,GC_Mendelian_variants,REF_chrX:55031184G>C|ALAS2
4275,GC_Mendelian_variants:REF_chrX:106007977G>A|SE...,GAGACAGAAGTCAGGAAATAGGTGGAGCAACATCACAGATAGTTGT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chrX,106007841,106008111,+,[SNV],[135],[NC_000023.11:106007976:G:A],[ref],NaN,GC_Mendelian_variants,REF_chrX:106007977G>A|SERPINA7
80042,GC_Mendelian_variants:REF_chr7:156791472C>G|SH...,GCAAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791336,156791606,+,"[SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, SNV, ...","[76, 122, 135, 135, 137, 143, 205, 210, 234, 2...","[NC_000007.14:156791412:A:C, NC_000007.14:1567...","[ref, ref, ref, ref, ref, ref, ref, ref, ref, ...",NaN,GC_Mendelian_variants,REF_chr7:156791472C>G|SHH;GC_Mendelian_variant...

In [137]:
# scp /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/mendelian_variants_reference_fasta.fa  kisa11_c@172.16.35.182:/data/cephfs-1/scratch/groups/kircher/users/kisa11_c/tmp/mendelian_variants_reference_fasta.fa
# makeblastdb -in /data/cephfs-1/work/projects/cubit/current/static_data/reference/hg38/ucsc/hg38.fa -dbtype nucl -out human_ref
# blastn -query mendelian_variants_reference_fasta.fa -db human_ref -out mendelian_variants_ref_hg38_out.txt -outfmt 6 -num_threads 4

# read the results in:
mendelian_variants_ref_blast_output = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/mendelian_variants_ref_hg38_out.txt"

mendelian_ref_blast = pd.read_csv(mendelian_variants_ref_blast_output, sep="\t", header=None, names=["qseqid", "sseqid", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"])
mendelian_ref_blast

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
0,REF_chr1:21564170G>A|ALPL,chr1,100.0,270,0,0,1,270,21564035,21564304,2.780000e-139,499.0
1,REF_chr1:209816133C>CA|IRF6,chr1,100.0,270,0,0,1,270,209815998,209816267,2.780000e-139,499.0
2,REF_chr10:23219376A>C|PTF1A,chr10,100.0,270,0,0,1,270,23219241,23219510,2.780000e-139,499.0
3,REF_chr10:23219434A>G|PTF1A,chr10,100.0,270,0,0,1,270,23219299,23219568,2.780000e-139,499.0
4,REF_chr10:23219436A>G|PTF1A,chr10,100.0,270,0,0,1,270,23219301,23219570,2.780000e-139,499.0
...,...,...,...,...,...,...,...,...,...,...,...,...
213466,REF_chrX:38352331A>G|OTC,chrX,100.0,270,0,0,1,270,38352196,38352465,2.780000e-139,499.0
213467,REF_chrX:55028202A>G|ALAS2,chrX,100.0,270,0,0,1,270,55028067,55028336,2.780000e-139,499.0
213468,REF_chrX:55031184G>C|ALAS2,chrX,100.0,270,0,0,1,270,55031049,55031318,2.780000e-139,499.0
213469,REF_chrX:106007977G>A|SERPINA7,chrX,100.0,270,0,0,1,270,106007842,106008111,2.780000e-139,499.0
213470,REF_chr7:156791472C>G|SHH;GC_Mendelian_variant...,chr7,100.0,270,0,0,1,270,156791337,156791606,2.780000e-139,499.0

In [149]:
def get_name_from_blast_results(row, associated_gene=""):
    """From a standard output of blastn get the name defined as <sseqid>:<sstart(-1)>-send"""
    return f'{associated_gene}_{row["sseqid"]}:{int(row["sstart"])-1}-{row["send"]}'

In [155]:
mendelian_ref_blast_only_perfect = mendelian_ref_blast.loc[(mendelian_ref_blast['length'] == 270) & (mendelian_ref_blast['pident'] == 100)].copy()
mendelian_ref_blast_only_perfect['associated_gene'] = mendelian_ref_blast_only_perfect['qseqid'].apply(lambda name: name.split("|")[-1])
mendelian_ref_blast_only_perfect['name'] = mendelian_ref_blast_only_perfect.apply(lambda row: get_name_from_blast_results(row, associated_gene=row["associated_gene"]), axis=1)

# write bed
mendelian_ref_blast_only_perfect['start'] = mendelian_ref_blast_only_perfect["sstart"].apply(lambda start: int(start) -1)
mendelian_ref_blast_only_perfect['strand'] = "+"

In [156]:
mendelian_ref_blast_only_perfect[['sseqid', 'start', 'send', 'name', 'bitscore', 'strand']].to_csv("mendelian_reference_region.bed", sep="\t", header=None, index=False)

In [151]:
mendelian_ref_blast_only_perfect

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,associated_gene,name
0,REF_chr1:21564170G>A|ALPL,chr1,100.0,270,0,0,1,270,21564035,21564304,2.780000e-139,499.0,ALPL,ALPL_chr1:21564034-21564304
1,REF_chr1:209816133C>CA|IRF6,chr1,100.0,270,0,0,1,270,209815998,209816267,2.780000e-139,499.0,IRF6,IRF6_chr1:209815997-209816267
2,REF_chr10:23219376A>C|PTF1A,chr10,100.0,270,0,0,1,270,23219241,23219510,2.780000e-139,499.0,PTF1A,PTF1A_chr10:23219240-23219510
3,REF_chr10:23219434A>G|PTF1A,chr10,100.0,270,0,0,1,270,23219299,23219568,2.780000e-139,499.0,PTF1A,PTF1A_chr10:23219298-23219568
4,REF_chr10:23219436A>G|PTF1A,chr10,100.0,270,0,0,1,270,23219301,23219570,2.780000e-139,499.0,PTF1A,PTF1A_chr10:23219300-23219570
5,REF_chr10:23219508A>G|PTF1A,chr10,100.0,270,0,0,1,270,23219373,23219642,2.780000e-139,499.0,PTF1A,PTF1A_chr10:23219372-23219642
6,REF_chr10:23219517A>C|PTF1A,chr10,100.0,270,0,0,1,270,23219382,23219651,2.780000e-139,499.0,PTF1A,PTF1A_chr10:23219381-23219651
7,REF_chr11:5250053G>A|HBG1,chr11,100.0,270,0,0,1,270,5249918,5250187,2.780000e-139,499.0,HBG1,HBG1_chr11:5249917-5250187
9,REF_chr11:5254956A>G|HBG2,chr11,100.0,270,0,0,1,270,5254821,5255090,2.780000e-139,499.0,HBG2,HBG2_chr11:5254820-5255090
11,REF_chr11:5254983G>C|HBG2,chr11,100.0,270,0,0,1,270,5254848,5255117,2.780000e-139,499.0,HBG2,HBG2_chr11:5254847-5255117
13,REF_chr11:17388225C>A|KCNJ11,chr11,100.0,270,0,0,1,270,17388090,17388359,2.780000e-139,499.0,KCNJ11,KCNJ11_chr11:17388089-17388359
29958,REF_chr11:31664397C>A|PAX6,chr11,100.0,270,0,0,1,270,31664262,31664531,2.780000e-139,499.0,PAX6,PAX6_chr11:31664261-31664531
29959,REF_chr12:114266710G>T|TBX5,chr12,100.0,270,0,0,1,270,114266575,114266844,2.780000e-139,499.0,TBX5,TBX5_chr12:114266574-114266844
29960,REF_chr16:159710T>C|HBA2,chr16,100.0,270,0,0,1,270,159575,159844,2.780000e-139,499.0,HBA2,HBA2_chr16:159574-159844
29961,REF_chr17:44001600C>A|NAGS,chr17,100.0,270,0,0,1,270,44001465,44001734,2.780000e-139,499.0,NAGS,NAGS_chr17:44001464-44001734
29962,REF_chr17:70680162T>C|SOX9,chr17,100.0,270,0,0,1,270,70680027,70680296,2.780000e-139,499.0,SOX9,SOX9_chr17:70680026-70680296
29963,REF_chr19:48965093C>A|FTL,chr19,100.0,270,0,0,1,270,48964958,48965227,2.780000e-139,499.0,FTL,FTL_chr19:48964957-48965227
29964,REF_chr5:112737311A>T|APC,chr5,100.0,270,0,0,1,270,112737176,112737445,2.780000e-139,499.0,APC,APC_chr5:112737175-112737445
29965,REF_chr7:117479283T>G|CFTR,chr7,100.0,270,0,0,1,270,117479148,117479417,2.780000e-139,499.0,CFTR,CFTR_chr7:117479147-117479417
29966,REF_chr7:156268812C>T|SHH,chr7,100.0,270,0,0,1,270,156268677,156268946,2.780000e-139,499.0,SHH,SHH_chr7:156268676-156268946
29967,REF_chr7:156791137T>C|SHH,chr7,100.0,270,0,0,1,270,156791002,156791271,2.780000e-139,499.0,SHH,SHH_chr7:156791001-156791271
29968,REF_chr7:156791255G>C|SHH,chr7,100.0,270,0,0,1,270,156791120,156791389,2.780000e-139,499.0,SHH,SHH_chr7:156791119-156791389
29969,REF_chr7:156791257G>A|SHH,chr7,100.0,270,0,0,1,270,156791122,156791391,2.780000e-139,499.0,SHH,SHH_chr7:156791121-156791391
29970,REF_chr7:156791274T>TTAAGGAAGTGATT|SHH,chr7,100.0,270,0,0,1,270,156791139,156791408,2.780000e-139,499.0,SHH,SHH_chr7:156791138-156791408
29971,REF_chr7:156791413A>C|SHH,chr7,100.0,270,0,0,1,270,156791278,156791547,2.780000e-139,499.0,SHH,SHH_chr7:156791277-156791547
29972,REF_chr7:156791459T>C|SHH,chr7,100.0,270,0,0,1,270,156791324,156791593,2.780000e-139,499.0,SHH,SHH_chr7:156791323-156791593
29973,REF_chr7:156791474G>A|SHH,chr7,100.0,270,0,0,1,270,156791339,156791608,2.780000e-139,499.0,SHH,SHH_chr7:156791338-156791608
29974,REF_chr7:156791480G>A|SHH,chr7,100.0,270,0,0,1,270,156791345,156791614,2.780000e-139,499.0,SHH,SHH_chr7:156791344-156791614
29975,REF_chr7:156791542A>C|SHH,chr7,100.0,270,0,0,1,270,156791407,156791676,2.780000e-139,499.0,SHH,SHH_chr7:156791406-156791676
29976,REF_chr7:156791547A>G|SHH,chr7,100.0,270,0,0,1,270,156791412,156791681,2.780000e-139,499.0,SHH,SHH_chr7:156791411-156791681
29977,REF_chr7:156791571T>A|SHH,chr7,100.0,270,0,0,1,270,156791436,156791705,2.780000e-139,499.0,SHH,SHH_chr7:156791435-156791705
29978,REF_chr7:156791579C>T|SHH,chr7,100.0,270,0,0,1,270,156791444,156791713,2.780000e-139,499.0,SHH,SHH_chr7:156791443-156791713
29979,REF_chr7:156791581A>G|SHH,chr7,100.0,270,0,0,1,270,156791446,156791715,2.780000e-139,499.0,SHH,SHH_chr7:156791445-156791715
29980,REF_chr7:156791771G>C|SHH,chr7,100.0,270,0,0,1,270,156791636,156791905,2.780000e-139,499.0,SHH,SHH_chr7:156791635-156791905
29981,REF_chr7:156792169G>A|SHH,chr7,100.0,270,0,0,1,270,156792034,156792303,2.780000e-139,499.0,SHH,SHH_chr7:156792033-156792303
29982,REF_chr8:11474238G>T|BLK,chr8,100.0,270,0,0,1,270,11474103,11474372,2.780000e-139,499.0,BLK,BLK_chr8:11474102-11474372
213460,REF_chr8:11703355C>A|GATA4,chr8,100.0,270,0,0,1,270,11703220,11703489,2.780000e-139,499.0,GATA4,GATA4_chr8:11703219-11703489
213461,REF_chr8:11703774C>T|GATA4,chr8,100.0,270,0,0,1,270,11703639,11703908,2.780000e-139,499.0,GATA4,GATA4_chr8:11703638-11703908
213462,REF_chr8:11703860G>T|GATA4,chr8,100.0,270,0,0,1,270,11703725,11703994,2.780000e-139,499.0,GATA4,GATA4_chr8:11703724-11703994
213463,REF_chr8:11703890AG>A|GATA4,chr8,100.0,270,0,0,1,270,11703755,11704024,2.780000e-139,499.0,GATA4,GATA4_chr8:11703754-11704024
213464,REF_chr9:101435912C>T|ALDOB,chr9,100.0,270,0,0,1,270,101435777,101436046,2.780000e-139,499.0,ALDOB,ALDOB_chr9:101435776-101436046
213466,REF_chrX:38352331A>G|OTC,chrX,100.0,270,0,0,1,270,38352196,38352465,2.780000e-139,499.0,OTC,OTC_chrX:38352195-38352465
213467,REF_chrX:55028202A>G|ALAS2,chrX,100.0,270,0,0,1,270,55028067,55028336,2.780000e-139,499.0,ALAS2,ALAS2_chrX:55028066-55028336
213468,REF_chrX:55031184G>C|ALAS2,chrX,100.0,270,0,0,1,270,55031049,55031318,2.780000e-139,499.0,ALAS2,ALAS2_chrX:55031048-55031318
213469,REF_chrX:106007977G>A|SERPINA7,chrX,100.0,270,0,0,1,270,106007842,106008111,2.780000e-139,499.0,SERPINA7,SERPINA7_chrX:106007841-106008111
213470,REF_chr7:156791472C>G|SHH;GC_Mendelian_variant...,chr7,100.0,270,0,0,1,270,156791337,156791606,2.780000e-139,499.0,SHH,SHH_chr7:156791336-156791606

Using MPRAOligodesign
```
snakemake --sdm conda --configfile mendelian_variant_oligo_design_config.yaml --snakefile /data/cephfs-1/scratch/groups/kircher/MPRA/mendelian_variant_second_version/MPRAOligoDesign/workflow/Snakefile
```

```
sample  bed_file        vcf_file
GC_Mendelian_variants   /data/cephfs-1/scratch/groups/kircher/MPRA/mendelian_variant_second_version/mendelian_reference_region.bed  /data/cephfs-1/scratch/groups/kircher/MPRA/mendelian_variant_second_version/mendelian_variants.vcf
```

results: 
```
/data/cephfs-1/scratch/groups/kircher/MPRA/mendelian_variant_second_version/results/final_design/design.fa.gz
```

In [198]:
# create coordinates from the variant_region_map + design file + region bed
mendelian_variant_region_map_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/mendelian_variants_MPRAoligo_design/variant_region_map.tsv.gz"
mendelian_variant_region_map = pd.read_csv(mendelian_variant_region_map_path, sep="\t")

mendelian_region_bed_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/mendelian_variants_MPRAoligo_design/regions.bed.gz"
mendelian_region_bed = pd.read_csv(mendelian_region_bed_path, sep="\t", header=None, names=[col_chr, col_start, col_end, "Region", "score", col_strand])
mendelian_region_bed

medelian_design_fa = hf.fasta_to_dataframe("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/mendelian_variants_MPRAoligo_design/design.fa.gz", columns=['name', 'sequence'])
medelian_design_fa['sequence_no_adapter'] = medelian_design_fa['sequence'].apply(lambda seq: seq[15:-15])

In [ ]:
mendelian_variant_region_df = mendelian_variant_region_map.merge(mendelian_region_bed, on="Region", how="inner").copy()

# add the region information to the design file:
# split design into ref and alt (clean split or is there something inbetween?)
# append inn

,Variant,Region,REF_ID,ALT_ID,chr,start,end,score,strand
0,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:ALPL_chr1:21564034-21564...,GC_Mendelian_variants:REF_ALPL_chr1:21564034-2...,GC_Mendelian_variants:ALT_ALPL_chr1:21564034-2...,chr1,21564034,21564304,499.0,+
1,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:IRF6_chr1:209815997-2098...,GC_Mendelian_variants:REF_IRF6_chr1:209815997-...,GC_Mendelian_variants:ALT_IRF6_chr1:209815997-...,chr1,209815997,209816267,499.0,+
2,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:PTF1A_chr10:23219240-232...,GC_Mendelian_variants:REF_PTF1A_chr10:23219240...,GC_Mendelian_variants:ALT_PTF1A_chr10:23219240...,chr10,23219240,23219510,499.0,+
3,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:PTF1A_chr10:23219298-232...,GC_Mendelian_variants:REF_PTF1A_chr10:23219298...,GC_Mendelian_variants:ALT_PTF1A_chr10:23219298...,chr10,23219298,23219568,499.0,+
4,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:PTF1A_chr10:23219300-232...,GC_Mendelian_variants:REF_PTF1A_chr10:23219300...,GC_Mendelian_variants:ALT_PTF1A_chr10:23219300...,chr10,23219300,23219570,499.0,+
...,...,...,...,...,...,...,...,...,...
158,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:ALDOB_chr9:101435776-101...,GC_Mendelian_variants:REF_ALDOB_chr9:101435776...,GC_Mendelian_variants:ALT_ALDOB_chr9:101435776...,chr9,101435776,101436046,499.0,+
159,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:OTC_chrX:38352195-383524...,GC_Mendelian_variants:REF_OTC_chrX:38352195-38...,GC_Mendelian_variants:ALT_OTC_chrX:38352195-38...,chrX,38352195,38352465,499.0,+
160,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:ALAS2_chrX:55028066-5502...,GC_Mendelian_variants:REF_ALAS2_chrX:55028066-...,GC_Mendelian_variants:ALT_ALAS2_chrX:55028066-...,chrX,55028066,55028336,499.0,+
161,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:ALAS2_chrX:55031048-5503...,GC_Mendelian_variants:REF_ALAS2_chrX:55031048-...,GC_Mendelian_variants:ALT_ALAS2_chrX:55031048-...,chrX,55031048,55031318,499.0,+
162,GC_Mendelian_variants:GC_Mendelian_variants:ch...,GC_Mendelian_variants:SERPINA7_chrX:106007841-...,GC_Mendelian_variants:REF_SERPINA7_chrX:106007...,GC_Mendelian_variants:ALT_SERPINA7_chrX:106007...,chrX,106007841,106008111,499.0,+

### Old way: not finished might get removed: merge with the shuffled sequences header by adding shuffeled to the name

In [ ]:
# shuffled_sequences_dnase = hf.fasta_to_dataframe("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_hg38_dnase_controls_no_shuffled.diShuffled.fa")

In [ ]:
# shuffled_sequences_dnase

,header,sequence,mod_header
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CGCTCAGAATTCCGCTGGCCTTAGTTGTTGGAACCTGCCATGTTGA...,GC_DNase_negative_brain_shuffeled:chr1:4768943...
1,GC_DNase_negative_brain:chr10:27823303-2782357...,AGACCAGCTCAAGTTTATTTCTTGTGATACCAACATTGCATTTCAG...,GC_DNase_negative_brain_shuffeled:chr10:278233...
2,GC_DNase_negative_brain:chr11:75379056-7537932...,AGCGTGTGGCGGCGCCCGGCCGAAGCGGGGGGGTGGGGGCTGTCGC...,GC_DNase_negative_brain_shuffeled:chr11:753790...
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TAATAGTAAGATGATAAAATTCCTTAGATGTTTTAGTGGTCAACAA...,GC_DNase_negative_brain_shuffeled:chr13:352971...
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTCTGGCAGCTTAGTTCAGCATTAGGCTTATCTTAAGGGAGACA...,GC_DNase_negative_brain_shuffeled:chr13:669193...
...,...,...,...
66,GC_DNase_positive:chr7:61079125-61079394_activ...,GATATTACAACGGAGATTAATAATGTGCTTTCATTTTTTTACTTCA...,GC_DNase_positive_shuffeled:chr7:61079125-6107...
67,GC_DNase_positive:chr7:68527446-68527715_activ...,ACCAGAACGCTATCTGCTGCGAAGAACACACAAAGGCCAGAATTAC...,GC_DNase_positive_shuffeled:chr7:68527446-6852...
68,GC_DNase_positive:chr8:8085418-8085687_active_...,TACTAGCTGGCGCAACGGTCGGAGTTGACCGAACCCTCCCCCGGTC...,GC_DNase_positive_shuffeled:chr8:8085418-80856...
69,GC_DNase_positive:chr8:56755078-56755347_activ...,CATGTGAGACTCTGTGACTCCCAAATGTAACCCACCTTAGCCTTTT...,GC_DNase_positive_shuffeled:chr8:56755078-5675...
70,GC_DNase_positive:chr9:88419918-88420187_activ...,GAGCGTCCTGGCCGCACCGCCTTGGTACCGCGTGACCCCCTTGCGC...,GC_DNase_positive_shuffeled:chr9:88419918-8842...

In [ ]:
shuffled_sequences_dnase["mod_header"] = shuffled_sequences_dnase["header"].apply(lambda header: header.split(":")[0] + "_shuffeled:" + ":".join(header.split(":")[1:]))
# remove brackets
shuffled_sequences_dnase["mod_header"] = shuffled_sequences_dnase["mod_header"].apply(remove_tailing_brackets_of_dnase_headers)

In [ ]:
shuffled_general_controls = general_control_metadata_dnase.loc[general_control_metadata_dnase["label"].str.contains("shuff")]

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
1502,GC_DNase_negative_brain_shuffeled:chr1:4768943...,CTTCCAATTTCACCCAAAAGCCCCCCTGGCCTCAGGTGTCTAGGGG...,scrambled,element inactive control,NaN,GRCh37,chr1,4708882,4709152,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled
1503,GC_DNase_negative_brain_shuffeled:chr10:278233...,TAATTTAAATTCCAATTATCTTAAAATGATCTCTAATTGTCTTTTA...,scrambled,element inactive control,NaN,GRCh37,chr10,27534373,27534643,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled
1504,GC_DNase_negative_brain_shuffeled:chr11:753790...,ACAGAGACTCCTTTGGAAGTTAATCAGGTTGTAAATGGTGCTGGGA...,scrambled,element inactive control,NaN,GRCh37,chr11,75668010,75668280,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled
1505,GC_DNase_negative_brain_shuffeled:chr13:352971...,TTTAATATGTTGAATCCTTCAATATTTAATTATTTATCATTGTACA...,scrambled,element inactive control,NaN,GRCh37,chr13,34722983,34723253,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled
1506,GC_DNase_negative_brain_shuffeled:chr13:669193...,TGGTTGCAGTCTAGCTTGTCAAAAATCAAGTGCATGATGCACAGTT...,scrambled,element inactive control,NaN,GRCh37,chr13,66345227,66345497,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76838,GC_DNase_positive_shuffeled:chr7:102389176-102...,ATTTTCTCAGAGGCATGCTTTCTCTTTATCCCCTGGGGTGCTGCTA...,scrambled,element inactive control,NaN,GRCh37,chr7,102748728,102748998,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled
76839,GC_DNase_positive_shuffeled:chr8:8085418-80856...,GGTGGAGCTTGGTGTCTCAACTTTAAAAGCTCATGGCAGACCATAT...,scrambled,element inactive control,NaN,GRCh37,chr8,8227895,8228165,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled
76840,GC_DNase_positive_shuffeled:chr8:56755078-5675...,CCTGCCTTGTTAGTAACTTGTGTCATAGTTCTCTTGCAAGAGGTCT...,scrambled,element inactive control,NaN,GRCh37,chr8,55842518,55842788,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled
76841,GC_DNase_positive_shuffeled:chr9:88419918-8842...,CACCCTGCCCATCAAGTGGCGTTGTTTCAGCCAGGGTGCGATGATC...,scrambled,element inactive control,NaN,GRCh37,chr9,85805002,85805272,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled
76842,GC_DNase_positive_shuffeled:chr16:46401227-464...,TCGATCGGATCTCTGATGACCAAAAATGTGAATCAATGGAAGATCA...,scrambled,element inactive control,NaN,GRCh37,chr16,46401226,46401496,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled

In [ ]:
shuffled_sequences_dnase.merge(general_control_metadata_dnase, left_on="mod_header", right_on="name", how="inner")

,header,sequence_x,mod_header,name,sequence_y,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label,no_tailing_brackets_name
0,GC_DNase_negative_brain:chr1:4768943-4769212_a...,CGCTCAGAATTCCGCTGGCCTTAGTTGTTGGAACCTGCCATGTTGA...,GC_DNase_negative_brain_shuffeled:chr1:4768943...,GC_DNase_negative_brain_shuffeled:chr1:4768943...,CTTCCAATTTCACCCAAAAGCCCCCCTGGCCTCAGGTGTCTAGGGG...,scrambled,element inactive control,NaN,GRCh37,chr1,4708882,4709152,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled,GC_DNase_negative_brain_shuffeled:chr1:4768943...
1,GC_DNase_negative_brain:chr10:27823303-2782357...,AGACCAGCTCAAGTTTATTTCTTGTGATACCAACATTGCATTTCAG...,GC_DNase_negative_brain_shuffeled:chr10:278233...,GC_DNase_negative_brain_shuffeled:chr10:278233...,TAATTTAAATTCCAATTATCTTAAAATGATCTCTAATTGTCTTTTA...,scrambled,element inactive control,NaN,GRCh37,chr10,27534373,27534643,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled,GC_DNase_negative_brain_shuffeled:chr10:278233...
2,GC_DNase_negative_brain:chr11:75379056-7537932...,AGCGTGTGGCGGCGCCCGGCCGAAGCGGGGGGGTGGGGGCTGTCGC...,GC_DNase_negative_brain_shuffeled:chr11:753790...,GC_DNase_negative_brain_shuffeled:chr11:753790...,ACAGAGACTCCTTTGGAAGTTAATCAGGTTGTAAATGGTGCTGGGA...,scrambled,element inactive control,NaN,GRCh37,chr11,75668010,75668280,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled,GC_DNase_negative_brain_shuffeled:chr11:753790...
3,GC_DNase_negative_brain:chr13:35297121-3529739...,TAATAGTAAGATGATAAAATTCCTTAGATGTTTTAGTGGTCAACAA...,GC_DNase_negative_brain_shuffeled:chr13:352971...,GC_DNase_negative_brain_shuffeled:chr13:352971...,TTTAATATGTTGAATCCTTCAATATTTAATTATTTATCATTGTACA...,scrambled,element inactive control,NaN,GRCh37,chr13,34722983,34723253,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled,GC_DNase_negative_brain_shuffeled:chr13:352971...
4,GC_DNase_negative_brain:chr13:66919360-6691962...,TTTTCTGGCAGCTTAGTTCAGCATTAGGCTTATCTTAAGGGAGACA...,GC_DNase_negative_brain_shuffeled:chr13:669193...,GC_DNase_negative_brain_shuffeled:chr13:669193...,TGGTTGCAGTCTAGCTTGTCAAAAATCAAGTGCATGATGCACAGTT...,scrambled,element inactive control,NaN,GRCh37,chr13,66345227,66345497,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_negative_brain_shuffeled,GC_DNase_negative_brain_shuffeled:chr13:669193...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,GC_DNase_positive:chr7:61079125-61079394_activ...,GATATTACAACGGAGATTAATAATGTGCTTTCATTTTTTTACTTCA...,GC_DNase_positive_shuffeled:chr7:61079125-6107...,GC_DNase_positive_shuffeled:chr7:61079125-6107...,AAAGTCTTCAGGTCCATTCACTTTGCATACTAGTAATATTTTTTAC...,scrambled,element inactive control,NaN,GRCh37,chr7,61096399,61096669,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled,GC_DNase_positive_shuffeled:chr7:61079125-6107...
67,GC_DNase_positive:chr7:68527446-68527715_activ...,ACCAGAACGCTATCTGCTGCGAAGAACACACAAAGGCCAGAATTAC...,GC_DNase_positive_shuffeled:chr7:68527446-6852...,GC_DNase_positive_shuffeled:chr7:68527446-6852...,GGGTAGGCCTGTCATTTCGTGAGGAGATTAGCCCCAAAAGACACTT...,scrambled,element inactive control,NaN,GRCh37,chr7,69062458,69062728,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled,GC_DNase_positive_shuffeled:chr7:68527446-6852...
68,GC_DNase_positive:chr8:8085418-8085687_active_...,TACTAGCTGGCGCAACGGTCGGAGTTGACCGAACCCTCCCCCGGTC...,GC_DNase_positive_shuffeled:chr8:8085418-80856...,GC_DNase_positive_shuffeled:chr8:8085418-80856...,GGTGGAGCTTGGTGTCTCAACTTTAAAAGCTCATGGCAGACCATAT...,scrambled,element inactive control,NaN,GRCh37,chr8,8227895,8228165,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled,GC_DNase_positive_shuffeled:chr8:8085418-80856...
69,GC_DNase_positive:chr8:56755078-56755347_activ...,CATGTGAGACTCTGTGACTCCCAAATGTAACCCACCTTAGCCTTTT...,GC_DNase_positive_shuffeled:chr8:56755078-5675...,GC_DNase_positive_shuffeled:chr8:56755078-5675...,CCTGCCTTGTTAGTAACTTGTGTCATAGTTCTCTTGCAAGAGGTCT...,scrambled,element inactive control,NaN,GRCh37,chr8,55842518,55842788,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled,GC_DNase_positive_shuffeled:chr8:56755078-5675...
70,GC_DNase_positive:chr9:88419918-88420187_activ...,GAGCGTCCTGGCCGCACCGCCTTGGTACCGCGTGACCCCCTTGCGC...,GC_DNase_positive_shuffeled:chr9:88419918-8842...,GC_DNase_positive_shuffeled:chr9:88419918-8842...,CACCCTGCCCATCAAGTGGCGTTGTTTCAGCCAGGGTGCGATGATC...,scrambled,element inactive control,NaN,GRCh37,chr9,85805002,85805272,+,None,None,None,None,Sequences are designed based on GRCh37 (wrong ...,GC_DNase_positive_shuffeled,GC_DNase_positive_shuffeled:chr9:88419918-8842...

### Get the MK sequences and blast them against hg38
`blastn -query /data/cephfs-2/unmirrored/groups/kircher/MPRA/IGVF_2025_design_WTC11/results/80k_mpra_general_controls_no_shuffled.fa -db human_ref -out gc_controls_results.txt -outfmt 6 -num_threads 4`
-result: the genomic regions look file (maybe some are different => try out)
- get the genomic regions from the header (start -1) and then with getfasta and compare start and end of the sequence => which do not match? (fix by hand)

In [ ]:
mk_metadata = metadata_df.loc[metadata_df[col_name].str.startswith('MK')].copy()

In [ ]:
def correct_MK_metadata(row):
    """
    Correct MK metadata:
    - category treat everything as element except the ones which contain scramble in the header => scrambled
    - set all as element active control except the ones which contain scramble => element inactive control
    - get the regions from the header (start -1) and strand from inbetween
    """
    pass

In [ ]:
mk_metadata_regions = mk_metadata.apply(get_mk_region_from_header, axis=1).copy()

In [ ]:
mk_metadata_regions

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
77640,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,variant negative control,Michael Kosicki,GRCh38,8,10365156,10365425,+,None,None,None,None,NaN,MK
77641,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,variant negative control,Michael Kosicki,GRCh38,20,20492859,20493129,+,None,None,None,None,NaN,MK
77642,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,variant negative control,Michael Kosicki,GRCh38,22,42282878,42283148,+,None,None,None,None,NaN,MK
77643,MK:CENPE|chr4-103198452-103198721|reference,AAAAATACATGTATCTCTACCTAGTTTCGTCTACAGGTTCCAAACT...,element,element inactive control,Michael Kosicki,GRCh38,4,103198452,103198721,-,None,None,None,None,NaN,MK
77644,MK:tile_45386|chr9-33290305+33290574|reference,AAAACCACAATGATTACGCAAGTCGCCGCCCTCCCTCCTGCGATTG...,element,element inactive control,Michael Kosicki,GRCh38,9,33290305,33290574,+,None,None,None,None,NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80032,MK:tile_2240|chr1-116244322+116244591|scramble...,CTTAATCAAATAACCCATTAATTCTATATATCTACCTAATATTAAT...,scrambled,element inactive control,Michael Kosicki,GRCh38,1,116244322,116244591,+,None,None,None,None,NaN,MK
80033,MK:tile_6675|chr11-2374617+2374886|scramble_ne...,CATCGGCCCTGGTGAAGCGTCCGTCCAGACGGGCCTGCCTAGCCTC...,scrambled,element inactive control,Michael Kosicki,GRCh38,11,2374617,2374886,+,None,None,None,None,NaN,MK
80034,MK:tile_18415|chr17-71181691+71181960|scramble...,TAAATATTCAGCGATACATTCCTATTCTTTTTCAGAAGTAGTTATT...,scrambled,element inactive control,Michael Kosicki,GRCh38,17,71181691,71181960,+,None,None,None,None,NaN,MK
80035,MK:tile_14356|chr15-67031618+67031887|scramble...,TGAAGCCCCTGATTCTGTTAGAATAAGGTTACTGAGTCGTGTATAC...,scrambled,element inactive control,Michael Kosicki,GRCh38,15,67031618,67031887,+,None,None,None,None,NaN,MK
80036,MK:tile_22033|chr2-71506006+71506275|scramble_...,GGGGGAGAAATTGGACAGGCACGCCTTGCTCATGTGTGTGGGGACT...,scrambled,element inactive control,Michael Kosicki,GRCh38,2,71506006,71506275,+,None,None,None,None,NaN,MK

In [ ]:
mk_metadata_no_scrambled = mk_metadata.loc[~mk_metadata["name"].str.contains("scramble")]

In [ ]:
mk_metadata_no_scrambled

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,label
77640,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77641,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77642,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77643,MK:CENPE|chr4-103198452-103198721|reference,AAAAATACATGTATCTCTACCTAGTTTCGTCTACAGGTTCCAAACT...,element,element inactive control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
77644,MK:tile_45386|chr9-33290305+33290574|reference,AAAACCACAATGATTACGCAAGTCGCCGCCCTCCCTCCTGCGATTG...,element,element inactive control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79532,MK:tile_9894|chr12-94535162+94535431|A-T-113,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
79533,MK:tile_9894|chr12-94535162+94535431|G-A-105,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
79534,MK:tile_9894|chr12-94535162+94535431|G-C-105,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
79535,MK:tile_9894|chr12-94535162+94535431|ts102-108,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK
79536,MK:tile_9894|chr12-94535162+94535431|ts110-116,CTAATGAAGGGGGCGATTCCCTGTCTCCGCTATGAAAAGAAAAATG...,variant,variant negative control,Michael Kosicki,GRCh38,NaN,NaN,NaN,NaN,None,None,None,None,NaN,MK

In [ ]:
hf.write_fasta(mk_metadata_no_scrambled, "80k_MK_sequences_for_hg38_blast.fa", header=["name", "sequence"])

True

In [ ]:
blast_mk_output = pd.read_csv("/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/mk_80k_blastn_hg38_out.txt", sep="\t", header=None)

In [ ]:
blast_mk_output.columns = ["qseqid", "sseqid", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"]

In [ ]:
blast_mk_output["qseqid"].nunique() # 1897
blast_mk_output

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
0,MK:rdhs_664198|chr8-10365156+10365425|reference,chr8,100.000,270,0,0,1,270,10365156,10365425,2.780000e-139,499.0
1,MK:tile_47691|chr20-20492859+20493129|reference,chr20,100.000,270,0,0,1,270,20492860,20493129,2.780000e-139,499.0
2,MK:tile_47699|chr22-42282878+42283148|reference,chr22,100.000,270,0,0,1,270,42282879,42283148,2.780000e-139,499.0
3,MK:CENPE|chr4-103198452-103198721|reference,chr4,100.000,270,0,0,1,270,103198721,103198452,2.780000e-139,499.0
4,MK:tile_45386|chr9-33290305+33290574|reference,chr9,100.000,270,0,0,1,270,33290305,33290574,2.780000e-139,499.0
...,...,...,...,...,...,...,...,...,...,...,...,...
528907,MK:tile_9894|chr12-94535162+94535431|A-T-113,chr12,99.630,270,1,0,1,270,94535162,94535431,1.290000e-137,494.0
528908,MK:tile_9894|chr12-94535162+94535431|G-A-105,chr12,99.630,270,1,0,1,270,94535162,94535431,1.290000e-137,494.0
528909,MK:tile_9894|chr12-94535162+94535431|G-C-105,chr12,99.630,270,1,0,1,270,94535162,94535431,1.290000e-137,494.0
528910,MK:tile_9894|chr12-94535162+94535431|ts102-108,chr12,97.407,270,7,0,1,270,94535162,94535431,1.310000e-127,460.0
528911,MK:tile_9894|chr12-94535162+94535431|ts110-116,chr12,97.407,270,7,0,1,270,94535162,94535431,1.310000e-127,460.0

In [ ]:
blast_mk_output_no_duplicates = blast_mk_output.sort_values(by="evalue").drop_duplicates(subset="qseqid", keep="first")

In [ ]:
def extract_sequence_from_header()

# Some sequences are variants which I have no variant region map for

# extract the regions from the header (start -1 ), to get_fasta and check which sequence start and end do not match (because of variants not all sequences will match anyway)

In [ ]:
blast_mk_output_no_duplicates

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
204206,MK:tile_24980|chr2-237427885+237428154|reference,chr2,100.000,270,0,0,1,270,237427885,237428154,2.780000e-139,499.0
168773,MK:tile_979|chr1-33342354+33342623|reference,chr1,100.000,270,0,0,1,270,33342354,33342623,2.780000e-139,499.0
168757,MK:tile_2712|chr1-157104702+157104971|reference,chr1,100.000,270,0,0,1,270,157104702,157104971,2.780000e-139,499.0
168758,MK:tile_47735|chr5-61408602+61408872|reference,chr5,100.000,270,0,0,1,270,61408603,61408872,2.780000e-139,499.0
168759,MK:YTHDC1|chr4-68350111-68350380|reference,chr4,100.000,270,0,0,1,270,68350380,68350111,2.780000e-139,499.0
...,...,...,...,...,...,...,...,...,...,...,...,...
528001,MK:tile_10173|chr12-113932853+113933122|LC18.35,chr12,100.000,84,0,0,157,240,113933009,113933092,6.930000e-36,156.0
528184,MK:tile_19098|chr18-25465453+25465722|LC16.47,chr18,90.164,122,8,3,97,216,25465549,25465668,6.930000e-36,156.0
528166,MK:tile_19098|chr18-25465453+25465722|LC16.1,chr18,78.475,223,34,9,49,264,25465501,25465716,3.250000e-29,134.0
528000,MK:tile_10173|chr12-113932853+113933122|LC18.3,chr12,77.419,248,40,13,1,240,113932853,113933092,3.250000e-29,134.0
527997,MK:tile_10173|chr12-113932853+113933122|LC18.2,chr12,74.558,283,46,17,1,270,113932853,113933122,3.290000e-19,100.0

In [ ]:
blast_mk_output_no_duplicates_not_perfect = blast_mk_output_no_duplicates.loc[blast_mk_output_no_duplicates["pident"] < 100]

In [ ]:
blast_mk_output_no_duplicates_not_perfect

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
528132,MK:tile_19098|chr18-25465452+25465722|G-A-172,chr18,99.630,270,1,0,1,270,25465453,25465722,1.290000e-137,494.0
528059,MK:tile_1451|chr1-52662913+52663182|C-G-149,chr1,99.630,270,1,0,1,270,52662913,52663182,1.290000e-137,494.0
528060,MK:tile_1451|chr1-52662913+52663182|C-T-145,chr1,99.630,270,1,0,1,270,52662913,52663182,1.290000e-137,494.0
528137,MK:tile_19098|chr18-25465452+25465722|G-A-262,chr18,99.630,270,1,0,1,270,25465453,25465722,1.290000e-137,494.0
528122,MK:tile_19098|chr18-25465452+25465722|C-T-97,chr18,99.630,270,1,0,1,270,25465453,25465722,1.290000e-137,494.0
...,...,...,...,...,...,...,...,...,...,...,...,...
528182,MK:tile_19098|chr18-25465453+25465722|LC16.3,chr18,79.921,254,23,13,1,240,25465453,25465692,1.490000e-37,161.0
528184,MK:tile_19098|chr18-25465453+25465722|LC16.47,chr18,90.164,122,8,3,97,216,25465549,25465668,6.930000e-36,156.0
528166,MK:tile_19098|chr18-25465453+25465722|LC16.1,chr18,78.475,223,34,9,49,264,25465501,25465716,3.250000e-29,134.0
528000,MK:tile_10173|chr12-113932853+113933122|LC18.3,chr12,77.419,248,40,13,1,240,113932853,113933092,3.250000e-29,134.0
527997,MK:tile_10173|chr12-113932853+113933122|LC18.2,chr12,74.558,283,46,17,1,270,113932853,113933122,3.290000e-19,100.0

In [ ]:
# Regex to capture the chromosome, start, and end
pattern = re.compile(r"chr(\d+)-(\d+)[+-](\d+)")

for s in strings:
    match = pattern.search(s)
    if match:
        chrom, start, end = match.groups()
        print(f"Chromosome: {chrom}, Start: {start}, End: {end}")

In [ ]:
blast_mk_output_filtered = blast_mk_output.loc[blast_mk_output["length"] >= 270].copy()

In [ ]:
blast_mk_output_filtered["qseqid"].nunique()

1829

In [ ]:
blast_mk_output_filtered.

In [ ]:
makeblastdb -in /data/cephfs-1/work/projects/cubit/current/static_data/reference/hg38/ucsc/hg38.fa -dbtype nucl -out human_ref
blastn -query /data/cephfs-1/scratch/groups/kircher/users/kisa11_c/tmp/80k_MK_sequences_for_hg38_blast.fa -db human_ref -out mk_80k_blastn_hg38_out.txt -outfmt 6 -num_threads 4

In [ ]:
blastn -query /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/80k_MK_sequences_for_hg38_blast.fa -db /home/kisa/coding/80K_MPRA/reference_genome_match/hg38.fa -out mk_80k_blastn_hg38_out.txt -outfmt 6 -num_threads 4
blastn -query /data/cephfs-1/scratch/groups/kircher/users/kisa11_c/tmp/80k_MK_sequences_for_hg38_blast.fa -db /data/cephfs-1/work/projects/cubit/18.12/static_data/reference/hg38/ucsc/hg38.fa -out mk_80k_blastn_hg38_out.txt -outfmt 6 -num_threads 4