### Use the additional info about the variants to annotate the significant variants
- from UKBB GWAS Imputed v3 - File Manifest Release 20180731: https://docs.google.com/spreadsheets/d/1kvPoupSzsSFBNSztMzl04xMoSC3Kcx3CrjVf4yBmESU/edit?gid=227859291#gid=227859291
- current example: coffe consumption
- downloading the data and unzipping it
```bash
cd /data/cephfs-1/scratch/groups/kircher/MPRA/IGVF_Y1_design/projects/80K_MPRA/ludwig_variant_annotations
# variant metadata
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/annotations/variants.tsv.bgz -O variants.tsv.bgz

# coffee consumption
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/100240.gwas.imputed_v3.both_sexes.tsv.bgz -O 100240.gwas.imputed_v3.both_sexes.tsv.bgz

# unzip
mv variants.tsv.bgz variants.tsv.gz
mv 100240.gwas.imputed_v3.both_sexes.tsv.bgz  100240.gwas.imputed_v3.both_sexes.tsv.gz
gunzip variants.tsv.gz
gunzip 100240.gwas.imputed_v3.both_sexes.tsv.gz
```

### TODOs:
- combine the varinat information of both cell-types and generate a upset plot of that information
- focus on one cell-type and annotate the information

### One table as example:

In [12]:
import os
import pandas as pd
import yaml


# load helpful functions
# import sys
# sys.path.append('../../00_helpful_functions')
# import helpful_functions as hf
# reload(hf)
# config
config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/global80K_config.yaml"
with open(config_path) as conf:
    config = yaml.load(conf, Loader=yaml.FullLoader)
    conf.close()

directory_ludwig_variants = "/data/cephfs-1/scratch/groups/kircher/MPRA/IGVF_Y1_design/projects/80K_MPRA/ludwig_variant_annotations"

In [ ]:
variant_metadata_path = os.path.join(directory_ludwig_variants, "variants.tsv")
ludwig_variant_metadata = pd.read_csv(variant_metadata_path, sep="\t")
ludwig_variant_metadata
# took 4m30s

/tmp/ipykernel_20088/30424099.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  ludwig_variant_metadata = pd.read_csv(variant_metadata_path, sep="\t")

,variant,chr,pos,ref,alt,rsid,varid,consequence,consequence_category,info,...,p_hwe,n_called,n_not_called,n_hom_ref,n_het,n_hom_var,n_non_ref,r_heterozygosity,r_het_hom_var,r_expected_het_frequency
0,1:15791:C:T,1,15791,C,T,rs547522712,1:15791_C_T,splice_region_variant,missense,0.861678,...,0.500000,361194,0,361194,0,0,0,0.000000,NaN,0.000000
1,1:69487:G:A,1,69487,G,A,rs568226429,1:69487_G_A,missense_variant,missense,0.956975,...,0.500004,361194,0,361190,4,0,4,0.000011,NaN,0.000011
2,1:69569:T:C,1,69569,T,C,rs2531267,1:69569_T_C,missense_variant,missense,0.831664,...,0.506315,361194,0,361058,136,0,136,0.000377,NaN,0.000376
3,1:139853:C:T,1,139853,C,T,rs533633326,1:139853_C_T,splice_region_variant,missense,0.985255,...,0.500004,361194,0,361190,4,0,4,0.000011,NaN,0.000011
4,1:692794:CA:C,1,692794,CA,C,1:692794_CA_C,1:692794_CA_C,upstream_gene_variant,non_coding,0.824483,...,0.031437,361188,6,286823,70224,4141,74365,0.194425,16.95820,0.193734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13791462,X:154929412:C:T,X,154929412,C,T,rs557132,X:154929412_C_T,intergenic_variant,non_coding,0.995733,...,0.534121,194174,0,110480,72040,11654,83694,0.371007,6.18157,0.370483
13791463,X:154929637:CT:C,X,154929637,CT,C,rs762503228,X:154929637_CT_C,intergenic_variant,non_coding,0.952571,...,0.454552,194174,0,116924,67580,9670,77250,0.348038,6.98862,0.347450
13791464,X:154929952:CAA:C,X,154929952,CAA,C,rs775521832,X:154929952_CAA_C,intergenic_variant,non_coding,0.899690,...,0.239567,194173,1,110711,71943,11519,83462,0.370510,6.24559,0.369520
13791465,X:154930230:A:G,X,154930230,A,G,rs781880,X:154930230_A_G,intergenic_variant,non_coding,0.994943,...,0.547746,194174,0,110089,72301,11784,84085,0.372352,6.13552,0.371845
13791466,X:154930487:T:A,X,154930487,T,A,rs781879,X:154930487_T_A,intergenic_variant,non_coding,0.855165,...,0.003683,194174,0,187060,7023,91,7114,0.036169,77.17580,0.036418

In [6]:
ludwig_variant_metadata.dtypes

variant                      object
chr                          object
pos                           int64
ref                          object
alt                          object
rsid                         object
varid                        object
consequence                  object
consequence_category         object
info                        float64
call_rate                   float64
AC                            int64
AF                          float64
minor_allele                 object
minor_AF                    float64
p_hwe                       float64
n_called                      int64
n_not_called                  int64
n_hom_ref                     int64
n_het                         int64
n_hom_var                     int64
n_non_ref                     int64
r_heterozygosity            float64
r_het_hom_var               float64
r_expected_het_frequency    float64
dtype: object

In [4]:
# 100240	Coffee consumed	http://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=100240	female	100240.gwas.imputed_v3.female.tsv.bgz	wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/100240.gwas.imputed_v3.female.tsv.bgz -O 100240.gwas.imputed_v3.female.tsv.bgz	https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/100240.gwas.imputed_v3.female.tsv.bgz	https://www.dropbox.com/s/puvsy1umeimdn85/100240.gwas.imputed_v3.female.tsv.bgz?dl=0	ec13033d5dd3ffce9b465ad552b19c8c
coffee_consumed_path = os.path.join(directory_ludwig_variants, "100240.gwas.imputed_v3.both_sexes.tsv")
coffee_consumed_df = pd.read_csv(coffee_consumed_path, sep="\t")

In [5]:
coffee_consumed_df

,variant,minor_allele,minor_AF,expected_case_minor_AC,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,pval
0,1:15791:C:T,T,0.000000,0.00000,True,51427,0.00000,0.000000,NaN,NaN,NaN,NaN
1,1:69487:G:A,A,0.000020,1.48165,True,51427,2.09804,0.098039,-0.736282,0.319522,-2.304320,0.021209
2,1:69569:T:C,C,0.000180,13.08560,True,51427,18.52940,11.502000,-0.101841,0.109721,-0.928180,0.353318
3,1:139853:C:T,T,0.000020,1.47611,True,51427,2.09020,0.090196,-0.737276,0.319524,-2.307420,0.021035
4,1:692794:CA:C,C,0.112100,8142.50000,False,51427,11529.90000,8182.380000,0.002915,0.004934,0.590769,0.554678
...,...,...,...,...,...,...,...,...,...,...,...,...
13791462,X:154929412:C:T,T,0.243258,17669.30000,False,51427,25020.10000,17539.600000,-0.004337,0.002731,-1.588260,0.112233
13791463,X:154929637:CT:C,C,0.227821,16548.00000,False,51427,23432.30000,16515.800000,-0.000880,0.002845,-0.309334,0.757069
13791464,X:154929952:CAA:C,C,0.237429,17245.90000,False,51427,24420.50000,17125.800000,-0.004350,0.002873,-1.513970,0.130041
13791465,X:154930230:A:G,G,0.243826,17710.60000,False,51427,25078.50000,17581.300000,-0.004285,0.002730,-1.569820,0.116462
13791466,X:154930487:T:A,A,0.018984,1378.95000,False,51427,1952.62000,1364.620000,-0.006676,0.009492,-0.703349,0.481841

Load the 80k MPRA variant information
- get only alt (because the spdi column is then one element per list)
- merge the lists using the elementarized spdi column

In [13]:
variant_input_name = "NGN2_variants_metadata_bcalm_2025_bbmap_normalized_counts"
variant_info_df = pd.read_csv(config['files']['creating'][variant_input_name], sep="\t")
variant_info_df

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label
0,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GTCCCAGCTCCCCACTGATGTGAAAGGTGGTGGTGAGTTAACAGCT...,GTCCCAGCTCCCCACTGATGTGAAAGGTGGTGGTGAGTTAACAGCT...,[83],False,NaN,NaN,0.022133,0.131536,5.965362e-07,0.190591,cardiac_neuro_cava_random
1,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTGATCTGCCCTGTCCGTGACGCTTCTGCTCAGTAGCTGAGCACG...,CCTGATCTGCCCTGTCCGTGACGCTTCTGCTCAGTAGCTGAGCACG...,[181],False,NaN,NaN,NaN,NaN,NaN,NaN,cardiac_neuro_cava_random
2,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCTGGGTGACCCGGAGAACACCAAGGCTGTGAGAAATGGGAGGC...,CCTCTGGGTGACCCGGAGAACACCAAGGCTGTGAGAAATGGGATGC...,[43],False,NaN,NaN,NaN,NaN,NaN,NaN,cardiac_neuro_cava_random
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],True,0.944787,-0.043372,1.000000,-0.068107,1.000000e+00,-0.072051,cardiac_neuro_cava_random
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],True,0.926799,-0.036392,1.000000,0.001944,1.000000e+00,-0.005889,cardiac_neuro_cava_random
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47039,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,[136],True,0.069025,0.177548,1.000000,-0.037515,1.000000e+00,-0.012714,C_positive_heart_CAD
47040,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,[136],True,0.220035,-0.313776,0.042527,-0.087468,7.038279e-05,-0.102879,C_positive_heart_CAD
47041,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,[136],True,0.341678,0.214433,1.000000,-0.027086,1.000000e+00,0.002929,C_positive_heart_CAD
47042,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,[136],True,0.775080,0.089574,1.000000,-0.070829,1.000000e+00,-0.067582,C_positive_heart_CAD
47043,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,[136],True,0.829395,-0.099302,1.000000,0.018869,1.000000e+00,0.002536,C_positive_heart_CAD

In [14]:
# filter for bcalm_variant_effect_data_exists
variant_info_df_filtered = variant_info_df.loc[variant_info_df['bcalm_variant_effect_data_exists'] == True].copy()
variant_info_df_filtered

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],True,0.944787,-0.043372,1.000000,-0.068107,1.00000,-0.072051,cardiac_neuro_cava_random
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],True,0.926799,-0.036392,1.000000,0.001944,1.00000,-0.005889,cardiac_neuro_cava_random
6,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[71],True,0.779710,-0.130556,1.000000,-0.053109,1.00000,-0.065999,cardiac_neuro_cava_random
7,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[144],True,0.953076,-0.034817,1.000000,-0.053109,1.00000,-0.074918,cardiac_neuro_cava_random
8,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[183],True,0.632794,-0.167928,1.000000,-0.053109,1.00000,-0.060033,cardiac_neuro_cava_random
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47039,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,[136],True,0.069025,0.177548,1.000000,-0.037515,1.00000,-0.012714,C_positive_heart_CAD
47040,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,[136],True,0.220035,-0.313776,0.042527,-0.087468,0.00007,-0.102879,C_positive_heart_CAD
47041,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,[136],True,0.341678,0.214433,1.000000,-0.027086,1.00000,0.002929,C_positive_heart_CAD
47042,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,[136],True,0.775080,0.089574,1.000000,-0.070829,1.00000,-0.067582,C_positive_heart_CAD
47043,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,[136],True,0.829395,-0.099302,1.000000,0.018869,1.00000,0.002536,C_positive_heart_CAD

In [15]:
# load metadata table to annotate the spdi info
metadata_80k = pd.read_csv("/data/cephfs-2/unmirrored/groups/kircher/MPRA/IGVF_Y1_design/design/mpra_metadata_format/MPRA_80215.metadata.tsv.gz", sep="\t")
import ast
# column names
col_name = 'name'
col_header = 'name'
col_sequence = 'sequence'
col_category = 'category'
col_class = 'class'
col_source = 'source'
col_ref = 'ref'
col_chr = 'chr'
col_start = 'start'
col_end = 'end'
col_strand = 'strand'
col_variant_class = 'variant_class'
col_variant_pos = 'variant_pos'
col_SPDI = 'SPDI'
col_allele = 'allele'
col_info = 'info'


list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

# Function to safely evaluate string representations of lists
def safe_eval(x):
    if pd.isna(x):
        return None
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return x


# use safe eval on list
# Apply the safe_eval function to the specified columns
for col in list_columns:
    metadata_80k[col] = metadata_80k[col].apply(safe_eval)

metadata_80k

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info
0,GC_Mohlke:REF_NC000001.11|159752292|A|G|Mohlke...,ATACATCCTTTAATTTGTTCCTACATCTTGCTTGGATTTTCCCCTG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,159752058.0,159752328.0,+,[SNV],[234],[NC_000001.11:159752292:A:G],[ref],NaN
1,GC_Mohlke:REF_NC000001.11|230158967|C|A|Mohlke...,TGTGTCTGGTGAGGTTGCTGACACTGCTTTTGGATGAGAGAGAGAG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159023.0,230159293.0,+,[SNV],[145],[NC_000001.11:230159168:C:T],[ref],NaN
2,GC_Mohlke:REF_NC000001.11|230158967|C|A|Mohlke...,GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159136.0,230159406.0,+,"[SNV, indel]","[32, 192]","[NC_000001.11:230159168:C:T, NC_000001.11:2301...","[ref, ref]",NaN
3,GC_Mohlke:ALT_NC000001.11|230158967|C|A|Mohlke...,GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159136.0,230159406.0,+,[indel],[192],[NC_000001.11:230159328:TCTTAAAGTGTTCAGCACTCCC:T],[alt],NaN
4,GC_Mohlke:REF_NC000001.11|230161389|C|T|Mohlke...,CCTCAACTCTCCACATGCCCCAGTAGCATAGACCAGCTTCCTTACA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230161269.0,230161539.0,+,[SNV],[120],[NC_000001.11:230161389:C:T],[ref],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80210,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element inactive control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN
80211,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element inactive control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN
80212,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element inactive control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN
80213,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element inactive control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN
80214,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element inactive control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN

In [16]:
variant_info_df_filtered

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],True,0.944787,-0.043372,1.000000,-0.068107,1.00000,-0.072051,cardiac_neuro_cava_random
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],True,0.926799,-0.036392,1.000000,0.001944,1.00000,-0.005889,cardiac_neuro_cava_random
6,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[71],True,0.779710,-0.130556,1.000000,-0.053109,1.00000,-0.065999,cardiac_neuro_cava_random
7,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[144],True,0.953076,-0.034817,1.000000,-0.053109,1.00000,-0.074918,cardiac_neuro_cava_random
8,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[183],True,0.632794,-0.167928,1.000000,-0.053109,1.00000,-0.060033,cardiac_neuro_cava_random
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47039,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,[136],True,0.069025,0.177548,1.000000,-0.037515,1.00000,-0.012714,C_positive_heart_CAD
47040,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,[136],True,0.220035,-0.313776,0.042527,-0.087468,0.00007,-0.102879,C_positive_heart_CAD
47041,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,[136],True,0.341678,0.214433,1.000000,-0.027086,1.00000,0.002929,C_positive_heart_CAD
47042,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,[136],True,0.775080,0.089574,1.000000,-0.070829,1.00000,-0.067582,C_positive_heart_CAD
47043,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,[136],True,0.829395,-0.099302,1.000000,0.018869,1.00000,0.002536,C_positive_heart_CAD

In [17]:

variant_info_filtered_spdi = variant_info_df_filtered.merge(metadata_80k[[col_name, col_SPDI]], left_on='ALT', right_on=col_name, how='inner')

# test if the shape is the same
if variant_info_filtered_spdi.shape[0] == variant_info_df_filtered.shape[0]:
    print("The shapes match, the merge was successful.")

The shapes match, the merge was successful.

In [18]:
variant_info_filtered_spdi

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label,name,SPDI
0,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],True,0.944787,-0.043372,1.000000,-0.068107,1.00000,-0.072051,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2192365:T:G]
1,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],True,0.926799,-0.036392,1.000000,0.001944,1.00000,-0.005889,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2193141:G:A]
2,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[71],True,0.779710,-0.130556,1.000000,-0.053109,1.00000,-0.065999,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2197933:C:A]
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[144],True,0.953076,-0.034817,1.000000,-0.053109,1.00000,-0.074918,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2198006:C:G]
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[183],True,0.632794,-0.167928,1.000000,-0.053109,1.00000,-0.060033,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2198045:G:A]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38178,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,[136],True,0.069025,0.177548,1.000000,-0.037515,1.00000,-0.012714,C_positive_heart_CAD,C_positive_heart_CAD:ALT_rs7865618_rs7865618,[NC_000009.12:22031005:G:A]
38179,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,[136],True,0.220035,-0.313776,0.042527,-0.087468,0.00007,-0.102879,C_positive_heart_CAD,C_positive_heart_CAD:ALT_rs4977757_rs4977757,[NC_000009.12:22094330:A:G]
38180,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,[136],True,0.341678,0.214433,1.000000,-0.027086,1.00000,0.002929,C_positive_heart_CAD,C_positive_heart_CAD:ALT_rs1537373_rs1537373,[NC_000009.12:22103341:T:G]
38181,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,[136],True,0.775080,0.089574,1.000000,-0.070829,1.00000,-0.067582,C_positive_heart_CAD,C_positive_heart_CAD:ALT_rs10811656_rs10811656,[NC_000009.12:22124472:C:T]
38182,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,[136],True,0.829395,-0.099302,1.000000,0.018869,1.00000,0.002536,C_positive_heart_CAD,C_positive_heart_CAD:ALT_rs507666_rs507666,[NC_000009.12:133273982:A:G]

In [19]:
variant_info_filtered_spdi['ALT'].nunique()

38183

In [20]:
# from list of spdis to sinlge element spdi columns
variant_info_filtered_spdi["SPDI_elem"] = variant_info_filtered_spdi[col_SPDI].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)
variant_info_filtered_spdi["SPDI_elem"].value_counts()

SPDI_elem
NC_000007.14:156791471:C:G    9
NC_000007.14:156791471:C:T    9
NC_000007.14:156791473:G:A    9
NC_000007.14:156791479:G:A    9
NC_000007.14:156791546:A:G    8
                             ..
NC_000015.10:66761647:C:T     1
NC_000015.10:66761734:A:G     1
NC_000015.10:66761811:C:T     1
NC_000015.10:67013831:G:A     1
NC_000015.10:66760484:C:T     1
Name: count, Length: 37949, dtype: int64

In [21]:
variant_info_filtered_spdi_tested = variant_info_filtered_spdi.loc[variant_info_filtered_spdi['label'] == "cardiac_neuro_cava_random"].copy()
variant_info_filtered_spdi_tested

# number of variants tested multiple times
number_of_variants = variant_info_filtered_spdi_tested["SPDI_elem"].value_counts().reset_index()
number_of_variants.columns = ['SPDI', 'number_of_variants']

number_of_variants.loc[number_of_variants['number_of_variants'] > 1].shape[0] # 131

131

In [22]:
# how many SPDIs are duplicated
variant_info_filtered_spdi.loc[variant_info_filtered_spdi["SPDI_elem"] == "NC_000007.14:156791471:C:G"]

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label,name,SPDI,SPDI_elem
38057,GC_Mendelian_variants:ALT_chr7:156791413A>C|SH...,GC_Mendelian_variants:REF_chr7:156791413A>C|SHH,GC_Mendelian_variants:ALT_chr7:156791413A>C|SH...,CAGCACTTCCTTAATCACTCATTTCCAACAATTTATGGATCATCAG...,CAGCACTTCCTTAATCACTCATTTCCAACAATTTATGGATCATCAG...,[194],True,0.856389,0.056221,1.000000,-0.013708,1.000000,-0.011810,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791413A>C|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38058,GC_Mendelian_variants:ALT_chr7:156791459T>C|SH...,GC_Mendelian_variants:REF_chr7:156791459T>C|SHH,GC_Mendelian_variants:ALT_chr7:156791459T>C|SH...,TGGCAAAAAACGAGCAAAAATAATGAAAGAATGCAATGAAAGCTCG...,TGGCAAAAAACGAGCAAAAATAATGAAAGAATGCAATGAAAGCTCG...,[148],True,0.875129,0.053071,1.000000,0.009024,1.000000,0.012502,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791459T>C|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38059,GC_Mendelian_variants:ALT_chr7:156791474G>A|SH...,GC_Mendelian_variants:REF_chr7:156791474G>A|SHH,GC_Mendelian_variants:ALT_chr7:156791474G>A|SH...,AAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTG...,AAAAATAATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTG...,[133],True,0.954396,-0.021555,1.000000,0.008693,1.000000,0.019434,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791474G>A|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38060,GC_Mendelian_variants:ALT_chr7:156791480G>A|SH...,GC_Mendelian_variants:REF_chr7:156791480G>A|SHH,GC_Mendelian_variants:ALT_chr7:156791480G>A|SH...,AATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTGGACTTC...,AATGAAAGAATGCAATGAAAGCTCGTGGAGACAGAGGCTGGACTTC...,[127],True,0.929460,-0.031729,1.000000,0.018209,1.000000,0.014658,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791480G>A|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38061,GC_Mendelian_variants:ALT_chr7:156791542A>C|SH...,GC_Mendelian_variants:REF_chr7:156791542A>C|SHH,GC_Mendelian_variants:ALT_chr7:156791542A>C|SH...,TCTTTAAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAA...,TCTTTAAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAA...,[65],True,0.869044,-0.058696,1.000000,-0.003807,1.000000,-0.014785,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791542A>C|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38062,GC_Mendelian_variants:ALT_chr7:156791547A>G|SH...,GC_Mendelian_variants:REF_chr7:156791547A>G|SHH,GC_Mendelian_variants:ALT_chr7:156791547A>G|SH...,AAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAAGTCAT...,AAGATGGAGGCCTGATACAAATTAGCCACTGGGGGGAAAAAGTCAT...,[60],True,0.798427,0.061689,1.000000,-0.007136,1.000000,0.000707,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791547A>G|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38063,GC_Mendelian_variants:ALT_chr7:156791571T>A|SH...,GC_Mendelian_variants:REF_chr7:156791571T>A|SHH,GC_Mendelian_variants:ALT_chr7:156791571T>A|SH...,GCCACTGGGGGGAAAAAGTCATCTGGTCATAAAATACAGTACAAGG...,GCCACTGGGGGGAAAAAGTCATCTGGTCATAAAATAGAGTACAAGG...,[36],True,0.968341,-0.011291,1.000000,0.017619,1.000000,0.015574,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791571T>A|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38064,GC_Mendelian_variants:ALT_chr7:156791579C>T|SH...,GC_Mendelian_variants:REF_chr7:156791579C>T|SHH,GC_Mendelian_variants:ALT_chr7:156791579C>T|SH...,GGGGAAAAAGTCATCTGGTCATAAAATACAGTACAAGGTCACTTTT...,GGGGAAAAAGTCATCTGGTCATAAAATAGAGTACAAGGTCACTTTT...,[28],True,0.887726,0.041087,1.000000,-0.001121,1.000000,0.004857,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791579C>T|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G
38065,GC_Mendelian_variants:ALT_chr7:156791581A>G|SH...,GC_Mendelian_variants:REF_chr7:156791581A>G|SHH,GC_Mendelian_variants:ALT_chr7:156791581A>G|SH...,GGAAAAAGTCATCTGGTCATAAAATACAGTACAAGGTCACTTTTAT...,GGAAAAAGTCATCTGGTCATAAAATAGAGTACAAGGTCACTTTTAT...,[26],True,0.977337,-0.015694,0.000041,-0.099476,0.000167,-0.097064,GC_Mendelian_variants,GC_Mendelian_variants:ALT_chr7:156791581A>G|SH...,[NC_000007.14:156791471:C:G],NC_000007.14:156791471:C:G

Focus on the tested variants of interest

In [23]:
variant_info_filtered_spdi_tested

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label,name,SPDI,SPDI_elem
0,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],True,0.944787,-0.043372,1.000000,-0.068107,1.000000,-0.072051,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2192365:T:G],NC_000001.11:2192365:T:G
1,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],True,0.926799,-0.036392,1.000000,0.001944,1.000000,-0.005889,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2193141:G:A],NC_000001.11:2193141:G:A
2,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[71],True,0.779710,-0.130556,1.000000,-0.053109,1.000000,-0.065999,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2197933:C:A],NC_000001.11:2197933:C:A
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[144],True,0.953076,-0.034817,1.000000,-0.053109,1.000000,-0.074918,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2198006:C:G],NC_000001.11:2198006:C:G
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[183],True,0.632794,-0.167928,1.000000,-0.053109,1.000000,-0.060033,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,[NC_000001.11:2198045:G:A],NC_000001.11:2198045:G:A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37865,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,GGAGCTCTGCCTCACCCCACCTGGCCCCAATTGTCCAGCTTGTAGA...,GGAGCTCTGCCTCACCCCACCTGGCCCCAATTGTCCAGCTTGTAGA...,[64],True,0.911154,-0.076406,0.015993,0.100370,0.451154,0.065547,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,[NC_000023.11:154545205:A:G],NC_000023.11:154545205:A:G
37866,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,ATGTCTGAATTCACCTCCAAATAATGGGAAAACTCCTAGGTATATA...,ATGTCTGAATTCACCTCCAAATAATGGGAAAACTCCTAGGTATATA...,[149],True,0.748684,-0.153448,1.000000,-0.080632,0.091747,-0.090558,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,[NC_000023.11:154549922:T:G],NC_000023.11:154549922:T:G
37867,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCCC...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCCC...,[126],True,0.989551,0.007846,0.409652,0.056209,0.436290,0.052674,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,[NC_000023.11:154552288:C:T],NC_000023.11:154552288:C:T
37868,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCCC...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCTC...,[44],True,0.514030,-0.243036,0.409652,0.056209,1.000000,0.016824,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,[NC_000023.11:154552370:G:A],NC_000023.11:154552370:G:A
37869,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCCC...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTCCCC...,[42],True,0.984694,-0.013075,0.409652,0.056209,0.099689,0.071148,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,[NC_000023.11:154552372:A:G],NC_000023.11:154552372:A:G

In [24]:
chrom_2_refseq = {"1": "NC_000001.11",
    "2": "NC_000002.12",
    "3": "NC_000003.12",
    "4": "NC_000004.12",
    "5": "NC_000005.10",
    "6": "NC_000006.12",
    "7": "NC_000007.14",
    "8": "NC_000008.11",
    "9": "NC_000009.12",
    "10": "NC_000010.11",
    "11": "NC_000011.10",
    "12": "NC_000012.12",
    "13": "NC_000013.11",
    "14": "NC_000014.9",
    "15": "NC_000015.10",
    "16": "NC_000016.10",
    "17": "NC_000017.11",
    "18": "NC_000018.10",
    "19": "NC_000019.10",
    "20": "NC_000020.11",
    "21": "NC_000021.9",
    "22": "NC_000022.11",
    "X": "NC_000023.11",
    "Y": "NC_000024.10"}

refseq_2_chrom = {v: k for k, v in chrom_2_refseq.items()}
refseq_2_chrom

{'NC_000001.11': '1',
 'NC_000002.12': '2',
 'NC_000003.12': '3',
 'NC_000004.12': '4',
 'NC_000005.10': '5',
 'NC_000006.12': '6',
 'NC_000007.14': '7',
 'NC_000008.11': '8',
 'NC_000009.12': '9',
 'NC_000010.11': '10',
 'NC_000011.10': '11',
 'NC_000012.12': '12',
 'NC_000013.11': '13',
 'NC_000014.9': '14',
 'NC_000015.10': '15',
 'NC_000016.10': '16',
 'NC_000017.11': '17',
 'NC_000018.10': '18',
 'NC_000019.10': '19',
 'NC_000020.11': '20',
 'NC_000021.9': '21',
 'NC_000022.11': '22',
 'NC_000023.11': 'X',
 'NC_000024.10': 'Y'}

In [25]:
variant_info_filtered_spdi_tested['SPDI_elem_chrom'] = variant_info_filtered_spdi_tested['SPDI_elem'].apply(lambda x: f"{refseq_2_chrom[x.split(':')[0]]}:{':'.join(x.split(':')[1:])}" if isinstance(x, str) else None)

In [26]:
variant_info_filtered_spdi_tested['SPDI_elem']

0          NC_000001.11:2192365:T:G
1          NC_000001.11:2193141:G:A
2          NC_000001.11:2197933:C:A
3          NC_000001.11:2198006:C:G
4          NC_000001.11:2198045:G:A
                    ...
37865    NC_000023.11:154545205:A:G
37866    NC_000023.11:154549922:T:G
37867    NC_000023.11:154552288:C:T
37868    NC_000023.11:154552370:G:A
37869    NC_000023.11:154552372:A:G
Name: SPDI_elem, Length: 37870, dtype: object

In [27]:
variant_info_filtered_spdi_tested['SPDI_elem_chrom']

0          1:2192365:T:G
1          1:2193141:G:A
2          1:2197933:C:A
3          1:2198006:C:G
4          1:2198045:G:A
              ...
37865    X:154545205:A:G
37866    X:154549922:T:G
37867    X:154552288:C:T
37868    X:154552370:G:A
37869    X:154552372:A:G
Name: SPDI_elem_chrom, Length: 37870, dtype: object

In [28]:
variant_info_filtered_spdi_tested.columns

Index(['ID', 'REF', 'ALT', 'ref_sequence', 'alt_sequence', 'variant_pos',
       'bcalm_variant_effect_data_exists',
       'bcalm_variant_effect_adjusted_p_value',
       'bcalm_variant_effect_log_ratio_activity',
       'bcalm_reference_adjusted_p_value',
       'bcalm_reference_log_ratio_activity',
       'bcalm_alternative_adjusted_p_value',
       'bcalm_alternative_log_ratio_activity', 'label', 'name', 'SPDI',
       'SPDI_elem', 'SPDI_elem_chrom'],
      dtype='object')

In [ ]:
# write to file:
directory_path = "/data/cephfs-1/scratch/groups/kircher/MPRA/IGVF_Y1_design/projects/80K_MPRA/ludwig_variant_annotations/download_testing"
output_path = os.path.join(directory_path, "80k_neuro_variant_info_filtered_spdi_tested.tsv")
variant_info_filtered_spdi_tested.to_csv(output_path, sep="\t", index=False)

In [68]:
coffee_consumed_df

,variant,minor_allele,minor_AF,expected_case_minor_AC,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,pval
0,1:15791:C:T,T,0.000000,0.00000,True,51427,0.00000,0.000000,NaN,NaN,NaN,NaN
1,1:69487:G:A,A,0.000020,1.48165,True,51427,2.09804,0.098039,-0.736282,0.319522,-2.304320,0.021209
2,1:69569:T:C,C,0.000180,13.08560,True,51427,18.52940,11.502000,-0.101841,0.109721,-0.928180,0.353318
3,1:139853:C:T,T,0.000020,1.47611,True,51427,2.09020,0.090196,-0.737276,0.319524,-2.307420,0.021035
4,1:692794:CA:C,C,0.112100,8142.50000,False,51427,11529.90000,8182.380000,0.002915,0.004934,0.590769,0.554678
...,...,...,...,...,...,...,...,...,...,...,...,...
13791462,X:154929412:C:T,T,0.243258,17669.30000,False,51427,25020.10000,17539.600000,-0.004337,0.002731,-1.588260,0.112233
13791463,X:154929637:CT:C,C,0.227821,16548.00000,False,51427,23432.30000,16515.800000,-0.000880,0.002845,-0.309334,0.757069
13791464,X:154929952:CAA:C,C,0.237429,17245.90000,False,51427,24420.50000,17125.800000,-0.004350,0.002873,-1.513970,0.130041
13791465,X:154930230:A:G,G,0.243826,17710.60000,False,51427,25078.50000,17581.300000,-0.004285,0.002730,-1.569820,0.116462
13791466,X:154930487:T:A,A,0.018984,1378.95000,False,51427,1952.62000,1364.620000,-0.006676,0.009492,-0.703349,0.481841

In [69]:
variant_info_filtered_spdi_tested_coffee_consumed = variant_info_filtered_spdi_tested.merge(coffee_consumed_df[['variant', 'minor_AF', 'tstat', 'pval']], left_on='SPDI_elem_chrom', right_on='variant', how='left').copy()
# took: 20s

In [70]:
print("Number of tested variants", variant_info_filtered_spdi_tested.shape[0])
print("Number of variants with coffee consumed data", variant_info_filtered_spdi_tested_coffee_consumed.loc[~variant_info_filtered_spdi_tested_coffee_consumed['pval'].isna()].shape[0])

# variants with coffee consumed data
variant_info_filtered_spdi_tested_coffee_consumed_annotated = variant_info_filtered_spdi_tested_coffee_consumed.loc[~variant_info_filtered_spdi_tested_coffee_consumed['pval'].isna()].copy()

Number of tested variants 37870
Number of variants with coffee consumed data 31

In [71]:
variant_info_filtered_spdi_tested_coffee_consumed_annotated

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,...,bcalm_alternative_log_ratio_activity,label,name,SPDI,SPDI_elem,SPDI_elem_chrom,variant,minor_AF,tstat,pval
1514,cardiac_neuro_cava_random:ALT_SZT2|ENSG0000019...,cardiac_neuro_cava_random:REF_SZT2|ENSG0000019...,cardiac_neuro_cava_random:ALT_SZT2|ENSG0000019...,AAGAGTGAACAAGGAAGTTGACGTTTGAGTGGCTCAGAAGAAGTGA...,AAGAGTGAACAAGGAAGTTGACGTTTGAGTGGCTCAGAAGAAGTGA...,[150],True,0.679913,-0.148576,1.000000e+00,...,-0.021683,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_SZT2|ENSG0000019...,[NC_000001.11:43495344:T:G],NC_000001.11:43495344:T:G,1:43495344:T:G,1:43495344:T:G,0.005896,-1.067910,0.285566
2060,cardiac_neuro_cava_random:ALT_CNN3|ENSG0000011...,cardiac_neuro_cava_random:REF_CNN3|ENSG0000011...,cardiac_neuro_cava_random:ALT_CNN3|ENSG0000011...,GGGCCTCAGTGTTAACCTTCCCAGGTTCAGATCCCAGCTTTACCCC...,GGGCCTCAGTGTTAACCTTCCCAGGTTCAGATCCCAGCTTTACCCC...,[167],True,0.908745,0.047040,4.273634e-05,...,-0.095507,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_CNN3|ENSG0000011...,[NC_000001.11:94856263:T:C],NC_000001.11:94856263:T:C,1:94856263:T:C,1:94856263:T:C,0.436663,-0.039048,0.968852
5580,cardiac_neuro_cava_random:ALT_MYPN|ENSG0000013...,cardiac_neuro_cava_random:REF_MYPN|ENSG0000013...,cardiac_neuro_cava_random:ALT_MYPN|ENSG0000013...,GGGACTACAGGCACGTGCCACTACTCGTGGCTAATTTTTGTGTTAT...,GGGACTACAGGCACGTGCCACTACTCGTGGCTAATTTTTGTGTTAT...,[75],True,0.463365,-0.134311,1.000000e+00,...,-0.017654,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_MYPN|ENSG0000013...,[NC_000010.11:68180393:C:T],NC_000010.11:68180393:C:T,10:68180393:C:T,10:68180393:C:T,0.317659,-1.496620,0.134498
7484,cardiac_neuro_cava_random:ALT_KMT5B|ENSG000001...,cardiac_neuro_cava_random:REF_KMT5B|ENSG000001...,cardiac_neuro_cava_random:ALT_KMT5B|ENSG000001...,GCCAGCCGCCCAGAGGGGCCACTGGGAAAGCCGGGTACGCCCCACT...,GCCAGCCGCCCAGAGGGGCCACTGGGAAAGCCGGGTACGCCCCACT...,[150],True,0.916749,0.061257,1.000000e+00,...,0.011800,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_KMT5B|ENSG000001...,[NC_000011.10:68216756:C:T],NC_000011.10:68216756:C:T,11:68216756:C:T,11:68216756:C:T,0.263960,1.404810,0.160084
10035,cardiac_neuro_cava_random:ALT_MAX|ENSG00000125...,cardiac_neuro_cava_random:REF_MAX|ENSG00000125...,cardiac_neuro_cava_random:ALT_MAX|ENSG00000125...,TGGACATGTTGACTTACCAAGTTCTATCTGATCAGTCACACTCACA...,TGGACATGTTGACTTACCAAGTTCTATCTGATCAGTCACACTCACA...,[110],True,0.421569,-0.126123,6.540612e-24,...,0.113314,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_MAX|ENSG00000125...,[NC_000014.9:65081553:C:T],NC_000014.9:65081553:C:T,14:65081553:C:T,14:65081553:C:T,0.190930,-1.250940,0.210962
10485,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,cardiac_neuro_cava_random:REF_RAD51B|ENSG00000...,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,GGAAGCCTCAAGGAACTTTCATCCCAAAGGGAAGCTTTGAAGAATA...,GGAAGCCTCAAGGAACTTTCATCCCAAAGGGAAGCTTTGAAGAATA...,[192],True,0.977337,0.013006,1.000000e+00,...,-0.063186,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,[NC_000014.9:68181607:A:G],NC_000014.9:68181607:A:G,14:68181607:A:G,14:68181607:A:G,0.008940,0.464997,0.641935
11214,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,cardiac_neuro_cava_random:REF_RAD51B|ENSG00000...,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,TCCAAACATGGACCATGTATTGCTACAAAGGAAGCAATAGTGTGCT...,TCCAAACATGGACCATGTATTGCTACAAAGGAAGCAATAGTGTGCT...,[224],True,0.933713,-0.043983,1.000000e+00,...,-0.022611,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,[NC_000014.9:68563142:G:A],NC_000014.9:68563142:G:A,14:68563142:G:A,14:68563142:G:A,0.165551,0.276866,0.781884
11856,cardiac_neuro_cava_random:ALT_MEIS2|ENSG000001...,cardiac_neuro_cava_random:REF_MEIS2|ENSG000001...,cardiac_neuro_cava_random:ALT_MEIS2|ENSG000001...,GTCAGATTGTGATGAGAATGGAGACCGTCGGGGCAGTGTTTGAAGG...,GTCAGATTGTGATGAGAATGGAGACCGTCGGGGCAGTGTTTGAAGG...,[168],True,0.015541,-0.318044,2.121407e-01,...,0.001798,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_MEIS2|ENSG000001...,[NC_000015.10:36888182:G:C],NC_000015.10:36888182:G:C,15:36888182:G:C,15:36888182:G:C,0.409422,0.669962,0.502885
12269,cardiac_neuro_cava_random:ALT_DMXL2|ENSG000001...,cardiac_neuro_cava_random:REF_DMXL2|ENSG000001...,cardiac_neuro_cava_random:ALT_DMXL2|ENSG000001...,TGCATTTAAGTTTAGCCATTGCCTTAGTGCATGTAATTCTGCCTTT...,TGCATTTAAGTTTAGCCATTGCCTTAGTGCATGTAATTCTGCCTTT...,[172],True,0.709068,-0.072395,1.000000e+00,...,-0.066655,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_DMXL2|ENSG000001...,[NC_000015.10:51576543:C:T],NC_000015.10:51576543:C:T,15:51576543:C:T,15:51576543:C:T,0.098233,-0.441981,0.658505
14726,cardiac_neuro_cava_random:ALT_GNAO1|ENSG000000...,cardiac_neuro_cava_random:REF_GNAO1|ENSG000000...,cardiac_neuro_cava_random:ALT_GNAO1|ENSG000000...,TGGAGGAAAACCTGACTTATAACTGACAAATTGGTACAGACTCAGT...,TGGAGGAAAACCTGACTTATAACTGACAAATTGGTACAGACTCAGT...,[163],True,0.585374,-0.107989,1.000000e+00,...,-0.020924,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_GNAO1|ENSG000000...,[NC_000016.10:56373184:C:T],NC_000016.10:56373184:C:T,16:56373184:C:T,16:56373184:C:T,0.052278,0.424493,0.671208
16015,cardiac_neuro_cava_random:ALT_ANKRD11|ENSG0000...,cardiac_neuro_cava_random:REF_ANKRD11|ENSG0000...,cardiac_neuro_cava_random:ALT_ANKRD11|ENSG0000...,CCAGCCCGTGCAGCCTGCCAGGACTCTTCCAGACACGGGATTTGTC...,CCAGCCCGTGCAGCCTGCCAGGACTCTTCCAGACACGGGATTTGTC...,[210],True,0.683077,0.207703,1.000000e+00,...,-0.068297,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_ANKRD11|ENSG0000...,[NC_000016.10:89431119:G:A],NC_000016.10:89431119:G:A,16:89431119:G:A,16:89431119:G:A,0.003288,0.214120,0.830454
16180,cardiac_neuro_cava_random:ALT_PIGL|ENSG0000010...,cardiac_neuro_cava_random:REF_PIGL|ENSG0000010...,cardiac_neuro_cava_random:ALT_PIGL|ENSG0000010...,CTGATAAATCCATTTATTTATTTATTTATTTGAGACCAGGTCTTGT...,CTGATAAATCCATTTATTTATTTATTTATTTGAGACCAGGTCTTGT...,[90],True,0.830221,-0.073084,1.000000e+00,...,-0.041194,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_PIGL|ENSG0000010...,[NC_000017.11:16331671:C:T],NC_000017.11:16331671:C:T,17:16331671:C:T,17:16331671:C:T,0.000002,-1.770780,0.076604
20250,cardiac_neuro_cava_random:ALT_MOGS|ENSG0000011...,cardiac_neuro_cava_random:REF_MOGS|ENSG0000011...,cardiac_neuro_cava_random:ALT_MOGS|ENSG0000011...,GACTCTTTAAGGCCTGGCCCACACATTCTGTGGTCCTGATGGGAGT...,GACTCTTTAAGGCCTGGCCCACACATTCTGTGGTCCTGATGGGAGT...,[97],True,0.998115,-0.001570,1.000000e+00,...,-0.025013,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_MOGS|ENSG0000011...,[NC_000002.12:74488452:A:G],NC_000002.12:74488452:A:G,2:74488452:A:G,2:74488452:A:G,0.181626,0.674638,0.499909
20649,cardiac_neuro_cava_random:ALT_BAZ2B|ENSG000001...,cardiac_neuro_cava_random:REF_BAZ2B|ENSG000001...,cardiac_neuro_cava_random:ALT_BAZ2B|ENSG000001...,GCTCAAACTTTTAGTAGGTTCTGCAACCCACACACAGATAATTGGC...,GCTCAAACTTTTAGTAGGTTCTGCAACCCACACACAGATAATTGGC...,[221],True,0.775545,0.094098,4.511542e-01,...,-0.066476,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_BAZ2B|ENSG000001...,[NC_000002.12:159659126:T:C],NC_000002.12:159659126:T:C,2:159659126:T:C,2:159659126:T:C,0.001063,-0.840820,0.400453
21098,cardiac_neuro_cava_random:ALT_ANKZF1|ENSG00000...,cardiac_neuro_cava_random:REF_ANKZF1|ENSG00000...,cardiac_neuro_cava_random:ALT_ANKZF1|ENSG00000...,TCCACCAATCCACAGCCTCCCATAGGTGGGTCACTTGAGTGGGGGC...,TCCACCAATCCACAGCCTCCCATAGGTGGGTCACTTGAGTGGGGGC...,[68],True,0.733707,0.176648,1.000000e+00,...,0.029980,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_ANKZF1|ENSG00000...,[NC_000002.12:219214918:C:T],NC_000002.12:219214918:C:T,2:219214918:C:T,2:219214918:C:T,0.046246,0.511034,0.609329
23090,cardiac_neuro_cava_random:ALT_LZTR1|ENSG000000...,cardiac_neuro_cava_random:REF_LZTR1|ENSG000000...,cardiac_neuro_cava_random:ALT_LZTR1|ENSG000000...,TCAAGGACAAGACGTGAGTACTCTGGCCAGTGGGGTGGAGGGAGGA...,TCAAGGACAAGACGTGAGTACTCTGGCCAGTGGGGTGGAGGGAGGA...,[150],True,0.748849,0.181961,7.328173e-01,...,-0.069791,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_LZTR1|ENSG000000...,[NC_000022.11:20990662:C:T],NC_000022.11:20990662:C:T,22:20990662:C:T,22:20990662:C:T,0.278179,0.658497,0.510222
23340,cardiac_neuro_cava_random:ALT_NF2|ENSG00000186...,cardiac_neuro_cava_random:REF_NF2|ENSG00000186...,cardiac_neuro_cava_random:ALT_NF2|ENSG00000186...,GAGGAGTACTACTTATTTCCAAAAGTGTTCTAGGTCCAGATAGGAG...,GAGGAGTACTACTTATTTCCAAAAGTGTTCTAGGTCCAGATAGGAG...,[146],True,0.953895,0.022649,1.000000e+00,...,-0.003324,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_NF2|ENSG00000186...,[NC_000022.11:29594127:A:C],NC_000022.11:29594127:A:C,22:29594127:A:C,22:29594127:A:C,0.051933,-0.119683,0.904735
25874,cardiac_neuro_cava_random:ALT_ARHGAP31|ENSG000...,cardiac_neuro_cava_random:REF_ARHGAP31|ENSG000...,cardiac_neuro_cava_random:ALT_ARHGAP31|ENSG000...,AAACAAAGGCCTCTCACAGGGCCTTCCCACCCCCAGCCAGCTGTAT...,AAACAAAGGCCTCTCACAGGGCCTTCCCACCCCCAGCCAGCTGTAT...,[237],True,0.424952,-0.194227,1.000000e+00,...,-0.057317,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_ARHGAP31|ENSG000...,[NC_000003.12:119329868:T:C],NC_000003.12:119329868:T:C,3:119329868:T:C,3:119329868:T:C,0.170444,-0.543551,0.586753
25975,cardiac_neuro_cava_random:ALT_CFAP91|ENSG00000...,cardiac_neuro_cava_random:REF_CFAP91|ENSG00000...,cardiac_neuro_cava_random:ALT_CFAP91|ENSG00000...,ACAAACTTTTACTGAATACCTCTTCTTGGCCTGGAGCTTGAAATGC...,ACAAACTTTTACTGAATACCTCTTCTTGGCCTGGAGCTTGAAATGC...,[120],True,0.979765,-0.013626,1.000000e+00,...,-0.008562,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_CFAP91|ENSG00000...,[NC_000003.12:119732104:A:G],NC_000003.12:119732104:A:G,3:119732104:A:G,3:119732104:A:G,0.002127,-0.379447,0.704357
26832,cardiac_neuro_cava_random:ALT_PPP3CA|ENSG00000...,cardiac_neuro_cava_random:REF_PPP3CA|ENSG00000...,cardiac_neuro_cava_random:ALT_PPP3CA|ENSG00000...,AAAAATTATGATGCATGTGTAAAGCAAGAACAATTTGCAGGGAATA...,AAAAATTATGATGCATGTGTAAAGCAAGAACAATTTGCAGGGAATA...,[232],True,0.936843,-0.048404,1.000000e+00,...,-0.067971,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_PPP3CA|ENSG00000...,[NC_000004.12:101144375:G:A],NC_000004.12:101144375:G:A,4:101144375:G:A,4:101144375:G:A,0.237883,-0.298408,0.765393
27814,cardiac_neuro_cava_random:ALT_TRIO|ENSG0000003...,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,cardiac_neuro_cava_random:ALT_TRIO|ENSG0000003...,AGTAGTGATACATGCTACAATATAAGTGAACCTTGAAAAACATTTT...,AGTAGTGATACATGCTACAATATAAGTGAACCTTGAAAAACATTTT...,[52],True,0.979491,-0.009908,1.000000e+00,...,0.003307,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_TRIO|ENSG0000003...,[NC_000005.10:14098317:T:C],NC_000005.10:14098317:T:C,5:14098317:T:C,5:14098317:T:C,0.035019,1.293540,0.195831
30202,cardiac_neuro_cava_random:ALT_H1-3|ENSG0000012...,cardiac_neuro_cava_random:REF_H1-3|ENSG0000012...,cardiac_neuro_cava_random:ALT_H1-3|ENSG0000012...,AAATCTGTTTTATATGAGAAGAGAAACAACAGGTTCTTTTTGAATT...,AAATCTGTTTTATATGAGAAGAGAAACAACAGGTTCTTTTTGAATT...,[203],True,0.772861,-0.087815,1.000000e+00,...,-0.032883,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_H1-3|ENSG0000012...,[NC_000006.12:26194869:A:G],NC_000006.12:26194869:A:G,6:26194869:A:G,6:26194869:A:G,0.130164,0.259039,0.795606
33053,cardiac_neuro_cava_random:ALT_CUX1|ENSG0000025...,cardiac_neuro_cava_random:REF_CUX1|ENSG0000025...,cardiac_neuro_cava_random:ALT_CUX1|ENSG0000025...,TGTCCTCTTTGTCAGGTGAGTTTATACCTTTCTGTTCCAAAGCAAA...,TGTCCTCTTTGTCAGGTGAGTTTATACCTTTCTGTTCCAAAGCAAA...,[77],True,0.924957,-0.027839,1.000000e+00,...,-0.027322,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_CUX1|ENSG0000025...,[NC_000007.14:101854168:G:A],NC_000007.14:101854168:G:A,7:101854168:G:A,7:101854168:G:A,0.450036,-0.431312,0.666243
33855,cardiac_neuro_cava_random:ALT_PRKAG2|ENSG00000...,cardiac_neuro_cava_random:REF_PRKAG2|ENSG00000...,cardiac_neuro_cava_random:ALT_PRKAG2|ENSG00000...,ATGGTATGACTATGAGGTCATTCTAGACAGAGATGGGTCAGGTCCC...,ATGGTATGACTATGAGGTCATTCTAGACAGAGATGGGCCAGGTCCC...,[37],True,0.523593,0.186315,6.751745e-22,...,0.494082,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_PRKAG2|ENSG00000...,[NC_000007.14:151739265:A:G],NC_000007.14:151739265:A:G,7:151739265:A:G,7:151739265:A:G,0.021467,0.899998,0.368126
33927,cardiac_neuro_cava_random:ALT_PRKAG2|ENSG00000...,cardiac_neuro_cava_random:REF_PRKAG2|ENSG00000...,cardiac_neuro_cava_random:ALT_PRKAG2|ENSG00000...,TTTCCTTTCCGTTCCTTGAGTGCCTGCGAGCACTGCGAGAGCCTCC...,TTTCCTTTCCGTTCCTTGAGTGCCTGCGAGCACTGCGAGAGCCTCC...,[56],True,0.749526,-0.086782,1.000000e+00,...,-0.013440,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_PRKAG2|ENSG00000...,[NC_000007.14:151806382:A:G],NC_000007.14:151806382:A:G,7:151806382:A:G,7:151806382:A:G,0.021213,0.985712,0.324279
34726,cardiac_neuro_cava_random:ALT_PPP2R2A|ENSG0000...,cardiac_neuro_cava_random:REF_PPP2R2A|ENSG0000...,cardiac_neuro_cava_random:ALT_PPP2R2A|ENSG0000...,GATCTGTTCTCTCTGGCTTTACTTTGTCTAATCACTACCCCTTTGC...,GATCTGTTCTCTCTGGCTTTACTTTGTCTAATCACTACCCCTTTGC...,[50],True,0.067249,0.231794,1.000000e+00,...,-0.005000,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_PPP2R2A|ENSG0000...,[NC_000008.11:26410134:G:A],NC_000008.11:26410134:G:A,8:26410134:G:A,8:26410134:G:A,0.014029,-1.658310,0.097262
35628,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,cardiac_neuro_cava_random:REF_CDKN2B|ENSG00000...,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,GGAATTGAGATTCAGACTCAGGTCTGTCTTACTTCAGGGCCCTTGA...,GGAATTGAGATTCAGACTCAGGTCTGTCTTACTTCAGGGCCCTTGA...,[165],True,0.997045,-0.002331,1.000000e+00,...,0.004920,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,[NC_000009.12:22049555:C:T],NC_000009.12:22049555:C:T,9:22049555:C:T,9:22049555:C:T,0.475714,-1.651470,0.098649
35637,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,cardiac_neuro_cava_random:REF_CDKN2B|ENSG00000...,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,GGGCTTTGTGGTGTGTAGATTTAGTTGCTCATACAAGAACCTGGGA...,GGGCTTTGTGGTGTGTAGATTTAGTTGCTCATACAAGAACCTGGGA...,[134],True,0.996140,0.002538,1.000000e+00,...,0.033374,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,[NC_000009.12:22052734:T:C],NC_000009.12:22052734:T:C,9:22052734:T:C,9:22052734:T:C,0.427281,-1.835270,0.066472
35638,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,cardiac_neuro_cava_random:REF_CDKN2B|ENSG00000...,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,GGGCTTTGTGGTGTGTAGATTTAGTTGCTCATACAAGAACCTGGGA...,GGGCTTTGTGGTGTGTAGATTTAGTTGCTCATACAAGAACCTGGGA...,[58],True,0.729287,-0.082865,1.000000e+00,...,0.010319,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_CDKN2B|ENSG00000...,[NC_000009.12:22052810:G:C],NC_000009.12:22052810:G:C,9:22052810:G:C,9:22052810:G:C,0.478949,-1.423760,0.154522
36123,cardiac_neuro_cava_random:ALT_GABBR2|ENSG00000...,cardiac_neuro_cava_random:REF_GABBR2|ENSG00000...,cardiac_neuro_cava_random:ALT_GABBR2|ENSG00000...,CCAAATACTATGTGAAATGACAGTTTTCAGACATGGGCTACAAGCA...,CCAAATACTATGTGAAATGACAGTTTTCAGACATGGGCTACAAGCA...,[224],True,0.857471,-0.126026,1.000000e+00,...,-0.055904,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_GABBR2|ENSG00000...,[NC_000009.12:98430707:C:T],NC_000009.12:98430707:C:T,9:98430707:C:T,9:98430707:C:T,0.325599,0.079234,0.936847
36575,cardiac_neuro_cava_random:ALT_ABL1|ENSG0000009...,cardiac_neuro_cava_random:REF_ABL1|ENSG0000009...,cardiac_neuro_cava_random:ALT_ABL1|ENSG0000009...,GATACGAGATTCCTCTGAGATGCTCTTTAGTCCAGGCAGGTTTATG...,GATACGAGATTCCTCTGAGATGCTCTTTAGTCCAGGCAGGTTTATG...,[218],True,0.972943,-0.012638,1.000000e+00,...,-0.016657,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_ABL1|ENSG0000009...,[NC_000009.12:130840012:C:T],NC_000009.12:130840012:C:T,9:130840012:C:T,9:130840012:C:T,0.145016,0.071123,0.943300

#### Investigate the signficant variants

In [73]:
# investigate significant variants
sig_level = 0.1
variant_info_filtered_spdi_tested_coffee_consumed_annotated_sig = variant_info_filtered_spdi_tested_coffee_consumed_annotated.loc[(variant_info_filtered_spdi_tested_coffee_consumed_annotated['bcalm_variant_effect_adjusted_p_value'] < sig_level) & (variant_info_filtered_spdi_tested_coffee_consumed_annotated['pval'] < sig_level)].copy()
print("Number of significant variants", variant_info_filtered_spdi_tested_coffee_consumed_annotated_sig.shape[0])

Number of significant variants 1

In [ ]:
variant_info_filtered_spdi_tested_coffee_consumed_annotated_sig

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,...,bcalm_alternative_log_ratio_activity,label,name,SPDI,SPDI_elem,SPDI_elem_chrom,variant,minor_AF,tstat,pval
34726,cardiac_neuro_cava_random:ALT_PPP2R2A|ENSG0000...,cardiac_neuro_cava_random:REF_PPP2R2A|ENSG0000...,cardiac_neuro_cava_random:ALT_PPP2R2A|ENSG0000...,GATCTGTTCTCTCTGGCTTTACTTTGTCTAATCACTACCCCTTTGC...,GATCTGTTCTCTCTGGCTTTACTTTGTCTAATCACTACCCCTTTGC...,[50],True,0.067249,0.231794,1.0,...,-0.005,cardiac_neuro_cava_random,cardiac_neuro_cava_random:ALT_PPP2R2A|ENSG0000...,[NC_000008.11:26410134:G:A],NC_000008.11:26410134:G:A,8:26410134:G:A,8:26410134:G:A,0.014029,-1.65831,0.097262

### Download all the gwas data using the manifest file
- TODO: load the manifest file and filter for only interesting rows (remove the male female specific ones; remove truncated rows)

In [ ]:
# Corrected command: p-value is in column 11, handle NaN
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/age.gwas.imputed_v3.both_sexes.tsv.bgz -O age.gwas.imputed_v3.both_sexes.tsv.bgz \
| zcat \
| awk 'BEGIN {FS="\t"} NR==1 || ($11 != "NaN" && $11 <= 5e-8) {print}' \
> age.gwas.imputed_v3.both_sexes.significant.tsv

wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/annotations/updated_phenotypes.both_sexes.v2.tsv -O updated_phenotypes.both_sexes.v2.tsv

In [2]:
import pandas as pd

In [3]:
manifest_path = "/home/kisa/coding/80K_MPRA/collaborations/ludwig_gwas_annotation_data/UKBB GWAS Imputed v3 - File Manifest Release 20180731 - Manifest 201807.tsv"
manifest_df = pd.read_csv(manifest_path, sep="\t")
manifest_df

,Phenotype Code,Phenotype Description,UK Biobank Data Showcase Link,Sex,File,wget command,AWS File,Dropbox File,md5s
0,NaN,README,NaN,NaN,README,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/wro30igqkmit5ig/READ...,bd14f2be665e6c915a3f6cee0a67b8dc
1,NaN,MD5 Values for files in this manifest,NaN,NaN,2018_gwas_imputed_md5.20240212.txt,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/dakt3shhn8b6wqr/2018...,NaN
2,NaN,Phenotype summary file - both_sexes,NaN,both_sexes,phenotypes.both_sexes.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/d4mlq9ly93yhjyt/phen...,cba910ee6f93eaed9d318edcd3f1ce18
3,NaN,Phenotype summary file - female,NaN,female,phenotypes.female.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/r7idtoulxfpyjss/phen...,ef1b494a5aa3f41bfab376efe8fa7250
4,NaN,Phenotype summary file - male,NaN,male,phenotypes.male.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/mywldevz4nsla2r/phen...,9f3385f31498de6b01956ec02d53dff7
...,...,...,...,...,...,...,...,...,...
11925,30897_irnt,Estimated sample dilution factor (quantile),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,female,30897_irnt.gwas.imputed_v3.female.varorder.tsv...,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/niyqjqc9pu1gcyl/3089...,6e44d3d1fe2deec912c46a3b289c18cf
11926,30897_irnt,Estimated sample dilution factor (quantile),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,male,30897_irnt.gwas.imputed_v3.male.varorder.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/0d2d7vq64cayb61/3089...,4fa62266d94fcd501efa3c02a64dd336
11927,30897_raw,Estimated sample dilution factor (factor),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,30897_raw.gwas.imputed_v3.both_sexes.varorder....,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/8qkf9j8f1yl03dy/3089...,eb382eb66034f5a596c614dd68baed80
11928,30897_raw,Estimated sample dilution factor (factor),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,female,30897_raw.gwas.imputed_v3.female.varorder.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/i8i6p0fthoim47c/3089...,43e0928ffd5ea9f7aeb368c05117b034
11929,30897_raw,Estimated sample dilution factor (factor),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,male,30897_raw.gwas.imputed_v3.male.varorder.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/sizij1vtlhkm4c6/3089...,58ed6d331262c70893a15f5eed116b2b

In [4]:
# remove missing Phenotype Code
manifest_df_filtered = manifest_df.loc[~manifest_df['Phenotype Code'].isna()].copy()

# only keep both sexes: Sex == both_sexes
manifest_df_filtered = manifest_df_filtered.loc[manifest_df_filtered['Sex'] == 'both_sexes'].copy()
manifest_df_filtered

,Phenotype Code,Phenotype Description,UK Biobank Data Showcase Link,Sex,File,wget command,AWS File,Dropbox File,md5s
18,is_female,Inferred genetic sex,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,is_female.gwas.imputed_v3.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/qmod3bx3p621urg/is_f...,2a1c79a7e6889dcd905dcfb36f3ec529
19,age,Age at recruitment,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,age.gwas.imputed_v3.both_sexes.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/x02h89mis8fe6md/age....,b2aa0ca8e34b385fced3948b62c8f19a
22,100001_irnt,Food weight,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,100001_irnt.gwas.imputed_v3.both_sexes.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/numenv46xtmpin2/1000...,e54db7eb4df1fe0dc9a09a5c47d77e7c
25,100001_raw,Food weight,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,100001_raw.gwas.imputed_v3.both_sexes.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/5tipfnkl7j3fg0c/1000...,da3a95175b5ecc2024f65947f1d350a0
28,100002_irnt,Energy,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,100002_irnt.gwas.imputed_v3.both_sexes.tsv.bgz,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/194230uv6xcouva/1000...,7a1373fbb5c3f5a4efed28356ffb631c
...,...,...,...,...,...,...,...,...,...
11915,30880_raw,Urate (umol/L),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,30880_raw.gwas.imputed_v3.both_sexes.varorder....,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/1l8zpo2ivikdh8x/3088...,bbacee18dc5f843f428e101d8fb5c876
11918,30890_irnt,Vitamin D (quantile),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,30890_irnt.gwas.imputed_v3.both_sexes.varorder...,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/bbbnj239w1kjkyi/3089...,3b7daee50c1dab8a24e422e22ae84d02
11921,30890_raw,Vitamin D (nmol/L),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,30890_raw.gwas.imputed_v3.both_sexes.varorder....,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/2kbx4nqmzlvetj0/3089...,b2917f9e849bb3f6e00cb67601dbb093
11924,30897_irnt,Estimated sample dilution factor (quantile),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,30897_irnt.gwas.imputed_v3.both_sexes.varorder...,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/pmqehlcilv4kglf/3089...,243e44d98c31eefcf9accb7ff20e4be8
11927,30897_raw,Estimated sample dilution factor (factor),http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,both_sexes,30897_raw.gwas.imputed_v3.both_sexes.varorder....,wget https://broad-ukb-sumstats-us-east-1.s3.a...,https://broad-ukb-sumstats-us-east-1.s3.amazon...,https://www.dropbox.com/s/8qkf9j8f1yl03dy/3089...,eb382eb66034f5a596c614dd68baed80

wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/is_female.gwas.imputed_v3.tsv.bgz -O is_female.gwas.imputed_v3.tsv.bgz

In [6]:
# sanity check if all wget command contain -O
def check_O_option_wget(command):
    return "-O" in command
manifest_df_filtered['wget_command_valid'] = manifest_df_filtered['wget command'].apply(check_O_option_wget)
# check if all wget commands are valid
if manifest_df_filtered['wget_command_valid'].all():
    print("All wget commands are valid.")

All wget commands are valid.

In [7]:
manifest_df_filtered.columns

Index(['Phenotype Code', 'Phenotype Description',
       'UK Biobank Data Showcase Link', 'Sex', 'File', 'wget command',
       'AWS File', 'Dropbox File', 'md5s', 'wget_command_valid'],
      dtype='object')

In [10]:
import os

In [11]:
output_path = "/home/kisa/coding/80K_MPRA/collaborations/ludwig_gwas_annotation_data/"
manifest_df_filtered.to_csv(os.path.join(output_path, "UKBB_GWAS_Imputed_v3_manifest_release_20180731_filtered.tsv"), sep="\t", index=False)

### Combine the downloaded data and the variant infor using SLURM on the BIH cluster

In [ ]:
# process_gwas.py

import pandas as pd
import os
import sys
import gzip

def process_single_gwas_file(gwas_filepath, variant_info_filepath, output_dir):
    """
    Processes a single gzipped GWAS result file, merges it with variant information,
    filters for overlapping variants, adds a source file column, and saves the result.

    Args:
        gwas_filepath (str): Path to the gzipped GWAS results file.
        variant_info_filepath (str): Path to the variant information TSV file.
        output_dir (str): Directory to save the processed output files.
    """
    try:
        # Extract the base name of the GWAS file without extension for output naming
        gwas_filename = os.path.basename(gwas_filepath)
        # Remove all extensions (.tsv.gz) to get the clean base name
        base_filename_no_ext = gwas_filename.replace('.tsv.gz', '')

        print(f"Processing file: {gwas_filepath}")

        # Load the GWAS results file
        # Using 'engine="c"' for faster reading of TSV files
        coffee_consumed_df = pd.read_csv(gwas_filepath, sep='\t', compression='gzip', engine='c')
        print(f"Loaded GWAS file: {gwas_filepath} with {len(coffee_consumed_df)} rows.")

        # Load the variant information file
        variant_info_df = pd.read_csv(variant_info_filepath, sep='\t', engine='c')
        print(f"Loaded variant info file: {variant_info_filepath} with {len(variant_info_df)} rows.")

        # Perform the merge operation as specified by the user
        # Assumption: 'SPDI_elem_chrom' in variant_info_df and 'variant' in coffee_consumed_df
        # contain comparable identifiers for merging. If 'SPDI_elem_chrom' is just a chromosome,
        # this merge will likely not yield specific variant overlaps.
        variant_info_filtered_spdi_tested_coffee_consumed = variant_info_df.merge(
            coffee_consumed_df[['variant', 'minor_AF', 'tstat', 'pval']],
            left_on='SPDI_elem_chrom',  # Key from variant_info_df
            right_on='variant',         # Key from coffee_consumed_df
            how='left'
        ).copy()
        print(f"Merged data. Resulting shape: {variant_info_filtered_spdi_tested_coffee_consumed.shape}")

        # Filter out rows where 'pval' is NaN (i.e., no overlap found)
        variant_info_filtered_spdi_tested_coffee_consumed_annotated = \
            variant_info_filtered_spdi_tested_coffee_consumed.loc[
                ~variant_info_filtered_spdi_tested_coffee_consumed['pval'].isna()
            ].copy()
        print(f"Filtered for overlapping variants. Remaining rows: {len(variant_info_filtered_spdi_tested_coffee_consumed_annotated)}")

        # Check if the resulting table is not empty
        if not variant_info_filtered_spdi_tested_coffee_consumed_annotated.empty:
            # Add the 'source_file' column
            variant_info_filtered_spdi_tested_coffee_consumed_annotated['source_file'] = gwas_filename

            # Define the output filename based on the input file and number of rows
            num_rows = len(variant_info_filtered_spdi_tested_coffee_consumed_annotated)
            output_filename = f"{base_filename_no_ext}_overlap_{num_rows}.tsv.gz"
            output_filepath = os.path.join(output_dir, output_filename)

            # Ensure the output directory exists
            os.makedirs(output_dir, exist_ok=True)

            # Write the annotated DataFrame to a gzipped TSV file
            variant_info_filtered_spdi_tested_coffee_consumed_annotated.to_csv(
                output_filepath,
                sep='\t',
                compression='gzip',
                index=False
            )
            print(f"Successfully saved {num_rows} overlapping variants to: {output_filepath}")
        else:
            print(f"No overlapping variants found for {gwas_filepath}. No output file generated.")

    except FileNotFoundError:
        print(f"Error: One of the input files not found. GWAS: {gwas_filepath}, Variant Info: {variant_info_filepath}")
        sys.exit(1)
    except pd.errors.EmptyDataError:
        print(f"Error: GWAS file {gwas_filepath} is empty or malformed.")
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred while processing {gwas_filepath}: {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python process_gwas.py <gwas_filepath> <variant_info_filepath> <output_directory>")
        sys.exit(1)

    gwas_filepath = sys.argv[1]
    variant_info_filepath = sys.argv[2]
    output_dir = sys.argv[3]

    process_single_gwas_file(gwas_filepath, variant_info_filepath, output_dir)